"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _CameraState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CameraStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CameraState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CAMERA_UNSPECIFIED: _CameraState.ValueType  # 0
    CAMERA_ON: _CameraState.ValueType  # 1
    CAMERA_OFF: _CameraState.ValueType  # 2

class CameraState(_CameraState, metaclass=_CameraStateEnumTypeWrapper): ...

CAMERA_UNSPECIFIED: CameraState.ValueType  # 0
CAMERA_ON: CameraState.ValueType  # 1
CAMERA_OFF: CameraState.ValueType  # 2
Global___CameraState: _TypeAlias = CameraState  # noqa: Y015

class _VideoHistorySetting:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _VideoHistorySettingEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_VideoHistorySetting.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VIDEO_HISTORY_UNSPECIFIED: _VideoHistorySetting.ValueType  # 0
    VIDEO_HISTORY_LEGACY_NONE: _VideoHistorySetting.ValueType  # 1
    VIDEO_HISTORY_EVENTS_24_7: _VideoHistorySetting.ValueType  # 2
    VIDEO_HISTORY_EVENTS: _VideoHistorySetting.ValueType  # 3
    VIDEO_HISTORY_LEGACY_EVENTS: _VideoHistorySetting.ValueType  # 4
    VIDEO_HISTORY_NONE: _VideoHistorySetting.ValueType  # 5

class VideoHistorySetting(_VideoHistorySetting, metaclass=_VideoHistorySettingEnumTypeWrapper): ...

VIDEO_HISTORY_UNSPECIFIED: VideoHistorySetting.ValueType  # 0
VIDEO_HISTORY_LEGACY_NONE: VideoHistorySetting.ValueType  # 1
VIDEO_HISTORY_EVENTS_24_7: VideoHistorySetting.ValueType  # 2
VIDEO_HISTORY_EVENTS: VideoHistorySetting.ValueType  # 3
VIDEO_HISTORY_LEGACY_EVENTS: VideoHistorySetting.ValueType  # 4
VIDEO_HISTORY_NONE: VideoHistorySetting.ValueType  # 5
Global___VideoHistorySetting: _TypeAlias = VideoHistorySetting  # noqa: Y015

@_typing.final
class RecordingToggleSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGETCAMERASTATE_FIELD_NUMBER: _builtins.int
    CHANGEMODEREASON_FIELD_NUMBER: _builtins.int
    SETTINGSUPDATED_FIELD_NUMBER: _builtins.int
    targetCameraState: Global___CameraState.ValueType
    changeModeReason: _builtins.int
    @_builtins.property
    def settingsUpdated(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        targetCameraState: Global___CameraState.ValueType = ...,
        changeModeReason: _builtins.int = ...,
        settingsUpdated: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["settingsUpdated", b"settingsUpdated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["changeModeReason", b"changeModeReason", "settingsUpdated", b"settingsUpdated", "targetCameraState", b"targetCameraState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RecordingToggleSettingsTrait: _TypeAlias = RecordingToggleSettingsTrait  # noqa: Y015

@_typing.final
class RecordingToggleTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENTCAMERASTATE_FIELD_NUMBER: _builtins.int
    CHANGEMODEREASON_FIELD_NUMBER: _builtins.int
    TOGGLEUPDATED_FIELD_NUMBER: _builtins.int
    currentCameraState: Global___CameraState.ValueType
    changeModeReason: _builtins.int
    @_builtins.property
    def toggleUpdated(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        currentCameraState: Global___CameraState.ValueType = ...,
        changeModeReason: _builtins.int = ...,
        toggleUpdated: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["toggleUpdated", b"toggleUpdated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["changeModeReason", b"changeModeReason", "currentCameraState", b"currentCameraState", "toggleUpdated", b"toggleUpdated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RecordingToggleTrait: _TypeAlias = RecordingToggleTrait  # noqa: Y015

@_typing.final
class RecordingEncoderSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _RecordingQuality:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RecordingQualityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[RecordingEncoderSettingsTrait._RecordingQuality.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        RECORDING_QUALITY_UNSPECIFIED: RecordingEncoderSettingsTrait._RecordingQuality.ValueType  # 0
        RECORDING_QUALITY_LOW: RecordingEncoderSettingsTrait._RecordingQuality.ValueType  # 1
        RECORDING_QUALITY_MEDIUM: RecordingEncoderSettingsTrait._RecordingQuality.ValueType  # 2
        RECORDING_QUALITY_MEDIUM_HIGH: RecordingEncoderSettingsTrait._RecordingQuality.ValueType  # 3
        RECORDING_QUALITY_HIGH: RecordingEncoderSettingsTrait._RecordingQuality.ValueType  # 4

    class RecordingQuality(_RecordingQuality, metaclass=_RecordingQualityEnumTypeWrapper): ...
    RECORDING_QUALITY_UNSPECIFIED: RecordingEncoderSettingsTrait.RecordingQuality.ValueType  # 0
    RECORDING_QUALITY_LOW: RecordingEncoderSettingsTrait.RecordingQuality.ValueType  # 1
    RECORDING_QUALITY_MEDIUM: RecordingEncoderSettingsTrait.RecordingQuality.ValueType  # 2
    RECORDING_QUALITY_MEDIUM_HIGH: RecordingEncoderSettingsTrait.RecordingQuality.ValueType  # 3
    RECORDING_QUALITY_HIGH: RecordingEncoderSettingsTrait.RecordingQuality.ValueType  # 4

    RECORDINGQUALITY_FIELD_NUMBER: _builtins.int
    recordingQuality: Global___RecordingEncoderSettingsTrait.RecordingQuality.ValueType
    def __init__(
        self,
        *,
        recordingQuality: Global___RecordingEncoderSettingsTrait.RecordingQuality.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recordingQuality", b"recordingQuality"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RecordingEncoderSettingsTrait: _TypeAlias = RecordingEncoderSettingsTrait  # noqa: Y015

@_typing.final
class MediaQualitySettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _MediaQuality:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MediaQualityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MediaQualitySettingsTrait._MediaQuality.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MEDIA_QUALITY_UNSPECIFIED: MediaQualitySettingsTrait._MediaQuality.ValueType  # 0
        MEDIA_QUALITY_LOW_OR_MEDIUM: MediaQualitySettingsTrait._MediaQuality.ValueType  # 1
        MEDIA_QUALITY_HIGH: MediaQualitySettingsTrait._MediaQuality.ValueType  # 2

    class MediaQuality(_MediaQuality, metaclass=_MediaQualityEnumTypeWrapper): ...
    MEDIA_QUALITY_UNSPECIFIED: MediaQualitySettingsTrait.MediaQuality.ValueType  # 0
    MEDIA_QUALITY_LOW_OR_MEDIUM: MediaQualitySettingsTrait.MediaQuality.ValueType  # 1
    MEDIA_QUALITY_HIGH: MediaQualitySettingsTrait.MediaQuality.ValueType  # 2

    MEDIAQUALITY_FIELD_NUMBER: _builtins.int
    mediaQuality: Global___MediaQualitySettingsTrait.MediaQuality.ValueType
    def __init__(
        self,
        *,
        mediaQuality: Global___MediaQualitySettingsTrait.MediaQuality.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mediaQuality", b"mediaQuality"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MediaQualitySettingsTrait: _TypeAlias = MediaQualitySettingsTrait  # noqa: Y015

@_typing.final
class ActivityZoneSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ActivityZone(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ActivityZoneProperties(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            @_typing.final
            class Coordinate(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                X_FIELD_NUMBER: _builtins.int
                Y_FIELD_NUMBER: _builtins.int
                x: _builtins.float
                y: _builtins.float
                def __init__(
                    self,
                    *,
                    x: _builtins.float = ...,
                    y: _builtins.float = ...,
                ) -> None: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            NAME_FIELD_NUMBER: _builtins.int
            INTERNALINDEX_FIELD_NUMBER: _builtins.int
            VERTICES_FIELD_NUMBER: _builtins.int
            ZONEID_FIELD_NUMBER: _builtins.int
            name: _builtins.str
            internalIndex: _builtins.int
            zoneId: _builtins.int
            @_builtins.property
            def vertices(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActivityZoneSettingsTrait.ActivityZone.ActivityZoneProperties.Coordinate]: ...
            def __init__(
                self,
                *,
                name: _builtins.str = ...,
                internalIndex: _builtins.int = ...,
                vertices: _abc.Iterable[Global___ActivityZoneSettingsTrait.ActivityZone.ActivityZoneProperties.Coordinate] | None = ...,
                zoneId: _builtins.int = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["internalIndex", b"internalIndex", "name", b"name", "vertices", b"vertices", "zoneId", b"zoneId"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        ZONEINDEX_FIELD_NUMBER: _builtins.int
        ZONEPROPERTIES_FIELD_NUMBER: _builtins.int
        zoneIndex: _builtins.int
        @_builtins.property
        def zoneProperties(self) -> Global___ActivityZoneSettingsTrait.ActivityZone.ActivityZoneProperties: ...
        def __init__(
            self,
            *,
            zoneIndex: _builtins.int = ...,
            zoneProperties: Global___ActivityZoneSettingsTrait.ActivityZone.ActivityZoneProperties | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["zoneProperties", b"zoneProperties"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["zoneIndex", b"zoneIndex", "zoneProperties", b"zoneProperties"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ACTIVITYZONES_FIELD_NUMBER: _builtins.int
    UNKNOWN_FIELD_NUMBER: _builtins.int
    unknown: _builtins.int
    """0 = zones disabled, 1 = zones enabled?"""
    @_builtins.property
    def activityZones(self) -> _containers.RepeatedCompositeFieldContainer[Global___ActivityZoneSettingsTrait.ActivityZone]: ...
    def __init__(
        self,
        *,
        activityZones: _abc.Iterable[Global___ActivityZoneSettingsTrait.ActivityZone] | None = ...,
        unknown: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activityZones", b"activityZones", "unknown", b"unknown"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActivityZoneSettingsTrait: _TypeAlias = ActivityZoneSettingsTrait  # noqa: Y015

@_typing.final
class FaceTrackingSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FACETRACKINGENABLED_FIELD_NUMBER: _builtins.int
    UNKNOWN_FIELD_NUMBER: _builtins.int
    unknown: _builtins.int
    @_builtins.property
    def faceTrackingEnabled(self) -> _wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        faceTrackingEnabled: _wrappers_pb2.BoolValue | None = ...,
        unknown: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["faceTrackingEnabled", b"faceTrackingEnabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["faceTrackingEnabled", b"faceTrackingEnabled", "unknown", b"unknown"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FaceTrackingSettingsTrait: _TypeAlias = FaceTrackingSettingsTrait  # noqa: Y015

@_typing.final
class StreamingProtocolTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _StreamingProtocol:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StreamingProtocolEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StreamingProtocolTrait._StreamingProtocol.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PROTOCOL_UNSPECIFIED: StreamingProtocolTrait._StreamingProtocol.ValueType  # 0
        PROTOCOL_WEBRTC: StreamingProtocolTrait._StreamingProtocol.ValueType  # 1
        PROTOCOL_NEXUSTALK: StreamingProtocolTrait._StreamingProtocol.ValueType  # 2
        PROTOCOL_MPEGDASH: StreamingProtocolTrait._StreamingProtocol.ValueType  # 3
        PROTOCOL_RTSP: StreamingProtocolTrait._StreamingProtocol.ValueType  # 4
        PROTOCOL_HLS: StreamingProtocolTrait._StreamingProtocol.ValueType  # 5

    class StreamingProtocol(_StreamingProtocol, metaclass=_StreamingProtocolEnumTypeWrapper): ...
    PROTOCOL_UNSPECIFIED: StreamingProtocolTrait.StreamingProtocol.ValueType  # 0
    PROTOCOL_WEBRTC: StreamingProtocolTrait.StreamingProtocol.ValueType  # 1
    PROTOCOL_NEXUSTALK: StreamingProtocolTrait.StreamingProtocol.ValueType  # 2
    PROTOCOL_MPEGDASH: StreamingProtocolTrait.StreamingProtocol.ValueType  # 3
    PROTOCOL_RTSP: StreamingProtocolTrait.StreamingProtocol.ValueType  # 4
    PROTOCOL_HLS: StreamingProtocolTrait.StreamingProtocol.ValueType  # 5

    class _AudioCommunicationType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AudioCommunicationTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StreamingProtocolTrait._AudioCommunicationType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        AUDIO_TYPE_UNSPECIFIED: StreamingProtocolTrait._AudioCommunicationType.ValueType  # 0
        AUDIO_TYPE_NONE: StreamingProtocolTrait._AudioCommunicationType.ValueType  # 1
        AUDIO_TYPE_HALF_DUPLEX: StreamingProtocolTrait._AudioCommunicationType.ValueType  # 2
        AUDIO_TYPE_FULL_DUPLEX: StreamingProtocolTrait._AudioCommunicationType.ValueType  # 3

    class AudioCommunicationType(_AudioCommunicationType, metaclass=_AudioCommunicationTypeEnumTypeWrapper): ...
    AUDIO_TYPE_UNSPECIFIED: StreamingProtocolTrait.AudioCommunicationType.ValueType  # 0
    AUDIO_TYPE_NONE: StreamingProtocolTrait.AudioCommunicationType.ValueType  # 1
    AUDIO_TYPE_HALF_DUPLEX: StreamingProtocolTrait.AudioCommunicationType.ValueType  # 2
    AUDIO_TYPE_FULL_DUPLEX: StreamingProtocolTrait.AudioCommunicationType.ValueType  # 3

    SUPPORTEDPROTOCOLS_FIELD_NUMBER: _builtins.int
    AUDIOCOMMUNICATIONTYPE_FIELD_NUMBER: _builtins.int
    DIRECTHOST_FIELD_NUMBER: _builtins.int
    DASHURL_FIELD_NUMBER: _builtins.int
    HLSURL_FIELD_NUMBER: _builtins.int
    audioCommunicationType: Global___StreamingProtocolTrait.AudioCommunicationType.ValueType
    @_builtins.property
    def supportedProtocols(self) -> _containers.RepeatedScalarFieldContainer[Global___StreamingProtocolTrait.StreamingProtocol.ValueType]: ...
    @_builtins.property
    def directHost(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def dashUrl(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def hlsUrl(self) -> _wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        supportedProtocols: _abc.Iterable[Global___StreamingProtocolTrait.StreamingProtocol.ValueType] | None = ...,
        audioCommunicationType: Global___StreamingProtocolTrait.AudioCommunicationType.ValueType = ...,
        directHost: _wrappers_pb2.StringValue | None = ...,
        dashUrl: _wrappers_pb2.StringValue | None = ...,
        hlsUrl: _wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dashUrl", b"dashUrl", "directHost", b"directHost", "hlsUrl", b"hlsUrl"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audioCommunicationType", b"audioCommunicationType", "dashUrl", b"dashUrl", "directHost", b"directHost", "hlsUrl", b"hlsUrl", "supportedProtocols", b"supportedProtocols"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamingProtocolTrait: _TypeAlias = StreamingProtocolTrait  # noqa: Y015

@_typing.final
class LoadingImageTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAXIMUMAGEINSECONDS_FIELD_NUMBER: _builtins.int
    LIVEURL_FIELD_NUMBER: _builtins.int
    liveUrl: _builtins.str
    @_builtins.property
    def maximumAgeInSeconds(self) -> _wrappers_pb2.Int32Value: ...
    def __init__(
        self,
        *,
        maximumAgeInSeconds: _wrappers_pb2.Int32Value | None = ...,
        liveUrl: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["maximumAgeInSeconds", b"maximumAgeInSeconds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["liveUrl", b"liveUrl", "maximumAgeInSeconds", b"maximumAgeInSeconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoadingImageTrait: _TypeAlias = LoadingImageTrait  # noqa: Y015

@_typing.final
class ObservationTriggerCapabilitiesTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class VideoEventTypes(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MOTION_FIELD_NUMBER: _builtins.int
        PERSON_FIELD_NUMBER: _builtins.int
        FACE_FIELD_NUMBER: _builtins.int
        VEHICLE_FIELD_NUMBER: _builtins.int
        ANIMAL_FIELD_NUMBER: _builtins.int
        PACKAGE_FIELD_NUMBER: _builtins.int
        UNKNOWN7_FIELD_NUMBER: _builtins.int
        UNKNOWN8_FIELD_NUMBER: _builtins.int
        UNKNOWN9_FIELD_NUMBER: _builtins.int
        UNKNOWN10_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def motion(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def person(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def face(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def vehicle(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def animal(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def package(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown7(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown8(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown9(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown10(self) -> _wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            motion: _wrappers_pb2.BoolValue | None = ...,
            person: _wrappers_pb2.BoolValue | None = ...,
            face: _wrappers_pb2.BoolValue | None = ...,
            vehicle: _wrappers_pb2.BoolValue | None = ...,
            animal: _wrappers_pb2.BoolValue | None = ...,
            package: _wrappers_pb2.BoolValue | None = ...,
            unknown7: _wrappers_pb2.BoolValue | None = ...,
            unknown8: _wrappers_pb2.BoolValue | None = ...,
            unknown9: _wrappers_pb2.BoolValue | None = ...,
            unknown10: _wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["animal", b"animal", "face", b"face", "motion", b"motion", "package", b"package", "person", b"person", "unknown10", b"unknown10", "unknown7", b"unknown7", "unknown8", b"unknown8", "unknown9", b"unknown9", "vehicle", b"vehicle"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["animal", b"animal", "face", b"face", "motion", b"motion", "package", b"package", "person", b"person", "unknown10", b"unknown10", "unknown7", b"unknown7", "unknown8", b"unknown8", "unknown9", b"unknown9", "vehicle", b"vehicle"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AudioEventTypes(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PERSONTALKING_FIELD_NUMBER: _builtins.int
        DOGBARKING_FIELD_NUMBER: _builtins.int
        UNKNOWN3_FIELD_NUMBER: _builtins.int
        UNKNOWN4_FIELD_NUMBER: _builtins.int
        OTHERSOUNDS_FIELD_NUMBER: _builtins.int
        SMOKEANDCOSOUNDS_FIELD_NUMBER: _builtins.int
        UNKNOWN7_FIELD_NUMBER: _builtins.int
        UNKNOWN8_FIELD_NUMBER: _builtins.int
        UNKNOWN9_FIELD_NUMBER: _builtins.int
        UNKNOWN10_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def personTalking(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def dogBarking(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown3(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown4(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def otherSounds(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def smokeAndCoSounds(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown7(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown8(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown9(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def unknown10(self) -> _wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            personTalking: _wrappers_pb2.BoolValue | None = ...,
            dogBarking: _wrappers_pb2.BoolValue | None = ...,
            unknown3: _wrappers_pb2.BoolValue | None = ...,
            unknown4: _wrappers_pb2.BoolValue | None = ...,
            otherSounds: _wrappers_pb2.BoolValue | None = ...,
            smokeAndCoSounds: _wrappers_pb2.BoolValue | None = ...,
            unknown7: _wrappers_pb2.BoolValue | None = ...,
            unknown8: _wrappers_pb2.BoolValue | None = ...,
            unknown9: _wrappers_pb2.BoolValue | None = ...,
            unknown10: _wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["dogBarking", b"dogBarking", "otherSounds", b"otherSounds", "personTalking", b"personTalking", "smokeAndCoSounds", b"smokeAndCoSounds", "unknown10", b"unknown10", "unknown3", b"unknown3", "unknown4", b"unknown4", "unknown7", b"unknown7", "unknown8", b"unknown8", "unknown9", b"unknown9"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["dogBarking", b"dogBarking", "otherSounds", b"otherSounds", "personTalking", b"personTalking", "smokeAndCoSounds", b"smokeAndCoSounds", "unknown10", b"unknown10", "unknown3", b"unknown3", "unknown4", b"unknown4", "unknown7", b"unknown7", "unknown8", b"unknown8", "unknown9", b"unknown9"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VIDEOEVENTTYPES_FIELD_NUMBER: _builtins.int
    AUDIOEVENTTYPES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def videoEventTypes(self) -> Global___ObservationTriggerCapabilitiesTrait.VideoEventTypes: ...
    @_builtins.property
    def audioEventTypes(self) -> Global___ObservationTriggerCapabilitiesTrait.AudioEventTypes: ...
    def __init__(
        self,
        *,
        videoEventTypes: Global___ObservationTriggerCapabilitiesTrait.VideoEventTypes | None = ...,
        audioEventTypes: Global___ObservationTriggerCapabilitiesTrait.AudioEventTypes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audioEventTypes", b"audioEventTypes", "videoEventTypes", b"videoEventTypes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audioEventTypes", b"audioEventTypes", "videoEventTypes", b"videoEventTypes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObservationTriggerCapabilitiesTrait: _TypeAlias = ObservationTriggerCapabilitiesTrait  # noqa: Y015

@_typing.final
class MediaRequestTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNKNOWN1_FIELD_NUMBER: _builtins.int
    unknown1: _builtins.int
    def __init__(
        self,
        *,
        unknown1: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unknown1", b"unknown1"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MediaRequestTrait: _TypeAlias = MediaRequestTrait  # noqa: Y015

@_typing.final
class UploadLiveImageTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class UploadLiveImageRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class UploadLiveImageResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _Status:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[UploadLiveImageTrait.UploadLiveImageResponse._Status.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            STATUS_UNSPECIFIED: UploadLiveImageTrait.UploadLiveImageResponse._Status.ValueType  # 0
            STATUS_SUCCESSFUL: UploadLiveImageTrait.UploadLiveImageResponse._Status.ValueType  # 1
            STATUS_UNSUCCESSFUL: UploadLiveImageTrait.UploadLiveImageResponse._Status.ValueType  # 2

        class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
        STATUS_UNSPECIFIED: UploadLiveImageTrait.UploadLiveImageResponse.Status.ValueType  # 0
        STATUS_SUCCESSFUL: UploadLiveImageTrait.UploadLiveImageResponse.Status.ValueType  # 1
        STATUS_UNSUCCESSFUL: UploadLiveImageTrait.UploadLiveImageResponse.Status.ValueType  # 2

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___UploadLiveImageTrait.UploadLiveImageResponse.Status.ValueType
        def __init__(
            self,
            *,
            status: Global___UploadLiveImageTrait.UploadLiveImageResponse.Status.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    LIVEIMAGEURL_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    liveImageUrl: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        liveImageUrl: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["liveImageUrl", b"liveImageUrl", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UploadLiveImageTrait: _TypeAlias = UploadLiveImageTrait  # noqa: Y015

@_typing.final
class ObservationTriggerSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class EventTrigger(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ENABLED_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def enabled(self) -> _wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            enabled: _wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SoundTriggerSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PERSONTALKING_FIELD_NUMBER: _builtins.int
        DOGBARKING_FIELD_NUMBER: _builtins.int
        UNKNOWN3_FIELD_NUMBER: _builtins.int
        UNKNOWN4_FIELD_NUMBER: _builtins.int
        SMOKEALARMSOUNDS_FIELD_NUMBER: _builtins.int
        CARBONMONOXIDEALARMSOUNDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def personTalking(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
        @_builtins.property
        def dogBarking(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
        @_builtins.property
        def unknown3(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
        @_builtins.property
        def unknown4(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
        @_builtins.property
        def smokeAlarmSounds(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
        @_builtins.property
        def carbonMonoxideAlarmSounds(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
        def __init__(
            self,
            *,
            personTalking: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
            dogBarking: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
            unknown3: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
            unknown4: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
            smokeAlarmSounds: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
            carbonMonoxideAlarmSounds: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["carbonMonoxideAlarmSounds", b"carbonMonoxideAlarmSounds", "dogBarking", b"dogBarking", "personTalking", b"personTalking", "smokeAlarmSounds", b"smokeAlarmSounds", "unknown3", b"unknown3", "unknown4", b"unknown4"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["carbonMonoxideAlarmSounds", b"carbonMonoxideAlarmSounds", "dogBarking", b"dogBarking", "personTalking", b"personTalking", "smokeAlarmSounds", b"smokeAlarmSounds", "unknown3", b"unknown3", "unknown4", b"unknown4"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ZoneTriggerSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ZoneSettings(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            @_typing.final
            class TriggerTypes(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                MOTION_FIELD_NUMBER: _builtins.int
                PERSON_FIELD_NUMBER: _builtins.int
                FACE_FIELD_NUMBER: _builtins.int
                VEHICLE_FIELD_NUMBER: _builtins.int
                ANIMAL_FIELD_NUMBER: _builtins.int
                PACKAGE_FIELD_NUMBER: _builtins.int
                @_builtins.property
                def motion(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
                @_builtins.property
                def person(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
                @_builtins.property
                def face(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
                @_builtins.property
                def vehicle(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
                @_builtins.property
                def animal(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
                @_builtins.property
                def package(self) -> Global___ObservationTriggerSettingsTrait.EventTrigger: ...
                def __init__(
                    self,
                    *,
                    motion: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
                    person: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
                    face: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
                    vehicle: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
                    animal: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
                    package: Global___ObservationTriggerSettingsTrait.EventTrigger | None = ...,
                ) -> None: ...
                _HasFieldArgType: _TypeAlias = _typing.Literal["animal", b"animal", "face", b"face", "motion", b"motion", "package", b"package", "person", b"person", "vehicle", b"vehicle"]  # noqa: Y015
                def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["animal", b"animal", "face", b"face", "motion", b"motion", "package", b"package", "person", b"person", "vehicle", b"vehicle"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            ZONEID_FIELD_NUMBER: _builtins.int
            TRIGGERTYPES_FIELD_NUMBER: _builtins.int
            zoneId: _builtins.int
            @_builtins.property
            def triggerTypes(self) -> Global___ObservationTriggerSettingsTrait.ZoneTriggerSettings.ZoneSettings.TriggerTypes: ...
            def __init__(
                self,
                *,
                zoneId: _builtins.int = ...,
                triggerTypes: Global___ObservationTriggerSettingsTrait.ZoneTriggerSettings.ZoneSettings.TriggerTypes | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["triggerTypes", b"triggerTypes"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["triggerTypes", b"triggerTypes", "zoneId", b"zoneId"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        ZONEINDEX_FIELD_NUMBER: _builtins.int
        ZONESETTINGS_FIELD_NUMBER: _builtins.int
        zoneIndex: _builtins.int
        @_builtins.property
        def zoneSettings(self) -> Global___ObservationTriggerSettingsTrait.ZoneTriggerSettings.ZoneSettings: ...
        def __init__(
            self,
            *,
            zoneIndex: _builtins.int = ...,
            zoneSettings: Global___ObservationTriggerSettingsTrait.ZoneTriggerSettings.ZoneSettings | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["zoneSettings", b"zoneSettings"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["zoneIndex", b"zoneIndex", "zoneSettings", b"zoneSettings"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AITriggerSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class AISeenSettings(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            GARAGEDOOR_FIELD_NUMBER: _builtins.int
            garageDoor: _builtins.bool
            def __init__(
                self,
                *,
                garageDoor: _builtins.bool = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["garageDoor", b"garageDoor"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        SEENSETTINGS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def seenSettings(self) -> Global___ObservationTriggerSettingsTrait.AITriggerSettings.AISeenSettings: ...
        def __init__(
            self,
            *,
            seenSettings: Global___ObservationTriggerSettingsTrait.AITriggerSettings.AISeenSettings | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["seenSettings", b"seenSettings"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["seenSettings", b"seenSettings"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    GLOBALTRIGGERSETTINGS_FIELD_NUMBER: _builtins.int
    ZONETRIGGERSETTINGS_FIELD_NUMBER: _builtins.int
    GLOBALAITRIGGERSETTINGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def globalTriggerSettings(self) -> Global___ObservationTriggerSettingsTrait.SoundTriggerSettings: ...
    @_builtins.property
    def zoneTriggerSettings(self) -> _containers.RepeatedCompositeFieldContainer[Global___ObservationTriggerSettingsTrait.ZoneTriggerSettings]: ...
    @_builtins.property
    def globalAITriggerSettings(self) -> Global___ObservationTriggerSettingsTrait.AITriggerSettings: ...
    def __init__(
        self,
        *,
        globalTriggerSettings: Global___ObservationTriggerSettingsTrait.SoundTriggerSettings | None = ...,
        zoneTriggerSettings: _abc.Iterable[Global___ObservationTriggerSettingsTrait.ZoneTriggerSettings] | None = ...,
        globalAITriggerSettings: Global___ObservationTriggerSettingsTrait.AITriggerSettings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["globalAITriggerSettings", b"globalAITriggerSettings", "globalTriggerSettings", b"globalTriggerSettings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["globalAITriggerSettings", b"globalAITriggerSettings", "globalTriggerSettings", b"globalTriggerSettings", "zoneTriggerSettings", b"zoneTriggerSettings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObservationTriggerSettingsTrait: _TypeAlias = ObservationTriggerSettingsTrait  # noqa: Y015

@_typing.final
class RecordingMediaSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEOHISTORY_FIELD_NUMBER: _builtins.int
    AUDIOHISTORYENABLED_FIELD_NUMBER: _builtins.int
    UNKNOWN3_FIELD_NUMBER: _builtins.int
    videoHistory: Global___VideoHistorySetting.ValueType
    audioHistoryEnabled: _builtins.bool
    unknown3: _builtins.int
    def __init__(
        self,
        *,
        videoHistory: Global___VideoHistorySetting.ValueType = ...,
        audioHistoryEnabled: _builtins.bool = ...,
        unknown3: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audioHistoryEnabled", b"audioHistoryEnabled", "unknown3", b"unknown3", "videoHistory", b"videoHistory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RecordingMediaSettingsTrait: _TypeAlias = RecordingMediaSettingsTrait  # noqa: Y015

@_typing.final
class AspectRatioTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WIDTHRELATIVE_FIELD_NUMBER: _builtins.int
    HEIGHTRELATIVE_FIELD_NUMBER: _builtins.int
    widthRelative: _builtins.int
    heightRelative: _builtins.int
    def __init__(
        self,
        *,
        widthRelative: _builtins.int = ...,
        heightRelative: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["heightRelative", b"heightRelative", "widthRelative", b"widthRelative"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AspectRatioTrait: _TypeAlias = AspectRatioTrait  # noqa: Y015

@_typing.final
class QuietTimeSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    QUIETTIMEENDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def quietTimeEnds(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        quietTimeEnds: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["quietTimeEnds", b"quietTimeEnds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["quietTimeEnds", b"quietTimeEnds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QuietTimeSettingsTrait: _TypeAlias = QuietTimeSettingsTrait  # noqa: Y015

@_typing.final
class EventSessionTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENTACTIVE_FIELD_NUMBER: _builtins.int
    eventActive: _builtins.bool
    def __init__(
        self,
        *,
        eventActive: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eventActive", b"eventActive"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventSessionTrait: _TypeAlias = EventSessionTrait  # noqa: Y015

@_typing.final
class RecordingMediaCapabilitiesTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUPPORTEDCAPABILITIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def supportedCapabilities(self) -> _containers.RepeatedScalarFieldContainer[Global___VideoHistorySetting.ValueType]: ...
    def __init__(
        self,
        *,
        supportedCapabilities: _abc.Iterable[Global___VideoHistorySetting.ValueType] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["supportedCapabilities", b"supportedCapabilities"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RecordingMediaCapabilitiesTrait: _TypeAlias = RecordingMediaCapabilitiesTrait  # noqa: Y015

@_typing.final
class EffectiveHistoryLengthTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HISTORYDURATIONSECONDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def historyDurationSeconds(self) -> _wrappers_pb2.UInt32Value: ...
    def __init__(
        self,
        *,
        historyDurationSeconds: _wrappers_pb2.UInt32Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["historyDurationSeconds", b"historyDurationSeconds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["historyDurationSeconds", b"historyDurationSeconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EffectiveHistoryLengthTrait: _TypeAlias = EffectiveHistoryLengthTrait  # noqa: Y015

@_typing.final
class CameraMigrationStatusTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MigrationState(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _WhereMigrated:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _WhereMigratedEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CameraMigrationStatusTrait.MigrationState._WhereMigrated.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            NOT_MIGRATED: CameraMigrationStatusTrait.MigrationState._WhereMigrated.ValueType  # 0
            MIGRATED_TO_GOOGLE_HOME: CameraMigrationStatusTrait.MigrationState._WhereMigrated.ValueType  # 1
            MIGRATED_TO_NEST: CameraMigrationStatusTrait.MigrationState._WhereMigrated.ValueType  # 2

        class WhereMigrated(_WhereMigrated, metaclass=_WhereMigratedEnumTypeWrapper): ...
        NOT_MIGRATED: CameraMigrationStatusTrait.MigrationState.WhereMigrated.ValueType  # 0
        MIGRATED_TO_GOOGLE_HOME: CameraMigrationStatusTrait.MigrationState.WhereMigrated.ValueType  # 1
        MIGRATED_TO_NEST: CameraMigrationStatusTrait.MigrationState.WhereMigrated.ValueType  # 2

        class _MigrationProgress:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _MigrationProgressEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CameraMigrationStatusTrait.MigrationState._MigrationProgress.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            PROGRESS_NONE: CameraMigrationStatusTrait.MigrationState._MigrationProgress.ValueType  # 0
            PROGRESS_STARTING: CameraMigrationStatusTrait.MigrationState._MigrationProgress.ValueType  # 1
            PROGRESS_INSTALLING: CameraMigrationStatusTrait.MigrationState._MigrationProgress.ValueType  # 2
            PROGRESS_COMPLETE: CameraMigrationStatusTrait.MigrationState._MigrationProgress.ValueType  # 3
            PROGRESS_MAYBE_ERROR: CameraMigrationStatusTrait.MigrationState._MigrationProgress.ValueType  # 4
            PROGRESS_FINALISING: CameraMigrationStatusTrait.MigrationState._MigrationProgress.ValueType  # 5

        class MigrationProgress(_MigrationProgress, metaclass=_MigrationProgressEnumTypeWrapper): ...
        PROGRESS_NONE: CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType  # 0
        PROGRESS_STARTING: CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType  # 1
        PROGRESS_INSTALLING: CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType  # 2
        PROGRESS_COMPLETE: CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType  # 3
        PROGRESS_MAYBE_ERROR: CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType  # 4
        PROGRESS_FINALISING: CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType  # 5

        WHERE_FIELD_NUMBER: _builtins.int
        PROGRESS_FIELD_NUMBER: _builtins.int
        where: Global___CameraMigrationStatusTrait.MigrationState.WhereMigrated.ValueType
        progress: Global___CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType
        def __init__(
            self,
            *,
            where: Global___CameraMigrationStatusTrait.MigrationState.WhereMigrated.ValueType = ...,
            progress: Global___CameraMigrationStatusTrait.MigrationState.MigrationProgress.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["progress", b"progress", "where", b"where"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___CameraMigrationStatusTrait.MigrationState: ...
    def __init__(
        self,
        *,
        state: Global___CameraMigrationStatusTrait.MigrationState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CameraMigrationStatusTrait: _TypeAlias = CameraMigrationStatusTrait  # noqa: Y015

@_typing.final
class DoorStateTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DoorState(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _DoorOpenCloseState:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _DoorOpenCloseStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorStateTrait.DoorState._DoorOpenCloseState.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            STATE_UNSPECIFIED: DoorStateTrait.DoorState._DoorOpenCloseState.ValueType  # 0
            STATE_MAYBE_CLOSING: DoorStateTrait.DoorState._DoorOpenCloseState.ValueType  # 1
            STATE_CLOSED: DoorStateTrait.DoorState._DoorOpenCloseState.ValueType  # 2
            STATE_MAYBE_OPENING: DoorStateTrait.DoorState._DoorOpenCloseState.ValueType  # 3
            STATE_OPEN: DoorStateTrait.DoorState._DoorOpenCloseState.ValueType  # 4

        class DoorOpenCloseState(_DoorOpenCloseState, metaclass=_DoorOpenCloseStateEnumTypeWrapper): ...
        STATE_UNSPECIFIED: DoorStateTrait.DoorState.DoorOpenCloseState.ValueType  # 0
        STATE_MAYBE_CLOSING: DoorStateTrait.DoorState.DoorOpenCloseState.ValueType  # 1
        STATE_CLOSED: DoorStateTrait.DoorState.DoorOpenCloseState.ValueType  # 2
        STATE_MAYBE_OPENING: DoorStateTrait.DoorState.DoorOpenCloseState.ValueType  # 3
        STATE_OPEN: DoorStateTrait.DoorState.DoorOpenCloseState.ValueType  # 4

        @_typing.final
        class OpenCloseState(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            DOORSTATE_FIELD_NUMBER: _builtins.int
            doorState: Global___DoorStateTrait.DoorState.DoorOpenCloseState.ValueType
            def __init__(
                self,
                *,
                doorState: Global___DoorStateTrait.DoorState.DoorOpenCloseState.ValueType = ...,
            ) -> None: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["doorState", b"doorState"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        OPENCLOSE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def openClose(self) -> Global___DoorStateTrait.DoorState.OpenCloseState: ...
        def __init__(
            self,
            *,
            openClose: Global___DoorStateTrait.DoorState.OpenCloseState | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["openClose", b"openClose"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["openClose", b"openClose"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___DoorStateTrait.DoorState: ...
    def __init__(
        self,
        *,
        state: Global___DoorStateTrait.DoorState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DoorStateTrait: _TypeAlias = DoorStateTrait  # noqa: Y015
