"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DoorbellIndoorChimeSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ChimeType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ChimeTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DoorbellIndoorChimeSettingsTrait._ChimeType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CHIME_TYPE_UNSPECIFIED: DoorbellIndoorChimeSettingsTrait._ChimeType.ValueType  # 0
        CHIME_TYPE_MECHANICAL: DoorbellIndoorChimeSettingsTrait._ChimeType.ValueType  # 1
        CHIME_TYPE_ELECTRONIC: DoorbellIndoorChimeSettingsTrait._ChimeType.ValueType  # 2

    class ChimeType(_ChimeType, metaclass=_ChimeTypeEnumTypeWrapper): ...
    CHIME_TYPE_UNSPECIFIED: DoorbellIndoorChimeSettingsTrait.ChimeType.ValueType  # 0
    CHIME_TYPE_MECHANICAL: DoorbellIndoorChimeSettingsTrait.ChimeType.ValueType  # 1
    CHIME_TYPE_ELECTRONIC: DoorbellIndoorChimeSettingsTrait.ChimeType.ValueType  # 2

    CHIMETYPE_FIELD_NUMBER: _builtins.int
    CHIMEDURATION_FIELD_NUMBER: _builtins.int
    CHIMEENABLED_FIELD_NUMBER: _builtins.int
    chimeType: Global___DoorbellIndoorChimeSettingsTrait.ChimeType.ValueType
    chimeEnabled: _builtins.bool
    @_builtins.property
    def chimeDuration(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        chimeType: Global___DoorbellIndoorChimeSettingsTrait.ChimeType.ValueType = ...,
        chimeDuration: _duration_pb2.Duration | None = ...,
        chimeEnabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["chimeDuration", b"chimeDuration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chimeDuration", b"chimeDuration", "chimeEnabled", b"chimeEnabled", "chimeType", b"chimeType"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DoorbellIndoorChimeSettingsTrait: _TypeAlias = DoorbellIndoorChimeSettingsTrait  # noqa: Y015
