"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ....nest.trait import selftest_pb2 as _selftest_pb2
from ....weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LegacyStructureSelfTestTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SelfTestType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SelfTestTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LegacyStructureSelfTestTrait._SelfTestType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SELF_TEST_TYPE_UNSPECIFIED: LegacyStructureSelfTestTrait._SelfTestType.ValueType  # 0
        SELF_TEST_TYPE_AST: LegacyStructureSelfTestTrait._SelfTestType.ValueType  # 1
        SELF_TEST_TYPE_MST: LegacyStructureSelfTestTrait._SelfTestType.ValueType  # 2

    class SelfTestType(_SelfTestType, metaclass=_SelfTestTypeEnumTypeWrapper): ...
    SELF_TEST_TYPE_UNSPECIFIED: LegacyStructureSelfTestTrait.SelfTestType.ValueType  # 0
    SELF_TEST_TYPE_AST: LegacyStructureSelfTestTrait.SelfTestType.ValueType  # 1
    SELF_TEST_TYPE_MST: LegacyStructureSelfTestTrait.SelfTestType.ValueType  # 2

    class _StartSelfTestStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StartSelfTestStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LegacyStructureSelfTestTrait._StartSelfTestStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        START_SELF_TEST_STATUS_UNSPECIFIED: LegacyStructureSelfTestTrait._StartSelfTestStatus.ValueType  # 0
        START_SELF_TEST_STATUS_OK: LegacyStructureSelfTestTrait._StartSelfTestStatus.ValueType  # 1
        START_SELF_TEST_STATUS_FAILED: LegacyStructureSelfTestTrait._StartSelfTestStatus.ValueType  # 2

    class StartSelfTestStatus(_StartSelfTestStatus, metaclass=_StartSelfTestStatusEnumTypeWrapper): ...
    START_SELF_TEST_STATUS_UNSPECIFIED: LegacyStructureSelfTestTrait.StartSelfTestStatus.ValueType  # 0
    START_SELF_TEST_STATUS_OK: LegacyStructureSelfTestTrait.StartSelfTestStatus.ValueType  # 1
    START_SELF_TEST_STATUS_FAILED: LegacyStructureSelfTestTrait.StartSelfTestStatus.ValueType  # 2

    class _EndSelfTestStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EndSelfTestStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LegacyStructureSelfTestTrait._EndSelfTestStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        END_SELF_TEST_STATUS_UNSPECIFIED: LegacyStructureSelfTestTrait._EndSelfTestStatus.ValueType  # 0
        END_SELF_TEST_STATUS_OK: LegacyStructureSelfTestTrait._EndSelfTestStatus.ValueType  # 1
        END_SELF_TEST_STATUS_FAILED: LegacyStructureSelfTestTrait._EndSelfTestStatus.ValueType  # 2

    class EndSelfTestStatus(_EndSelfTestStatus, metaclass=_EndSelfTestStatusEnumTypeWrapper): ...
    END_SELF_TEST_STATUS_UNSPECIFIED: LegacyStructureSelfTestTrait.EndSelfTestStatus.ValueType  # 0
    END_SELF_TEST_STATUS_OK: LegacyStructureSelfTestTrait.EndSelfTestStatus.ValueType  # 1
    END_SELF_TEST_STATUS_FAILED: LegacyStructureSelfTestTrait.EndSelfTestStatus.ValueType  # 2

    @_typing.final
    class StartSelfTestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        TESTID_FIELD_NUMBER: _builtins.int
        type: Global___LegacyStructureSelfTestTrait.SelfTestType.ValueType
        @_builtins.property
        def testId(self) -> _selftest_pb2.SelfTestRunnerTrait.TestId: ...
        def __init__(
            self,
            *,
            type: Global___LegacyStructureSelfTestTrait.SelfTestType.ValueType = ...,
            testId: _selftest_pb2.SelfTestRunnerTrait.TestId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StartSelfTestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___LegacyStructureSelfTestTrait.StartSelfTestStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___LegacyStructureSelfTestTrait.StartSelfTestStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class EndSelfTestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        TESTID_FIELD_NUMBER: _builtins.int
        type: Global___LegacyStructureSelfTestTrait.SelfTestType.ValueType
        @_builtins.property
        def testId(self) -> _selftest_pb2.SelfTestRunnerTrait.TestId: ...
        def __init__(
            self,
            *,
            type: Global___LegacyStructureSelfTestTrait.SelfTestType.ValueType = ...,
            testId: _selftest_pb2.SelfTestRunnerTrait.TestId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class EndSelfTestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___LegacyStructureSelfTestTrait.EndSelfTestStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___LegacyStructureSelfTestTrait.EndSelfTestStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AutomatedSelfTestSkipEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class AutomatedSelfTestCompleteEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class ManualSelfTestCompleteEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    LASTMSTCANCELLED_FIELD_NUMBER: _builtins.int
    MSTINPROGRESS_FIELD_NUMBER: _builtins.int
    LASTMSTSTARTUTCSECS_FIELD_NUMBER: _builtins.int
    LASTMSTENDUTCSECS_FIELD_NUMBER: _builtins.int
    LASTMSTSUCCESSUTCSECS_FIELD_NUMBER: _builtins.int
    ASTINPROGRESS_FIELD_NUMBER: _builtins.int
    LASTASTSTARTUTCSECS_FIELD_NUMBER: _builtins.int
    LASTASTENDUTCSECS_FIELD_NUMBER: _builtins.int
    ASTREQUESTUTCSECS_FIELD_NUMBER: _builtins.int
    ASTSKIPUTCSECS_FIELD_NUMBER: _builtins.int
    ASTPARTICIPANTS_FIELD_NUMBER: _builtins.int
    lastMstCancelled: _builtins.bool
    mstInProgress: _builtins.bool
    astInProgress: _builtins.bool
    @_builtins.property
    def lastMstStartUtcSecs(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastMstEndUtcSecs(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastMstSuccessUtcSecs(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastAstStartUtcSecs(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastAstEndUtcSecs(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def astRequestUtcSecs(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def astSkipUtcSecs(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def astParticipants(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        lastMstCancelled: _builtins.bool = ...,
        mstInProgress: _builtins.bool = ...,
        lastMstStartUtcSecs: _timestamp_pb2.Timestamp | None = ...,
        lastMstEndUtcSecs: _timestamp_pb2.Timestamp | None = ...,
        lastMstSuccessUtcSecs: _timestamp_pb2.Timestamp | None = ...,
        astInProgress: _builtins.bool = ...,
        lastAstStartUtcSecs: _timestamp_pb2.Timestamp | None = ...,
        lastAstEndUtcSecs: _timestamp_pb2.Timestamp | None = ...,
        astRequestUtcSecs: _timestamp_pb2.Timestamp | None = ...,
        astSkipUtcSecs: _timestamp_pb2.Timestamp | None = ...,
        astParticipants: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["astRequestUtcSecs", b"astRequestUtcSecs", "astSkipUtcSecs", b"astSkipUtcSecs", "lastAstEndUtcSecs", b"lastAstEndUtcSecs", "lastAstStartUtcSecs", b"lastAstStartUtcSecs", "lastMstEndUtcSecs", b"lastMstEndUtcSecs", "lastMstStartUtcSecs", b"lastMstStartUtcSecs", "lastMstSuccessUtcSecs", b"lastMstSuccessUtcSecs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["astInProgress", b"astInProgress", "astParticipants", b"astParticipants", "astRequestUtcSecs", b"astRequestUtcSecs", "astSkipUtcSecs", b"astSkipUtcSecs", "lastAstEndUtcSecs", b"lastAstEndUtcSecs", "lastAstStartUtcSecs", b"lastAstStartUtcSecs", "lastMstCancelled", b"lastMstCancelled", "lastMstEndUtcSecs", b"lastMstEndUtcSecs", "lastMstStartUtcSecs", b"lastMstStartUtcSecs", "lastMstSuccessUtcSecs", b"lastMstSuccessUtcSecs", "mstInProgress", b"mstInProgress"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LegacyStructureSelfTestTrait: _TypeAlias = LegacyStructureSelfTestTrait  # noqa: Y015

@_typing.final
class SelfTestTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SelfTestType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SelfTestTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SelfTestTrait._SelfTestType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SELF_TEST_TYPE_UNSPECIFIED: SelfTestTrait._SelfTestType.ValueType  # 0
        SELF_TEST_TYPE_AST: SelfTestTrait._SelfTestType.ValueType  # 1
        SELF_TEST_TYPE_MST: SelfTestTrait._SelfTestType.ValueType  # 2

    class SelfTestType(_SelfTestType, metaclass=_SelfTestTypeEnumTypeWrapper): ...
    SELF_TEST_TYPE_UNSPECIFIED: SelfTestTrait.SelfTestType.ValueType  # 0
    SELF_TEST_TYPE_AST: SelfTestTrait.SelfTestType.ValueType  # 1
    SELF_TEST_TYPE_MST: SelfTestTrait.SelfTestType.ValueType  # 2

    class _StartSelfTestStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StartSelfTestStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SelfTestTrait._StartSelfTestStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        START_SELF_TEST_STATUS_UNSPECIFIED: SelfTestTrait._StartSelfTestStatus.ValueType  # 0
        START_SELF_TEST_STATUS_OK: SelfTestTrait._StartSelfTestStatus.ValueType  # 1
        START_SELF_TEST_STATUS_FAILED: SelfTestTrait._StartSelfTestStatus.ValueType  # 2

    class StartSelfTestStatus(_StartSelfTestStatus, metaclass=_StartSelfTestStatusEnumTypeWrapper): ...
    START_SELF_TEST_STATUS_UNSPECIFIED: SelfTestTrait.StartSelfTestStatus.ValueType  # 0
    START_SELF_TEST_STATUS_OK: SelfTestTrait.StartSelfTestStatus.ValueType  # 1
    START_SELF_TEST_STATUS_FAILED: SelfTestTrait.StartSelfTestStatus.ValueType  # 2

    class _EndSelfTestStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EndSelfTestStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SelfTestTrait._EndSelfTestStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        END_SELF_TEST_STATUS_UNSPECIFIED: SelfTestTrait._EndSelfTestStatus.ValueType  # 0
        END_SELF_TEST_STATUS_OK: SelfTestTrait._EndSelfTestStatus.ValueType  # 1
        END_SELF_TEST_STATUS_FAILED: SelfTestTrait._EndSelfTestStatus.ValueType  # 2

    class EndSelfTestStatus(_EndSelfTestStatus, metaclass=_EndSelfTestStatusEnumTypeWrapper): ...
    END_SELF_TEST_STATUS_UNSPECIFIED: SelfTestTrait.EndSelfTestStatus.ValueType  # 0
    END_SELF_TEST_STATUS_OK: SelfTestTrait.EndSelfTestStatus.ValueType  # 1
    END_SELF_TEST_STATUS_FAILED: SelfTestTrait.EndSelfTestStatus.ValueType  # 2

    class _MstTrigger:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MstTriggerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SelfTestTrait._MstTrigger.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MST_TRIGGER_UNSPECIFIED: SelfTestTrait._MstTrigger.ValueType  # 0
        MST_TRIGGER_BUTTON: SelfTestTrait._MstTrigger.ValueType  # 1
        MST_TRIGGER_REMOTE: SelfTestTrait._MstTrigger.ValueType  # 2
        MST_TRIGGER_APP: SelfTestTrait._MstTrigger.ValueType  # 3

    class MstTrigger(_MstTrigger, metaclass=_MstTriggerEnumTypeWrapper): ...
    MST_TRIGGER_UNSPECIFIED: SelfTestTrait.MstTrigger.ValueType  # 0
    MST_TRIGGER_BUTTON: SelfTestTrait.MstTrigger.ValueType  # 1
    MST_TRIGGER_REMOTE: SelfTestTrait.MstTrigger.ValueType  # 2
    MST_TRIGGER_APP: SelfTestTrait.MstTrigger.ValueType  # 3

    @_typing.final
    class StartSelfTestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        TESTID_FIELD_NUMBER: _builtins.int
        type: Global___SelfTestTrait.SelfTestType.ValueType
        @_builtins.property
        def testId(self) -> _selftest_pb2.SelfTestRunnerTrait.TestId: ...
        def __init__(
            self,
            *,
            type: Global___SelfTestTrait.SelfTestType.ValueType = ...,
            testId: _selftest_pb2.SelfTestRunnerTrait.TestId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StartSelfTestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___SelfTestTrait.StartSelfTestStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___SelfTestTrait.StartSelfTestStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class EndSelfTestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPE_FIELD_NUMBER: _builtins.int
        TESTID_FIELD_NUMBER: _builtins.int
        type: Global___SelfTestTrait.SelfTestType.ValueType
        @_builtins.property
        def testId(self) -> _selftest_pb2.SelfTestRunnerTrait.TestId: ...
        def __init__(
            self,
            *,
            type: Global___SelfTestTrait.SelfTestType.ValueType = ...,
            testId: _selftest_pb2.SelfTestRunnerTrait.TestId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class EndSelfTestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___SelfTestTrait.EndSelfTestStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___SelfTestTrait.EndSelfTestStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class MstTransitionEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TRIGGER_FIELD_NUMBER: _builtins.int
        NEWSTATE_FIELD_NUMBER: _builtins.int
        OLDSTATE_FIELD_NUMBER: _builtins.int
        trigger: Global___SelfTestTrait.MstTrigger.ValueType
        newState: _builtins.int
        oldState: _builtins.int
        def __init__(
            self,
            *,
            trigger: Global___SelfTestTrait.MstTrigger.ValueType = ...,
            newState: _builtins.int = ...,
            oldState: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["newState", b"newState", "oldState", b"oldState", "trigger", b"trigger"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AstTransitionEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ORCHESTRATOR_FIELD_NUMBER: _builtins.int
        NEWSTATE_FIELD_NUMBER: _builtins.int
        OLDSTATE_FIELD_NUMBER: _builtins.int
        orchestrator: _builtins.bool
        newState: _builtins.int
        oldState: _builtins.int
        def __init__(
            self,
            *,
            orchestrator: _builtins.bool = ...,
            newState: _builtins.int = ...,
            oldState: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["newState", b"newState", "oldState", b"oldState", "orchestrator", b"orchestrator"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    LASTMSTSTART_FIELD_NUMBER: _builtins.int
    LASTMSTEND_FIELD_NUMBER: _builtins.int
    LASTMSTCANCELLED_FIELD_NUMBER: _builtins.int
    LASTASTSTART_FIELD_NUMBER: _builtins.int
    LASTASTEND_FIELD_NUMBER: _builtins.int
    lastMstCancelled: _builtins.bool
    @_builtins.property
    def lastMstStart(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastMstEnd(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastAstStart(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def lastAstEnd(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        lastMstStart: _timestamp_pb2.Timestamp | None = ...,
        lastMstEnd: _timestamp_pb2.Timestamp | None = ...,
        lastMstCancelled: _builtins.bool = ...,
        lastAstStart: _timestamp_pb2.Timestamp | None = ...,
        lastAstEnd: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lastAstEnd", b"lastAstEnd", "lastAstStart", b"lastAstStart", "lastMstEnd", b"lastMstEnd", "lastMstStart", b"lastMstStart"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lastAstEnd", b"lastAstEnd", "lastAstStart", b"lastAstStart", "lastMstCancelled", b"lastMstCancelled", "lastMstEnd", b"lastMstEnd", "lastMstStart", b"lastMstStart"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SelfTestTrait: _TypeAlias = SelfTestTrait  # noqa: Y015

@_typing.final
class AudioTestTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _AudioTestSource:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AudioTestSourceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AudioTestTrait._AudioTestSource.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        AUDIO_TEST_SOURCE_UNSPECIFIED: AudioTestTrait._AudioTestSource.ValueType  # 0
        AUDIO_TEST_SOURCE_AUTOMATIC: AudioTestTrait._AudioTestSource.ValueType  # 1
        AUDIO_TEST_SOURCE_MANUAL: AudioTestTrait._AudioTestSource.ValueType  # 2

    class AudioTestSource(_AudioTestSource, metaclass=_AudioTestSourceEnumTypeWrapper): ...
    AUDIO_TEST_SOURCE_UNSPECIFIED: AudioTestTrait.AudioTestSource.ValueType  # 0
    AUDIO_TEST_SOURCE_AUTOMATIC: AudioTestTrait.AudioTestSource.ValueType  # 1
    AUDIO_TEST_SOURCE_MANUAL: AudioTestTrait.AudioTestSource.ValueType  # 2

    class _AudioFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AudioFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AudioTestTrait._AudioFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        AUDIO_FAULT_TYPE_UNSPECIFIED: AudioTestTrait._AudioFaultType.ValueType  # 0
        AUDIO_FAULT_TYPE_INCONCLUSIVE_OTHER: AudioTestTrait._AudioFaultType.ValueType  # 1
        AUDIO_FAULT_TYPE_INCONCLUSIVE_AMBIENT_NOISE: AudioTestTrait._AudioFaultType.ValueType  # 2
        AUDIO_FAULT_TYPE_INCONCLUSIVE_ASYNC_INTER: AudioTestTrait._AudioFaultType.ValueType  # 4
        AUDIO_FAULT_TYPE_INCONCLUSIVE_DID_NOT_RUN: AudioTestTrait._AudioFaultType.ValueType  # 8
        AUDIO_FAULT_TYPE_INCONCLUSIVE_DROPPED_BUFFER: AudioTestTrait._AudioFaultType.ValueType  # 16

    class AudioFaultType(_AudioFaultType, metaclass=_AudioFaultTypeEnumTypeWrapper): ...
    AUDIO_FAULT_TYPE_UNSPECIFIED: AudioTestTrait.AudioFaultType.ValueType  # 0
    AUDIO_FAULT_TYPE_INCONCLUSIVE_OTHER: AudioTestTrait.AudioFaultType.ValueType  # 1
    AUDIO_FAULT_TYPE_INCONCLUSIVE_AMBIENT_NOISE: AudioTestTrait.AudioFaultType.ValueType  # 2
    AUDIO_FAULT_TYPE_INCONCLUSIVE_ASYNC_INTER: AudioTestTrait.AudioFaultType.ValueType  # 4
    AUDIO_FAULT_TYPE_INCONCLUSIVE_DID_NOT_RUN: AudioTestTrait.AudioFaultType.ValueType  # 8
    AUDIO_FAULT_TYPE_INCONCLUSIVE_DROPPED_BUFFER: AudioTestTrait.AudioFaultType.ValueType  # 16

    @_typing.final
    class AudioTestResult(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SOURCE_FIELD_NUMBER: _builtins.int
        TESTPASSED_FIELD_NUMBER: _builtins.int
        TYPES_FIELD_NUMBER: _builtins.int
        source: Global___AudioTestTrait.AudioTestSource.ValueType
        testPassed: _builtins.bool
        @_builtins.property
        def types(self) -> _containers.RepeatedScalarFieldContainer[Global___AudioTestTrait.AudioFaultType.ValueType]: ...
        def __init__(
            self,
            *,
            source: Global___AudioTestTrait.AudioTestSource.ValueType = ...,
            testPassed: _builtins.bool = ...,
            types: _abc.Iterable[Global___AudioTestTrait.AudioFaultType.ValueType] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["source", b"source", "testPassed", b"testPassed", "types", b"types"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AudioTestStartEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SOURCE_FIELD_NUMBER: _builtins.int
        source: Global___AudioTestTrait.AudioTestSource.ValueType
        def __init__(
            self,
            *,
            source: Global___AudioTestTrait.AudioTestSource.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["source", b"source"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AudioTestEndEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SPEAKERRESULT_FIELD_NUMBER: _builtins.int
        BUZZERRESULT_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def speakerResult(self) -> Global___AudioTestTrait.AudioTestResult: ...
        @_builtins.property
        def buzzerResult(self) -> Global___AudioTestTrait.AudioTestResult: ...
        def __init__(
            self,
            *,
            speakerResult: Global___AudioTestTrait.AudioTestResult | None = ...,
            buzzerResult: Global___AudioTestTrait.AudioTestResult | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["buzzerResult", b"buzzerResult", "speakerResult", b"speakerResult"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["buzzerResult", b"buzzerResult", "speakerResult", b"speakerResult"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SPEAKERRESULT_FIELD_NUMBER: _builtins.int
    BUZZERRESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def speakerResult(self) -> Global___AudioTestTrait.AudioTestResult: ...
    @_builtins.property
    def buzzerResult(self) -> Global___AudioTestTrait.AudioTestResult: ...
    def __init__(
        self,
        *,
        speakerResult: Global___AudioTestTrait.AudioTestResult | None = ...,
        buzzerResult: Global___AudioTestTrait.AudioTestResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["buzzerResult", b"buzzerResult", "speakerResult", b"speakerResult"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["buzzerResult", b"buzzerResult", "speakerResult", b"speakerResult"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AudioTestTrait: _TypeAlias = AudioTestTrait  # noqa: Y015

@_typing.final
class ReadyActionTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ReadyActionState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ReadyActionStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ReadyActionTrait._ReadyActionState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        READY_ACTION_STATE_UNSPECIFIED: ReadyActionTrait._ReadyActionState.ValueType  # 0
        READY_ACTION_STATE_IDLE: ReadyActionTrait._ReadyActionState.ValueType  # 1
        READY_ACTION_STATE_START_UX: ReadyActionTrait._ReadyActionState.ValueType  # 2
        READY_ACTION_STATE_PAIRING_UX: ReadyActionTrait._ReadyActionState.ValueType  # 3

    class ReadyActionState(_ReadyActionState, metaclass=_ReadyActionStateEnumTypeWrapper): ...
    READY_ACTION_STATE_UNSPECIFIED: ReadyActionTrait.ReadyActionState.ValueType  # 0
    READY_ACTION_STATE_IDLE: ReadyActionTrait.ReadyActionState.ValueType  # 1
    READY_ACTION_STATE_START_UX: ReadyActionTrait.ReadyActionState.ValueType  # 2
    READY_ACTION_STATE_PAIRING_UX: ReadyActionTrait.ReadyActionState.ValueType  # 3

    class _ReadyStateChangeReason:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ReadyStateChangeReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ReadyActionTrait._ReadyStateChangeReason.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        READY_STATE_CHANGE_REASON_UNSPECIFIED: ReadyActionTrait._ReadyStateChangeReason.ValueType  # 0
        READY_STATE_CHANGE_REASON_TIMEOUT: ReadyActionTrait._ReadyStateChangeReason.ValueType  # 1
        READY_STATE_CHANGE_REASON_BUTTON_PRESS: ReadyActionTrait._ReadyStateChangeReason.ValueType  # 2
        READY_STATE_CHANGE_REASON_BLE_TRIGGER: ReadyActionTrait._ReadyStateChangeReason.ValueType  # 3

    class ReadyStateChangeReason(_ReadyStateChangeReason, metaclass=_ReadyStateChangeReasonEnumTypeWrapper): ...
    READY_STATE_CHANGE_REASON_UNSPECIFIED: ReadyActionTrait.ReadyStateChangeReason.ValueType  # 0
    READY_STATE_CHANGE_REASON_TIMEOUT: ReadyActionTrait.ReadyStateChangeReason.ValueType  # 1
    READY_STATE_CHANGE_REASON_BUTTON_PRESS: ReadyActionTrait.ReadyStateChangeReason.ValueType  # 2
    READY_STATE_CHANGE_REASON_BLE_TRIGGER: ReadyActionTrait.ReadyStateChangeReason.ValueType  # 3

    @_typing.final
    class ReadyActionStateChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NEWREADYACTIONSTATE_FIELD_NUMBER: _builtins.int
        PREVIOUSREADYACTIONSTATE_FIELD_NUMBER: _builtins.int
        CHANGEREASON_FIELD_NUMBER: _builtins.int
        newReadyActionState: Global___ReadyActionTrait.ReadyActionState.ValueType
        previousReadyActionState: Global___ReadyActionTrait.ReadyActionState.ValueType
        changeReason: Global___ReadyActionTrait.ReadyStateChangeReason.ValueType
        def __init__(
            self,
            *,
            newReadyActionState: Global___ReadyActionTrait.ReadyActionState.ValueType = ...,
            previousReadyActionState: Global___ReadyActionTrait.ReadyActionState.ValueType = ...,
            changeReason: Global___ReadyActionTrait.ReadyStateChangeReason.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["changeReason", b"changeReason", "newReadyActionState", b"newReadyActionState", "previousReadyActionState", b"previousReadyActionState"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___ReadyActionTrait: _TypeAlias = ReadyActionTrait  # noqa: Y015

@_typing.final
class TrapActionTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _TrapStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TrapStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TrapActionTrait._TrapStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TRAP_STATUS_UNSPECIFIED: TrapActionTrait._TrapStatus.ValueType  # 0
        TRAP_STATUS_NONE: TrapActionTrait._TrapStatus.ValueType  # 1
        TRAP_STATUS_LAST_GASP_BEGIN: TrapActionTrait._TrapStatus.ValueType  # 2
        TRAP_STATUS_SAFETY_MCU: TrapActionTrait._TrapStatus.ValueType  # 3

    class TrapStatus(_TrapStatus, metaclass=_TrapStatusEnumTypeWrapper): ...
    TRAP_STATUS_UNSPECIFIED: TrapActionTrait.TrapStatus.ValueType  # 0
    TRAP_STATUS_NONE: TrapActionTrait.TrapStatus.ValueType  # 1
    TRAP_STATUS_LAST_GASP_BEGIN: TrapActionTrait.TrapStatus.ValueType  # 2
    TRAP_STATUS_SAFETY_MCU: TrapActionTrait.TrapStatus.ValueType  # 3

    @_typing.final
    class TrapStatusUpdateEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NEWTRAPSTATUS_FIELD_NUMBER: _builtins.int
        PREVIOUSTRAPSTATUS_FIELD_NUMBER: _builtins.int
        newTrapStatus: Global___TrapActionTrait.TrapStatus.ValueType
        previousTrapStatus: Global___TrapActionTrait.TrapStatus.ValueType
        def __init__(
            self,
            *,
            newTrapStatus: Global___TrapActionTrait.TrapStatus.ValueType = ...,
            previousTrapStatus: Global___TrapActionTrait.TrapStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["newTrapStatus", b"newTrapStatus", "previousTrapStatus", b"previousTrapStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SafetyMCUFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___TrapActionTrait: _TypeAlias = TrapActionTrait  # noqa: Y015

@_typing.final
class NightTimePromiseTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _NtpState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _NtpStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[NightTimePromiseTrait._NtpState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NTP_STATE_UNSPECIFIED: NightTimePromiseTrait._NtpState.ValueType  # 0
        NTP_STATE_ALL_CLEAR_NTP_ENABLED: NightTimePromiseTrait._NtpState.ValueType  # 1
        NTP_STATE_ALL_CLEAR_NTP_DISABLED: NightTimePromiseTrait._NtpState.ValueType  # 2
        NTP_STATE_WARNINGS_DISPLAYED: NightTimePromiseTrait._NtpState.ValueType  # 3
        NTP_STATE_WARNINGS_SPOKEN: NightTimePromiseTrait._NtpState.ValueType  # 4
        NTP_STATE_CRITICAL_WARNINGS_SPOKEN: NightTimePromiseTrait._NtpState.ValueType  # 5
        NTP_STATE_DONE: NightTimePromiseTrait._NtpState.ValueType  # 6

    class NtpState(_NtpState, metaclass=_NtpStateEnumTypeWrapper): ...
    NTP_STATE_UNSPECIFIED: NightTimePromiseTrait.NtpState.ValueType  # 0
    NTP_STATE_ALL_CLEAR_NTP_ENABLED: NightTimePromiseTrait.NtpState.ValueType  # 1
    NTP_STATE_ALL_CLEAR_NTP_DISABLED: NightTimePromiseTrait.NtpState.ValueType  # 2
    NTP_STATE_WARNINGS_DISPLAYED: NightTimePromiseTrait.NtpState.ValueType  # 3
    NTP_STATE_WARNINGS_SPOKEN: NightTimePromiseTrait.NtpState.ValueType  # 4
    NTP_STATE_CRITICAL_WARNINGS_SPOKEN: NightTimePromiseTrait.NtpState.ValueType  # 5
    NTP_STATE_DONE: NightTimePromiseTrait.NtpState.ValueType  # 6

    @_typing.final
    class NightTimePromiseEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATE_FIELD_NUMBER: _builtins.int
        USINGREMOTE_FIELD_NUMBER: _builtins.int
        CRITICALWARNINGS_FIELD_NUMBER: _builtins.int
        WARNINGCOUNT_FIELD_NUMBER: _builtins.int
        state: Global___NightTimePromiseTrait.NtpState.ValueType
        usingRemote: _builtins.bool
        criticalWarnings: _builtins.bool
        warningCount: _builtins.int
        def __init__(
            self,
            *,
            state: Global___NightTimePromiseTrait.NtpState.ValueType = ...,
            usingRemote: _builtins.bool = ...,
            criticalWarnings: _builtins.bool = ...,
            warningCount: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["criticalWarnings", b"criticalWarnings", "state", b"state", "usingRemote", b"usingRemote", "warningCount", b"warningCount"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___NightTimePromiseTrait: _TypeAlias = NightTimePromiseTrait  # noqa: Y015

@_typing.final
class ProtectDeviceInfoTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _CertRegion:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CertRegionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ProtectDeviceInfoTrait._CertRegion.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CERT_REGION_UNSPECIFIED: ProtectDeviceInfoTrait._CertRegion.ValueType  # 0
        CERT_REGION_US: ProtectDeviceInfoTrait._CertRegion.ValueType  # 1
        CERT_REGION_EU: ProtectDeviceInfoTrait._CertRegion.ValueType  # 2
        CERT_REGION_AU: ProtectDeviceInfoTrait._CertRegion.ValueType  # 3

    class CertRegion(_CertRegion, metaclass=_CertRegionEnumTypeWrapper): ...
    CERT_REGION_UNSPECIFIED: ProtectDeviceInfoTrait.CertRegion.ValueType  # 0
    CERT_REGION_US: ProtectDeviceInfoTrait.CertRegion.ValueType  # 1
    CERT_REGION_EU: ProtectDeviceInfoTrait.CertRegion.ValueType  # 2
    CERT_REGION_AU: ProtectDeviceInfoTrait.CertRegion.ValueType  # 3

    @_typing.final
    class AppDailyConnectionStatusEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WDMDISCONNECTTIME_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def wdmDisconnectTime(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            wdmDisconnectTime: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["wdmDisconnectTime", b"wdmDisconnectTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["wdmDisconnectTime", b"wdmDisconnectTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DEVICEEXTERNALCOLOR_FIELD_NUMBER: _builtins.int
    CERTIFICATIONBODY_FIELD_NUMBER: _builtins.int
    deviceExternalColor: _builtins.str
    certificationBody: Global___ProtectDeviceInfoTrait.CertRegion.ValueType
    def __init__(
        self,
        *,
        deviceExternalColor: _builtins.str = ...,
        certificationBody: Global___ProtectDeviceInfoTrait.CertRegion.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["certificationBody", b"certificationBody", "deviceExternalColor", b"deviceExternalColor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProtectDeviceInfoTrait: _TypeAlias = ProtectDeviceInfoTrait  # noqa: Y015

@_typing.final
class SafetySummaryTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _FailureType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _FailureTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SafetySummaryTrait._FailureType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        FAILURE_TYPE_UNSPECIFIED: SafetySummaryTrait._FailureType.ValueType  # 0
        FAILURE_TYPE_SMOKE: SafetySummaryTrait._FailureType.ValueType  # 1
        FAILURE_TYPE_CO: SafetySummaryTrait._FailureType.ValueType  # 2
        FAILURE_TYPE_TEMP: SafetySummaryTrait._FailureType.ValueType  # 4
        FAILURE_TYPE_HUM: SafetySummaryTrait._FailureType.ValueType  # 8
        FAILURE_TYPE_ALS: SafetySummaryTrait._FailureType.ValueType  # 16
        FAILURE_TYPE_US: SafetySummaryTrait._FailureType.ValueType  # 32
        FAILURE_TYPE_PIR: SafetySummaryTrait._FailureType.ValueType  # 64
        FAILURE_TYPE_BUZZER: SafetySummaryTrait._FailureType.ValueType  # 128
        FAILURE_TYPE_EXPIRED: SafetySummaryTrait._FailureType.ValueType  # 256
        FAILURE_TYPE_EXPIRING: SafetySummaryTrait._FailureType.ValueType  # 512
        FAILURE_TYPE_BATT_VERYLOW: SafetySummaryTrait._FailureType.ValueType  # 1024
        FAILURE_TYPE_BATT_LOW: SafetySummaryTrait._FailureType.ValueType  # 2048
        FAILURE_TYPE_WIFI: SafetySummaryTrait._FailureType.ValueType  # 4096
        FAILURE_TYPE_LED: SafetySummaryTrait._FailureType.ValueType  # 8192
        FAILURE_TYPE_AUDIO: SafetySummaryTrait._FailureType.ValueType  # 16384
        FAILURE_TYPE_POWEROUT: SafetySummaryTrait._FailureType.ValueType  # 32768
        FAILURE_TYPE_OFFLINE: SafetySummaryTrait._FailureType.ValueType  # 65536

    class FailureType(_FailureType, metaclass=_FailureTypeEnumTypeWrapper): ...
    FAILURE_TYPE_UNSPECIFIED: SafetySummaryTrait.FailureType.ValueType  # 0
    FAILURE_TYPE_SMOKE: SafetySummaryTrait.FailureType.ValueType  # 1
    FAILURE_TYPE_CO: SafetySummaryTrait.FailureType.ValueType  # 2
    FAILURE_TYPE_TEMP: SafetySummaryTrait.FailureType.ValueType  # 4
    FAILURE_TYPE_HUM: SafetySummaryTrait.FailureType.ValueType  # 8
    FAILURE_TYPE_ALS: SafetySummaryTrait.FailureType.ValueType  # 16
    FAILURE_TYPE_US: SafetySummaryTrait.FailureType.ValueType  # 32
    FAILURE_TYPE_PIR: SafetySummaryTrait.FailureType.ValueType  # 64
    FAILURE_TYPE_BUZZER: SafetySummaryTrait.FailureType.ValueType  # 128
    FAILURE_TYPE_EXPIRED: SafetySummaryTrait.FailureType.ValueType  # 256
    FAILURE_TYPE_EXPIRING: SafetySummaryTrait.FailureType.ValueType  # 512
    FAILURE_TYPE_BATT_VERYLOW: SafetySummaryTrait.FailureType.ValueType  # 1024
    FAILURE_TYPE_BATT_LOW: SafetySummaryTrait.FailureType.ValueType  # 2048
    FAILURE_TYPE_WIFI: SafetySummaryTrait.FailureType.ValueType  # 4096
    FAILURE_TYPE_LED: SafetySummaryTrait.FailureType.ValueType  # 8192
    FAILURE_TYPE_AUDIO: SafetySummaryTrait.FailureType.ValueType  # 16384
    FAILURE_TYPE_POWEROUT: SafetySummaryTrait.FailureType.ValueType  # 32768
    FAILURE_TYPE_OFFLINE: SafetySummaryTrait.FailureType.ValueType  # 65536

    @_typing.final
    class DeviceStatus(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESOURCEID_FIELD_NUMBER: _builtins.int
        SPOKENWHEREANNOTATION_FIELD_NUMBER: _builtins.int
        FAILURES_FIELD_NUMBER: _builtins.int
        CRITICALMASK_FIELD_NUMBER: _builtins.int
        PRODUCTID_FIELD_NUMBER: _builtins.int
        VENDORID_FIELD_NUMBER: _builtins.int
        productId: _builtins.int
        vendorId: _builtins.int
        @_builtins.property
        def resourceId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def spokenWhereAnnotation(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def failures(self) -> _containers.RepeatedScalarFieldContainer[Global___SafetySummaryTrait.FailureType.ValueType]: ...
        @_builtins.property
        def criticalMask(self) -> _containers.RepeatedScalarFieldContainer[Global___SafetySummaryTrait.FailureType.ValueType]: ...
        def __init__(
            self,
            *,
            resourceId: _common_pb2.ResourceId | None = ...,
            spokenWhereAnnotation: _common_pb2.ResourceId | None = ...,
            failures: _abc.Iterable[Global___SafetySummaryTrait.FailureType.ValueType] | None = ...,
            criticalMask: _abc.Iterable[Global___SafetySummaryTrait.FailureType.ValueType] | None = ...,
            productId: _builtins.int = ...,
            vendorId: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "spokenWhereAnnotation", b"spokenWhereAnnotation"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["criticalMask", b"criticalMask", "failures", b"failures", "productId", b"productId", "resourceId", b"resourceId", "spokenWhereAnnotation", b"spokenWhereAnnotation", "vendorId", b"vendorId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CRITICALDEVICES_FIELD_NUMBER: _builtins.int
    WARNINGDEVICES_FIELD_NUMBER: _builtins.int
    TOTALCRITICALFAILURES_FIELD_NUMBER: _builtins.int
    TOTALWARNINGS_FIELD_NUMBER: _builtins.int
    TESTID_FIELD_NUMBER: _builtins.int
    totalCriticalFailures: _builtins.int
    totalWarnings: _builtins.int
    @_builtins.property
    def criticalDevices(self) -> _containers.RepeatedCompositeFieldContainer[Global___SafetySummaryTrait.DeviceStatus]: ...
    @_builtins.property
    def warningDevices(self) -> _containers.RepeatedCompositeFieldContainer[Global___SafetySummaryTrait.DeviceStatus]: ...
    @_builtins.property
    def testId(self) -> _selftest_pb2.SelfTestRunnerTrait.TestId: ...
    def __init__(
        self,
        *,
        criticalDevices: _abc.Iterable[Global___SafetySummaryTrait.DeviceStatus] | None = ...,
        warningDevices: _abc.Iterable[Global___SafetySummaryTrait.DeviceStatus] | None = ...,
        totalCriticalFailures: _builtins.int = ...,
        totalWarnings: _builtins.int = ...,
        testId: _selftest_pb2.SelfTestRunnerTrait.TestId | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["criticalDevices", b"criticalDevices", "testId", b"testId", "totalCriticalFailures", b"totalCriticalFailures", "totalWarnings", b"totalWarnings", "warningDevices", b"warningDevices"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SafetySummaryTrait: _TypeAlias = SafetySummaryTrait  # noqa: Y015

@_typing.final
class ActionSchedulerTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ActionSchedulerOpEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OPID_FIELD_NUMBER: _builtins.int
        ACTIONID_FIELD_NUMBER: _builtins.int
        opId: _builtins.int
        actionId: _builtins.int
        def __init__(
            self,
            *,
            opId: _builtins.int = ...,
            actionId: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["actionId", b"actionId", "opId", b"opId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___ActionSchedulerTrait: _TypeAlias = ActionSchedulerTrait  # noqa: Y015

@_typing.final
class AudioPlayTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AudioPlayEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SENTENCEID_FIELD_NUMBER: _builtins.int
        SENTENCESTRING_FIELD_NUMBER: _builtins.int
        SENTENCEARGIDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sentenceId(self) -> _wrappers_pb2.UInt32Value: ...
        @_builtins.property
        def sentenceString(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def sentenceArgIds(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(
            self,
            *,
            sentenceId: _wrappers_pb2.UInt32Value | None = ...,
            sentenceString: _wrappers_pb2.StringValue | None = ...,
            sentenceArgIds: _abc.Iterable[_builtins.int] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sentenceId", b"sentenceId", "sentenceString", b"sentenceString"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sentenceArgIds", b"sentenceArgIds", "sentenceId", b"sentenceId", "sentenceString", b"sentenceString"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___AudioPlayTrait: _TypeAlias = AudioPlayTrait  # noqa: Y015

@_typing.final
class LegacyAlarmHistoryTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AlarmStatus(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        SYNCED_FIELD_NUMBER: _builtins.int
        status: _builtins.int
        synced: _builtins.bool
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            status: _builtins.int = ...,
            synced: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "synced", b"synced", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SMOKEHISTORY_FIELD_NUMBER: _builtins.int
    COHISTORY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def smokeHistory(self) -> _containers.RepeatedCompositeFieldContainer[Global___LegacyAlarmHistoryTrait.AlarmStatus]: ...
    @_builtins.property
    def coHistory(self) -> _containers.RepeatedCompositeFieldContainer[Global___LegacyAlarmHistoryTrait.AlarmStatus]: ...
    def __init__(
        self,
        *,
        smokeHistory: _abc.Iterable[Global___LegacyAlarmHistoryTrait.AlarmStatus] | None = ...,
        coHistory: _abc.Iterable[Global___LegacyAlarmHistoryTrait.AlarmStatus] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["coHistory", b"coHistory", "smokeHistory", b"smokeHistory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LegacyAlarmHistoryTrait: _TypeAlias = LegacyAlarmHistoryTrait  # noqa: Y015

@_typing.final
class LegacySelfTestSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AutomatedSelfTestScheduleChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASTSTARTOFFSETUTCSECS_FIELD_NUMBER: _builtins.int
        ASTENDOFFSETUTCSECS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def astStartOffsetUtcSecs(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def astEndOffsetUtcSecs(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            astStartOffsetUtcSecs: _duration_pb2.Duration | None = ...,
            astEndOffsetUtcSecs: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["astEndOffsetUtcSecs", b"astEndOffsetUtcSecs", "astStartOffsetUtcSecs", b"astStartOffsetUtcSecs"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["astEndOffsetUtcSecs", b"astEndOffsetUtcSecs", "astStartOffsetUtcSecs", b"astStartOffsetUtcSecs"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ASTENABLED_FIELD_NUMBER: _builtins.int
    ASTNOTIFY_FIELD_NUMBER: _builtins.int
    ASTREPEATSECS_FIELD_NUMBER: _builtins.int
    ASTFORCESECS_FIELD_NUMBER: _builtins.int
    ASTSTARTOFFSETUTCSECS_FIELD_NUMBER: _builtins.int
    ASTENDOFFSETUTCSECS_FIELD_NUMBER: _builtins.int
    astEnabled: _builtins.bool
    astNotify: _builtins.bool
    @_builtins.property
    def astRepeatSecs(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def astForceSecs(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def astStartOffsetUtcSecs(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def astEndOffsetUtcSecs(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        astEnabled: _builtins.bool = ...,
        astNotify: _builtins.bool = ...,
        astRepeatSecs: _duration_pb2.Duration | None = ...,
        astForceSecs: _duration_pb2.Duration | None = ...,
        astStartOffsetUtcSecs: _duration_pb2.Duration | None = ...,
        astEndOffsetUtcSecs: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["astEndOffsetUtcSecs", b"astEndOffsetUtcSecs", "astForceSecs", b"astForceSecs", "astRepeatSecs", b"astRepeatSecs", "astStartOffsetUtcSecs", b"astStartOffsetUtcSecs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["astEnabled", b"astEnabled", "astEndOffsetUtcSecs", b"astEndOffsetUtcSecs", "astForceSecs", b"astForceSecs", "astNotify", b"astNotify", "astRepeatSecs", b"astRepeatSecs", "astStartOffsetUtcSecs", b"astStartOffsetUtcSecs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LegacySelfTestSettingsTrait: _TypeAlias = LegacySelfTestSettingsTrait  # noqa: Y015

@_typing.final
class NightTimePromiseSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _NightTimePromiseBrightness:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _NightTimePromiseBrightnessEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[NightTimePromiseSettingsTrait._NightTimePromiseBrightness.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NIGHT_TIME_PROMISE_BRIGHTNESS_UNSPECIFIED: NightTimePromiseSettingsTrait._NightTimePromiseBrightness.ValueType  # 0
        NIGHT_TIME_PROMISE_BRIGHTNESS_LOW: NightTimePromiseSettingsTrait._NightTimePromiseBrightness.ValueType  # 1
        NIGHT_TIME_PROMISE_BRIGHTNESS_MEDIUM: NightTimePromiseSettingsTrait._NightTimePromiseBrightness.ValueType  # 2
        NIGHT_TIME_PROMISE_BRIGHTNESS_HIGH: NightTimePromiseSettingsTrait._NightTimePromiseBrightness.ValueType  # 3

    class NightTimePromiseBrightness(_NightTimePromiseBrightness, metaclass=_NightTimePromiseBrightnessEnumTypeWrapper): ...
    NIGHT_TIME_PROMISE_BRIGHTNESS_UNSPECIFIED: NightTimePromiseSettingsTrait.NightTimePromiseBrightness.ValueType  # 0
    NIGHT_TIME_PROMISE_BRIGHTNESS_LOW: NightTimePromiseSettingsTrait.NightTimePromiseBrightness.ValueType  # 1
    NIGHT_TIME_PROMISE_BRIGHTNESS_MEDIUM: NightTimePromiseSettingsTrait.NightTimePromiseBrightness.ValueType  # 2
    NIGHT_TIME_PROMISE_BRIGHTNESS_HIGH: NightTimePromiseSettingsTrait.NightTimePromiseBrightness.ValueType  # 3

    GREENLEDENABLED_FIELD_NUMBER: _builtins.int
    GREENLEDBRIGHTNESS_FIELD_NUMBER: _builtins.int
    greenLedEnabled: _builtins.bool
    greenLedBrightness: Global___NightTimePromiseSettingsTrait.NightTimePromiseBrightness.ValueType
    def __init__(
        self,
        *,
        greenLedEnabled: _builtins.bool = ...,
        greenLedBrightness: Global___NightTimePromiseSettingsTrait.NightTimePromiseBrightness.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["greenLedBrightness", b"greenLedBrightness", "greenLedEnabled", b"greenLedEnabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NightTimePromiseSettingsTrait: _TypeAlias = NightTimePromiseSettingsTrait  # noqa: Y015

@_typing.final
class OutOfBoxTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OutOfBoxFinishedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SUCCESS_FIELD_NUMBER: _builtins.int
        DEFAULTLANGUAGESELECTED_FIELD_NUMBER: _builtins.int
        CURRENTLANGUAGE_FIELD_NUMBER: _builtins.int
        OSMSWAPPOSSIBLE_FIELD_NUMBER: _builtins.int
        REPEATCOUNT_FIELD_NUMBER: _builtins.int
        success: _builtins.bool
        defaultLanguageSelected: _builtins.bool
        currentLanguage: _builtins.bool
        osmSwapPossible: _builtins.bool
        repeatCount: _builtins.int
        def __init__(
            self,
            *,
            success: _builtins.bool = ...,
            defaultLanguageSelected: _builtins.bool = ...,
            currentLanguage: _builtins.bool = ...,
            osmSwapPossible: _builtins.bool = ...,
            repeatCount: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["currentLanguage", b"currentLanguage", "defaultLanguageSelected", b"defaultLanguageSelected", "osmSwapPossible", b"osmSwapPossible", "repeatCount", b"repeatCount", "success", b"success"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___OutOfBoxTrait: _TypeAlias = OutOfBoxTrait  # noqa: Y015

@_typing.final
class LegacyProtectDeviceInfoTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CAPABILITYIDX_FIELD_NUMBER: _builtins.int
    AUTOAWAY_FIELD_NUMBER: _builtins.int
    CAPABILITYLEVEL_FIELD_NUMBER: _builtins.int
    LINEPOWERCAPABLE_FIELD_NUMBER: _builtins.int
    SPSOFTWAREVERSION_FIELD_NUMBER: _builtins.int
    capabilityIdx: _builtins.str
    autoAway: _builtins.bool
    linePowerCapable: _builtins.bool
    spSoftwareVersion: _builtins.str
    @_builtins.property
    def capabilityLevel(self) -> _wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        capabilityIdx: _builtins.str = ...,
        autoAway: _builtins.bool = ...,
        capabilityLevel: _wrappers_pb2.FloatValue | None = ...,
        linePowerCapable: _builtins.bool = ...,
        spSoftwareVersion: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["capabilityLevel", b"capabilityLevel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["autoAway", b"autoAway", "capabilityIdx", b"capabilityIdx", "capabilityLevel", b"capabilityLevel", "linePowerCapable", b"linePowerCapable", "spSoftwareVersion", b"spSoftwareVersion"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LegacyProtectDeviceInfoTrait: _TypeAlias = LegacyProtectDeviceInfoTrait  # noqa: Y015

@_typing.final
class LegacyProtectDeviceSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REPLACEBYDATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def replaceByDate(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        replaceByDate: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["replaceByDate", b"replaceByDate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["replaceByDate", b"replaceByDate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LegacyProtectDeviceSettingsTrait: _TypeAlias = LegacyProtectDeviceSettingsTrait  # noqa: Y015

@_typing.final
class SafetyStructureSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STRUCTUREHUSHKEY_FIELD_NUMBER: _builtins.int
    PHONEHUSHENABLED_FIELD_NUMBER: _builtins.int
    structureHushKey: _builtins.str
    phoneHushEnabled: _builtins.bool
    def __init__(
        self,
        *,
        structureHushKey: _builtins.str = ...,
        phoneHushEnabled: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["phoneHushEnabled", b"phoneHushEnabled", "structureHushKey", b"structureHushKey"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SafetyStructureSettingsTrait: _TypeAlias = SafetyStructureSettingsTrait  # noqa: Y015
