"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import field_mask_pb2 as _field_mask_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BasicUserSchedulesSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ScheduleErrorCodes:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ScheduleErrorCodesEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BasicUserSchedulesSettingsTrait._ScheduleErrorCodes.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SCHEDULE_ERROR_CODES_UNSPECIFIED: BasicUserSchedulesSettingsTrait._ScheduleErrorCodes.ValueType  # 0
        SCHEDULE_ERROR_CODES_SUCCESS_STATUS: BasicUserSchedulesSettingsTrait._ScheduleErrorCodes.ValueType  # 1
        SCHEDULE_ERROR_CODES_DUPLICATE_ENTRY: BasicUserSchedulesSettingsTrait._ScheduleErrorCodes.ValueType  # 2
        SCHEDULE_ERROR_CODES_INDEX_OUT_OF_RANGE: BasicUserSchedulesSettingsTrait._ScheduleErrorCodes.ValueType  # 3
        SCHEDULE_ERROR_CODES_EMPTY_SCHEDULE_ENTRY: BasicUserSchedulesSettingsTrait._ScheduleErrorCodes.ValueType  # 4
        SCHEDULE_ERROR_CODES_INVALID_SCHEDULE: BasicUserSchedulesSettingsTrait._ScheduleErrorCodes.ValueType  # 5

    class ScheduleErrorCodes(_ScheduleErrorCodes, metaclass=_ScheduleErrorCodesEnumTypeWrapper): ...
    SCHEDULE_ERROR_CODES_UNSPECIFIED: BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType  # 0
    SCHEDULE_ERROR_CODES_SUCCESS_STATUS: BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType  # 1
    SCHEDULE_ERROR_CODES_DUPLICATE_ENTRY: BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType  # 2
    SCHEDULE_ERROR_CODES_INDEX_OUT_OF_RANGE: BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType  # 3
    SCHEDULE_ERROR_CODES_EMPTY_SCHEDULE_ENTRY: BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType  # 4
    SCHEDULE_ERROR_CODES_INVALID_SCHEDULE: BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType  # 5

    @_typing.final
    class BasicUserSchedulesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DailyRepeatingScheduleItem(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DAYSOFWEEK_FIELD_NUMBER: _builtins.int
        STARTTIME_FIELD_NUMBER: _builtins.int
        DURATION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def daysOfWeek(self) -> _containers.RepeatedScalarFieldContainer[_common_pb2.DayOfWeek.ValueType]: ...
        @_builtins.property
        def startTime(self) -> _common_pb2.TimeOfDay: ...
        @_builtins.property
        def duration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            daysOfWeek: _abc.Iterable[_common_pb2.DayOfWeek.ValueType] | None = ...,
            startTime: _common_pb2.TimeOfDay | None = ...,
            duration: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["duration", b"duration", "startTime", b"startTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["daysOfWeek", b"daysOfWeek", "duration", b"duration", "startTime", b"startTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class TimeboxScheduleItem(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STARTTIME_FIELD_NUMBER: _builtins.int
        ENDTIME_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def startTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def endTime(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            startTime: _timestamp_pb2.Timestamp | None = ...,
            endTime: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["endTime", b"endTime", "startTime", b"startTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["endTime", b"endTime", "startTime", b"startTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BasicUserSchedule(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        DAILYREPEATINGSCHEDULES_FIELD_NUMBER: _builtins.int
        TIMEBOXSCHEDULES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def dailyRepeatingSchedules(self) -> _containers.RepeatedCompositeFieldContainer[Global___BasicUserSchedulesSettingsTrait.DailyRepeatingScheduleItem]: ...
        @_builtins.property
        def timeBoxSchedules(self) -> _containers.RepeatedCompositeFieldContainer[Global___BasicUserSchedulesSettingsTrait.TimeboxScheduleItem]: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
            dailyRepeatingSchedules: _abc.Iterable[Global___BasicUserSchedulesSettingsTrait.DailyRepeatingScheduleItem] | None = ...,
            timeBoxSchedules: _abc.Iterable[Global___BasicUserSchedulesSettingsTrait.TimeboxScheduleItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["dailyRepeatingSchedules", b"dailyRepeatingSchedules", "timeBoxSchedules", b"timeBoxSchedules", "userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetUserScheduleRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERSCHEDULE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userSchedule(self) -> Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule: ...
        def __init__(
            self,
            *,
            userSchedule: Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userSchedule", b"userSchedule"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["userSchedule", b"userSchedule"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetUserScheduleResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType
        def __init__(
            self,
            *,
            status: Global___BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class GetUserScheduleRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class GetUserScheduleResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        USERSCHEDULE_FIELD_NUMBER: _builtins.int
        status: Global___BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType
        @_builtins.property
        def userSchedule(self) -> Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule: ...
        def __init__(
            self,
            *,
            status: Global___BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType = ...,
            userSchedule: Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userSchedule", b"userSchedule"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "userSchedule", b"userSchedule"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DeleteUserScheduleRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["userId", b"userId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DeleteUserScheduleResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType
        def __init__(
            self,
            *,
            status: Global___BasicUserSchedulesSettingsTrait.ScheduleErrorCodes.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class OfflineDeviceSyncSchedulesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class BasicUserSchedulesEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.int
            @_builtins.property
            def value(self) -> Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule: ...
            def __init__(
                self,
                *,
                key: _builtins.int = ...,
                value: Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        BASICUSERSCHEDULES_FIELD_NUMBER: _builtins.int
        STATEMASK_FIELD_NUMBER: _builtins.int
        STATEVERSION_FIELD_NUMBER: _builtins.int
        ACCEPTEDTIMESTAMP_FIELD_NUMBER: _builtins.int
        CONFIRMEDTIMESTAMP_FIELD_NUMBER: _builtins.int
        stateVersion: _builtins.str
        @_builtins.property
        def basicUserSchedules(self) -> _containers.MessageMap[_builtins.int, Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule]: ...
        @_builtins.property
        def stateMask(self) -> _field_mask_pb2.FieldMask: ...
        @_builtins.property
        def acceptedTimestamp(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def confirmedTimestamp(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            basicUserSchedules: _abc.Mapping[_builtins.int, Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule] | None = ...,
            stateMask: _field_mask_pb2.FieldMask | None = ...,
            stateVersion: _builtins.str = ...,
            acceptedTimestamp: _timestamp_pb2.Timestamp | None = ...,
            confirmedTimestamp: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["acceptedTimestamp", b"acceptedTimestamp", "confirmedTimestamp", b"confirmedTimestamp", "stateMask", b"stateMask"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["acceptedTimestamp", b"acceptedTimestamp", "basicUserSchedules", b"basicUserSchedules", "confirmedTimestamp", b"confirmedTimestamp", "stateMask", b"stateMask", "stateVersion", b"stateVersion"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    BASICUSERSCHEDULES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def basicUserSchedules(self) -> _containers.MessageMap[_builtins.int, Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule]: ...
    def __init__(
        self,
        *,
        basicUserSchedules: _abc.Mapping[_builtins.int, Global___BasicUserSchedulesSettingsTrait.BasicUserSchedule] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["basicUserSchedules", b"basicUserSchedules"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BasicUserSchedulesSettingsTrait: _TypeAlias = BasicUserSchedulesSettingsTrait  # noqa: Y015

@_typing.final
class BasicUserSchedulesCapabilitiesTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BASICMAXTIMEBOXSCHEDULESSUPPORTEDPERUSER_FIELD_NUMBER: _builtins.int
    BASICMAXDAILYREPEATEDSUPPORTEDPERUSER_FIELD_NUMBER: _builtins.int
    basicMaxTimeBoxSchedulesSupportedPerUser: _builtins.int
    basicMaxDailyRepeatedSupportedPerUser: _builtins.int
    def __init__(
        self,
        *,
        basicMaxTimeBoxSchedulesSupportedPerUser: _builtins.int = ...,
        basicMaxDailyRepeatedSupportedPerUser: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["basicMaxDailyRepeatedSupportedPerUser", b"basicMaxDailyRepeatedSupportedPerUser", "basicMaxTimeBoxSchedulesSupportedPerUser", b"basicMaxTimeBoxSchedulesSupportedPerUser"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BasicUserSchedulesCapabilitiesTrait: _TypeAlias = BasicUserSchedulesCapabilitiesTrait  # noqa: Y015
