"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MicrophoneSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLEMICROPHONE_FIELD_NUMBER: _builtins.int
    enableMicrophone: _builtins.bool
    def __init__(
        self,
        *,
        enableMicrophone: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enableMicrophone", b"enableMicrophone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MicrophoneSettingsTrait: _TypeAlias = MicrophoneSettingsTrait  # noqa: Y015
