"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class OpenCloseTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _OpenCloseState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _OpenCloseStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[OpenCloseTrait._OpenCloseState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OPEN_CLOSE_STATE_UNSPECIFIED: OpenCloseTrait._OpenCloseState.ValueType  # 0
        OPEN_CLOSE_STATE_CLOSED: OpenCloseTrait._OpenCloseState.ValueType  # 1
        OPEN_CLOSE_STATE_OPEN: OpenCloseTrait._OpenCloseState.ValueType  # 2
        OPEN_CLOSE_STATE_UNKNOWN: OpenCloseTrait._OpenCloseState.ValueType  # 3
        OPEN_CLOSE_STATE_INVALID_CALIBRATION: OpenCloseTrait._OpenCloseState.ValueType  # 4

    class OpenCloseState(_OpenCloseState, metaclass=_OpenCloseStateEnumTypeWrapper): ...
    OPEN_CLOSE_STATE_UNSPECIFIED: OpenCloseTrait.OpenCloseState.ValueType  # 0
    OPEN_CLOSE_STATE_CLOSED: OpenCloseTrait.OpenCloseState.ValueType  # 1
    OPEN_CLOSE_STATE_OPEN: OpenCloseTrait.OpenCloseState.ValueType  # 2
    OPEN_CLOSE_STATE_UNKNOWN: OpenCloseTrait.OpenCloseState.ValueType  # 3
    OPEN_CLOSE_STATE_INVALID_CALIBRATION: OpenCloseTrait.OpenCloseState.ValueType  # 4

    @_typing.final
    class OpenCloseEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OPENCLOSESTATE_FIELD_NUMBER: _builtins.int
        PRIOROPENCLOSESTATE_FIELD_NUMBER: _builtins.int
        openCloseState: Global___OpenCloseTrait.OpenCloseState.ValueType
        priorOpenCloseState: Global___OpenCloseTrait.OpenCloseState.ValueType
        def __init__(
            self,
            *,
            openCloseState: Global___OpenCloseTrait.OpenCloseState.ValueType = ...,
            priorOpenCloseState: Global___OpenCloseTrait.OpenCloseState.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["openCloseState", b"openCloseState", "priorOpenCloseState", b"priorOpenCloseState"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    OPENCLOSESTATE_FIELD_NUMBER: _builtins.int
    FIRSTOBSERVEDAT_FIELD_NUMBER: _builtins.int
    FIRSTOBSERVEDATMS_FIELD_NUMBER: _builtins.int
    openCloseState: Global___OpenCloseTrait.OpenCloseState.ValueType
    @_builtins.property
    def firstObservedAt(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def firstObservedAtMs(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        openCloseState: Global___OpenCloseTrait.OpenCloseState.ValueType = ...,
        firstObservedAt: _timestamp_pb2.Timestamp | None = ...,
        firstObservedAtMs: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["firstObservedAt", b"firstObservedAt", "firstObservedAtMs", b"firstObservedAtMs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["firstObservedAt", b"firstObservedAt", "firstObservedAtMs", b"firstObservedAtMs", "openCloseState", b"openCloseState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OpenCloseTrait: _TypeAlias = OpenCloseTrait  # noqa: Y015

@_typing.final
class AmbientMotionTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AmbientMotionEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STARTMOTION_FIELD_NUMBER: _builtins.int
        MAXHOLDOFF_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def startMotion(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def maxHoldOff(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            startMotion: _timestamp_pb2.Timestamp | None = ...,
            maxHoldOff: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["maxHoldOff", b"maxHoldOff", "startMotion", b"startMotion"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["maxHoldOff", b"maxHoldOff", "startMotion", b"startMotion"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___AmbientMotionTrait: _TypeAlias = AmbientMotionTrait  # noqa: Y015

@_typing.final
class AmbientMotionSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLEDETECTION_FIELD_NUMBER: _builtins.int
    enableDetection: _builtins.bool
    def __init__(
        self,
        *,
        enableDetection: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enableDetection", b"enableDetection"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AmbientMotionSettingsTrait: _TypeAlias = AmbientMotionSettingsTrait  # noqa: Y015

@_typing.final
class AmbientMotionTimingSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAXHOLDOFF_FIELD_NUMBER: _builtins.int
    OVERRIDEMAXHOLDOFF_FIELD_NUMBER: _builtins.int
    overrideMaxHoldOff: _builtins.bool
    @_builtins.property
    def maxHoldOff(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        maxHoldOff: _duration_pb2.Duration | None = ...,
        overrideMaxHoldOff: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["maxHoldOff", b"maxHoldOff"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["maxHoldOff", b"maxHoldOff", "overrideMaxHoldOff", b"overrideMaxHoldOff"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AmbientMotionTimingSettingsTrait: _TypeAlias = AmbientMotionTimingSettingsTrait  # noqa: Y015
