"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...weave import common_pb2 as _common_pb2
from ...weave.trait import schedule_pb2 as _schedule_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GuestsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ResponseStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ResponseStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[GuestsTrait._ResponseStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        RESPONSE_STATUS_UNSPECIFIED: GuestsTrait._ResponseStatus.ValueType  # 0
        RESPONSE_STATUS_SUCCESS: GuestsTrait._ResponseStatus.ValueType  # 1
        RESPONSE_STATUS_INTERNAL_FAILURE: GuestsTrait._ResponseStatus.ValueType  # 2
        RESPONSE_STATUS_COMMAND_MISSING_PARAMS: GuestsTrait._ResponseStatus.ValueType  # 3
        RESPONSE_STATUS_DUP_GUEST_NAME: GuestsTrait._ResponseStatus.ValueType  # 4
        RESPONSE_STATUS_LIMIT_REACHED: GuestsTrait._ResponseStatus.ValueType  # 5
        RESPONSE_STATUS_DUP_PINCODE: GuestsTrait._ResponseStatus.ValueType  # 6
        RESPONSE_STATUS_GUEST_NOT_FOUND: GuestsTrait._ResponseStatus.ValueType  # 7

    class ResponseStatus(_ResponseStatus, metaclass=_ResponseStatusEnumTypeWrapper): ...
    RESPONSE_STATUS_UNSPECIFIED: GuestsTrait.ResponseStatus.ValueType  # 0
    RESPONSE_STATUS_SUCCESS: GuestsTrait.ResponseStatus.ValueType  # 1
    RESPONSE_STATUS_INTERNAL_FAILURE: GuestsTrait.ResponseStatus.ValueType  # 2
    RESPONSE_STATUS_COMMAND_MISSING_PARAMS: GuestsTrait.ResponseStatus.ValueType  # 3
    RESPONSE_STATUS_DUP_GUEST_NAME: GuestsTrait.ResponseStatus.ValueType  # 4
    RESPONSE_STATUS_LIMIT_REACHED: GuestsTrait.ResponseStatus.ValueType  # 5
    RESPONSE_STATUS_DUP_PINCODE: GuestsTrait.ResponseStatus.ValueType  # 6
    RESPONSE_STATUS_GUEST_NOT_FOUND: GuestsTrait.ResponseStatus.ValueType  # 7

    class _GuestStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _GuestStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[GuestsTrait._GuestStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        GUEST_STATUS_UNSPECIFIED: GuestsTrait._GuestStatus.ValueType  # 0
        GUEST_STATUS_ACTIVE: GuestsTrait._GuestStatus.ValueType  # 1
        GUEST_STATUS_INVITED: GuestsTrait._GuestStatus.ValueType  # 2
        GUEST_STATUS_ACCESS_EXPIRED: GuestsTrait._GuestStatus.ValueType  # 3

    class GuestStatus(_GuestStatus, metaclass=_GuestStatusEnumTypeWrapper): ...
    GUEST_STATUS_UNSPECIFIED: GuestsTrait.GuestStatus.ValueType  # 0
    GUEST_STATUS_ACTIVE: GuestsTrait.GuestStatus.ValueType  # 1
    GUEST_STATUS_INVITED: GuestsTrait.GuestStatus.ValueType  # 2
    GUEST_STATUS_ACCESS_EXPIRED: GuestsTrait.GuestStatus.ValueType  # 3

    @_typing.final
    class Guest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        ID_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        INVITATIONSENTTIME_FIELD_NUMBER: _builtins.int
        INVITATIONACCEPTANCETIME_FIELD_NUMBER: _builtins.int
        AVATARURL_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        status: Global___GuestsTrait.GuestStatus.ValueType
        avatarUrl: _builtins.str
        @_builtins.property
        def id(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def invitationSentTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def invitationAcceptanceTime(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            name: _builtins.str = ...,
            id: _common_pb2.ResourceId | None = ...,
            status: Global___GuestsTrait.GuestStatus.ValueType = ...,
            invitationSentTime: _timestamp_pb2.Timestamp | None = ...,
            invitationAcceptanceTime: _timestamp_pb2.Timestamp | None = ...,
            avatarUrl: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "invitationAcceptanceTime", b"invitationAcceptanceTime", "invitationSentTime", b"invitationSentTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["avatarUrl", b"avatarUrl", "id", b"id", "invitationAcceptanceTime", b"invitationAcceptanceTime", "invitationSentTime", b"invitationSentTime", "name", b"name", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CreateGuestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        PINCODE_FIELD_NUMBER: _builtins.int
        SCHEDULE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        pincode: _builtins.bytes
        @_builtins.property
        def schedule(self) -> _schedule_pb2.BasicUserSchedulesSettingsTrait.BasicUserSchedule: ...
        def __init__(
            self,
            *,
            name: _builtins.str = ...,
            pincode: _builtins.bytes = ...,
            schedule: _schedule_pb2.BasicUserSchedulesSettingsTrait.BasicUserSchedule | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["schedule", b"schedule"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "pincode", b"pincode", "schedule", b"schedule"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CreateGuestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GUESTID_FIELD_NUMBER: _builtins.int
        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___GuestsTrait.ResponseStatus.ValueType
        @_builtins.property
        def guestId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            guestId: _common_pb2.ResourceId | None = ...,
            status: Global___GuestsTrait.ResponseStatus.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RemoveGuestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GUESTID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def guestId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            guestId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RemoveGuestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___GuestsTrait.ResponseStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___GuestsTrait.ResponseStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class InviteGuestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GUESTID_FIELD_NUMBER: _builtins.int
        EMAIL_FIELD_NUMBER: _builtins.int
        ENCRYPTIONKEY_FIELD_NUMBER: _builtins.int
        ENCRYPTEDPAYLOAD_FIELD_NUMBER: _builtins.int
        NOTES_FIELD_NUMBER: _builtins.int
        email: _builtins.str
        encryptionKey: _builtins.bytes
        encryptedPayload: _builtins.bytes
        notes: _builtins.str
        @_builtins.property
        def guestId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            guestId: _common_pb2.ResourceId | None = ...,
            email: _builtins.str = ...,
            encryptionKey: _builtins.bytes = ...,
            encryptedPayload: _builtins.bytes = ...,
            notes: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "encryptedPayload", b"encryptedPayload", "encryptionKey", b"encryptionKey", "guestId", b"guestId", "notes", b"notes"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class GuestInvitation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        INVITATIONUUID_FIELD_NUMBER: _builtins.int
        ENCRYPTEDPAYLOAD_FIELD_NUMBER: _builtins.int
        CREATEDAT_FIELD_NUMBER: _builtins.int
        SENTAT_FIELD_NUMBER: _builtins.int
        CLAIMEDAT_FIELD_NUMBER: _builtins.int
        INVISIBLEAT_FIELD_NUMBER: _builtins.int
        invitationUuid: _builtins.str
        encryptedPayload: _builtins.bytes
        @_builtins.property
        def createdAt(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def sentAt(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def claimedAt(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def invisibleAt(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            invitationUuid: _builtins.str = ...,
            encryptedPayload: _builtins.bytes = ...,
            createdAt: _timestamp_pb2.Timestamp | None = ...,
            sentAt: _timestamp_pb2.Timestamp | None = ...,
            claimedAt: _timestamp_pb2.Timestamp | None = ...,
            invisibleAt: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["claimedAt", b"claimedAt", "createdAt", b"createdAt", "invisibleAt", b"invisibleAt", "sentAt", b"sentAt"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["claimedAt", b"claimedAt", "createdAt", b"createdAt", "encryptedPayload", b"encryptedPayload", "invisibleAt", b"invisibleAt", "invitationUuid", b"invitationUuid", "sentAt", b"sentAt"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class InviteGuestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___GuestsTrait.ResponseStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___GuestsTrait.ResponseStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetGuestAvatarUrlRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GUESTID_FIELD_NUMBER: _builtins.int
        AVATARURL_FIELD_NUMBER: _builtins.int
        avatarUrl: _builtins.str
        @_builtins.property
        def guestId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            guestId: _common_pb2.ResourceId | None = ...,
            avatarUrl: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["avatarUrl", b"avatarUrl", "guestId", b"guestId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SetGuestAvatarUrlResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        status: Global___GuestsTrait.ResponseStatus.ValueType
        def __init__(
            self,
            *,
            status: Global___GuestsTrait.ResponseStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CreateGuestEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        INVITERID_FIELD_NUMBER: _builtins.int
        STRUCTUREID_FIELD_NUMBER: _builtins.int
        GUESTID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def inviterId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def structureId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def guestId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            inviterId: _common_pb2.ResourceId | None = ...,
            structureId: _common_pb2.ResourceId | None = ...,
            guestId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId", "inviterId", b"inviterId", "structureId", b"structureId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId", "inviterId", b"inviterId", "structureId", b"structureId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class InviteGuestEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GUESTID_FIELD_NUMBER: _builtins.int
        GUESTEMAIL_FIELD_NUMBER: _builtins.int
        INVITATIONLINK_FIELD_NUMBER: _builtins.int
        INVITERID_FIELD_NUMBER: _builtins.int
        STRUCTUREID_FIELD_NUMBER: _builtins.int
        NOTES_FIELD_NUMBER: _builtins.int
        INVISIBLEDATE_FIELD_NUMBER: _builtins.int
        REINVITE_FIELD_NUMBER: _builtins.int
        guestEmail: _builtins.str
        invitationLink: _builtins.str
        notes: _builtins.str
        reinvite: _builtins.bool
        @_builtins.property
        def guestId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def inviterId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def structureId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def invisibleDate(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            guestId: _common_pb2.ResourceId | None = ...,
            guestEmail: _builtins.str = ...,
            invitationLink: _builtins.str = ...,
            inviterId: _common_pb2.ResourceId | None = ...,
            structureId: _common_pb2.ResourceId | None = ...,
            notes: _builtins.str = ...,
            invisibleDate: _timestamp_pb2.Timestamp | None = ...,
            reinvite: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["guestId", b"guestId", "invisibleDate", b"invisibleDate", "inviterId", b"inviterId", "structureId", b"structureId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["guestEmail", b"guestEmail", "guestId", b"guestId", "invisibleDate", b"invisibleDate", "invitationLink", b"invitationLink", "inviterId", b"inviterId", "notes", b"notes", "reinvite", b"reinvite", "structureId", b"structureId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    GUESTS_FIELD_NUMBER: _builtins.int
    MAXGUESTSPERSTRUCTURE_FIELD_NUMBER: _builtins.int
    maxGuestsPerStructure: _builtins.int
    @_builtins.property
    def guests(self) -> _containers.RepeatedCompositeFieldContainer[Global___GuestsTrait.Guest]: ...
    def __init__(
        self,
        *,
        guests: _abc.Iterable[Global___GuestsTrait.Guest] | None = ...,
        maxGuestsPerStructure: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["guests", b"guests", "maxGuestsPerStructure", b"maxGuestsPerStructure"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GuestsTrait: _TypeAlias = GuestsTrait  # noqa: Y015
