"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...nest.trait import hvac_pb2 as _hvac_pb2
from ...nest.trait import occupancy_pb2 as _occupancy_pb2
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CameraObservationHistoryTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class CameraObservationHistoryRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        QUERYSTARTTIME_FIELD_NUMBER: _builtins.int
        QUERYENDTIME_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def queryStartTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def queryEndTime(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            queryStartTime: _timestamp_pb2.Timestamp | None = ...,
            queryEndTime: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["queryEndTime", b"queryEndTime", "queryStartTime", b"queryStartTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["queryEndTime", b"queryEndTime", "queryStartTime", b"queryStartTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CameraObservationHistoryResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class CameraEventTimeWindow(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            class _EventType:
                ValueType = _typing.NewType("ValueType", _builtins.int)
                V: _TypeAlias = ValueType  # noqa: Y015

            class _EventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType], _builtins.type):
                DESCRIPTOR: _descriptor.EnumDescriptor
                EVENT_UNSPECIFIED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 0
                EVENT_MOTION: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 1
                EVENT_SOUND: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 2
                EVENT_PERSON: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 3
                EVENT_FACE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 4
                EVENT_UNFAMILIAR_FACE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 5
                EVENT_PERSON_TALKING: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 6
                EVENT_DOG_BARKING: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 7
                EVENT_DOORBELL: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 8
                EVENT_PACKAGE_DELIVERED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 9
                EVENT_PACKAGE_RETRIEVED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 10
                EVENT_SMOKE_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 11
                EVENT_CO_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 12
                EVENT_FIRE_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 13
                EVENT_GLASS_BREAK: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 14
                EVENT_OFFLINE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 15
                EVENT_BABY_CRYING: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 16
                EVENT_DOOR_KNOCK: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 17
                EVENT_VEHICLE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 18
                EVENT_FACE_OTHER: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 19
                EVENT_PACKAGE_IN_TRANSIT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 20
                EVENT_ANIMAL_DOG: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 21
                EVENT_ANIMAL_CAT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 22
                EVENT_ANIMAL: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 23
                EVENT_MAGIC_MOMENT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 24
                EVENT_CTD: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 25
                EVENT_CMDT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 26
                EVENT_TALKBACK: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 27
                EVENT_SECURITY_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 28
                EVENT_NOT_A_FACE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 29
                EVENT_DOOR_OPEN: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 30
                EVENT_DOOR_CLOSE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 31
                EVENT_DOOR_AJAR: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 32
                EVENT_UNRECOGNIZED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow._EventType.ValueType  # 33

            class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...
            EVENT_UNSPECIFIED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 0
            EVENT_MOTION: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 1
            EVENT_SOUND: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 2
            EVENT_PERSON: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 3
            EVENT_FACE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 4
            EVENT_UNFAMILIAR_FACE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 5
            EVENT_PERSON_TALKING: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 6
            EVENT_DOG_BARKING: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 7
            EVENT_DOORBELL: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 8
            EVENT_PACKAGE_DELIVERED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 9
            EVENT_PACKAGE_RETRIEVED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 10
            EVENT_SMOKE_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 11
            EVENT_CO_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 12
            EVENT_FIRE_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 13
            EVENT_GLASS_BREAK: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 14
            EVENT_OFFLINE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 15
            EVENT_BABY_CRYING: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 16
            EVENT_DOOR_KNOCK: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 17
            EVENT_VEHICLE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 18
            EVENT_FACE_OTHER: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 19
            EVENT_PACKAGE_IN_TRANSIT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 20
            EVENT_ANIMAL_DOG: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 21
            EVENT_ANIMAL_CAT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 22
            EVENT_ANIMAL: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 23
            EVENT_MAGIC_MOMENT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 24
            EVENT_CTD: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 25
            EVENT_CMDT: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 26
            EVENT_TALKBACK: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 27
            EVENT_SECURITY_ALARM: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 28
            EVENT_NOT_A_FACE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 29
            EVENT_DOOR_OPEN: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 30
            EVENT_DOOR_CLOSE: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 31
            EVENT_DOOR_AJAR: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 32
            EVENT_UNRECOGNIZED: CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType  # 33

            @_typing.final
            class CameraEvent(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                EVENTID_FIELD_NUMBER: _builtins.int
                STARTTIME_FIELD_NUMBER: _builtins.int
                ENDTIME_FIELD_NUMBER: _builtins.int
                EVENTTYPE_FIELD_NUMBER: _builtins.int
                FAMILIARFACE_FIELD_NUMBER: _builtins.int
                ACTIVITYZONE_FIELD_NUMBER: _builtins.int
                EVENTURLS_FIELD_NUMBER: _builtins.int
                eventId: _builtins.str
                @_builtins.property
                def startTime(self) -> _timestamp_pb2.Timestamp: ...
                @_builtins.property
                def endTime(self) -> _timestamp_pb2.Timestamp: ...
                @_builtins.property
                def eventType(self) -> _containers.RepeatedScalarFieldContainer[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType]: ...
                @_builtins.property
                def familiarFace(self) -> Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.FamiliarFace: ...
                @_builtins.property
                def activityZone(self) -> _containers.RepeatedCompositeFieldContainer[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.ActivityZone]: ...
                @_builtins.property
                def eventUrls(self) -> Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventUrls: ...
                def __init__(
                    self,
                    *,
                    eventId: _builtins.str = ...,
                    startTime: _timestamp_pb2.Timestamp | None = ...,
                    endTime: _timestamp_pb2.Timestamp | None = ...,
                    eventType: _abc.Iterable[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventType.ValueType] | None = ...,
                    familiarFace: Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.FamiliarFace | None = ...,
                    activityZone: _abc.Iterable[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.ActivityZone] | None = ...,
                    eventUrls: Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventUrls | None = ...,
                ) -> None: ...
                _HasFieldArgType: _TypeAlias = _typing.Literal["endTime", b"endTime", "eventUrls", b"eventUrls", "familiarFace", b"familiarFace", "startTime", b"startTime"]  # noqa: Y015
                def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["activityZone", b"activityZone", "endTime", b"endTime", "eventId", b"eventId", "eventType", b"eventType", "eventUrls", b"eventUrls", "familiarFace", b"familiarFace", "startTime", b"startTime"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            @_typing.final
            class EventUrls(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                SNAPSHOTURL_FIELD_NUMBER: _builtins.int
                CLIPURL_FIELD_NUMBER: _builtins.int
                snapshotUrl: _builtins.str
                @_builtins.property
                def clipUrl(self) -> _wrappers_pb2.StringValue: ...
                def __init__(
                    self,
                    *,
                    snapshotUrl: _builtins.str = ...,
                    clipUrl: _wrappers_pb2.StringValue | None = ...,
                ) -> None: ...
                _HasFieldArgType: _TypeAlias = _typing.Literal["clipUrl", b"clipUrl"]  # noqa: Y015
                def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["clipUrl", b"clipUrl", "snapshotUrl", b"snapshotUrl"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            @_typing.final
            class FamiliarFace(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                FACEID_FIELD_NUMBER: _builtins.int
                FACENAME_FIELD_NUMBER: _builtins.int
                FACEPICTUREURL_FIELD_NUMBER: _builtins.int
                faceId: _builtins.str
                faceName: _builtins.str
                facePictureUrl: _builtins.str
                def __init__(
                    self,
                    *,
                    faceId: _builtins.str = ...,
                    faceName: _builtins.str = ...,
                    facePictureUrl: _builtins.str = ...,
                ) -> None: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["faceId", b"faceId", "faceName", b"faceName", "facePictureUrl", b"facePictureUrl"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            @_typing.final
            class ActivityZone(_message.Message):
                DESCRIPTOR: _descriptor.Descriptor

                ZONEINDEX_FIELD_NUMBER: _builtins.int
                NAME_FIELD_NUMBER: _builtins.int
                INTERNALINDEX_FIELD_NUMBER: _builtins.int
                zoneIndex: _builtins.int
                name: _builtins.str
                internalIndex: _builtins.int
                def __init__(
                    self,
                    *,
                    zoneIndex: _builtins.int = ...,
                    name: _builtins.str = ...,
                    internalIndex: _builtins.int = ...,
                ) -> None: ...
                _ClearFieldArgType: _TypeAlias = _typing.Literal["internalIndex", b"internalIndex", "name", b"name", "zoneIndex", b"zoneIndex"]  # noqa: Y015
                def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

            UUID_FIELD_NUMBER: _builtins.int
            STARTTIME_FIELD_NUMBER: _builtins.int
            ENDTIME_FIELD_NUMBER: _builtins.int
            CAMERAEVENT_FIELD_NUMBER: _builtins.int
            ACTIVITYZONE_FIELD_NUMBER: _builtins.int
            FAMILIARFACE_FIELD_NUMBER: _builtins.int
            TIMEWINDOWURLS_FIELD_NUMBER: _builtins.int
            UNKNOWN_FIELD_NUMBER: _builtins.int
            uuid: _builtins.str
            unknown: _builtins.int
            @_builtins.property
            def startTime(self) -> _timestamp_pb2.Timestamp: ...
            @_builtins.property
            def endTime(self) -> _timestamp_pb2.Timestamp: ...
            @_builtins.property
            def cameraEvent(self) -> _containers.RepeatedCompositeFieldContainer[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.CameraEvent]: ...
            @_builtins.property
            def activityZone(self) -> _containers.RepeatedCompositeFieldContainer[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.ActivityZone]: ...
            @_builtins.property
            def familiarFace(self) -> Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.FamiliarFace: ...
            @_builtins.property
            def timeWindowUrls(self) -> Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventUrls: ...
            def __init__(
                self,
                *,
                uuid: _builtins.str = ...,
                startTime: _timestamp_pb2.Timestamp | None = ...,
                endTime: _timestamp_pb2.Timestamp | None = ...,
                cameraEvent: _abc.Iterable[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.CameraEvent] | None = ...,
                activityZone: _abc.Iterable[Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.ActivityZone] | None = ...,
                familiarFace: Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.FamiliarFace | None = ...,
                timeWindowUrls: Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow.EventUrls | None = ...,
                unknown: _builtins.int = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["endTime", b"endTime", "familiarFace", b"familiarFace", "startTime", b"startTime", "timeWindowUrls", b"timeWindowUrls"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["activityZone", b"activityZone", "cameraEvent", b"cameraEvent", "endTime", b"endTime", "familiarFace", b"familiarFace", "startTime", b"startTime", "timeWindowUrls", b"timeWindowUrls", "unknown", b"unknown", "uuid", b"uuid"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        CAMERAEVENTWINDOW_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def cameraEventWindow(self) -> Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow: ...
        def __init__(
            self,
            *,
            cameraEventWindow: Global___CameraObservationHistoryTrait.CameraObservationHistoryResponse.CameraEventTimeWindow | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["cameraEventWindow", b"cameraEventWindow"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["cameraEventWindow", b"cameraEventWindow"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___CameraObservationHistoryTrait: _TypeAlias = CameraObservationHistoryTrait  # noqa: Y015

@_typing.final
class EnergyHistoryTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _LegacyEnergyWinner:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LegacyEnergyWinnerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EnergyHistoryTrait._LegacyEnergyWinner.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LEGACY_ENERGY_WINNER_UNSPECIFIED: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 0
        LEGACY_ENERGY_WINNER_USER: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 1
        LEGACY_ENERGY_WINNER_WEATHER: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 2
        LEGACY_ENERGY_WINNER_AWAY: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 3
        LEGACY_ENERGY_WINNER_AUTO_AWAY: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 4
        LEGACY_ENERGY_WINNER_TUNE_UP: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 5
        LEGACY_ENERGY_WINNER_AUTO_DEHUM: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 6
        LEGACY_ENERGY_WINNER_DEMAND_RESPONSE: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 7
        LEGACY_ENERGY_WINNER_TIME_OF_USE: EnergyHistoryTrait._LegacyEnergyWinner.ValueType  # 8

    class LegacyEnergyWinner(_LegacyEnergyWinner, metaclass=_LegacyEnergyWinnerEnumTypeWrapper): ...
    LEGACY_ENERGY_WINNER_UNSPECIFIED: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 0
    LEGACY_ENERGY_WINNER_USER: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 1
    LEGACY_ENERGY_WINNER_WEATHER: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 2
    LEGACY_ENERGY_WINNER_AWAY: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 3
    LEGACY_ENERGY_WINNER_AUTO_AWAY: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 4
    LEGACY_ENERGY_WINNER_TUNE_UP: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 5
    LEGACY_ENERGY_WINNER_AUTO_DEHUM: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 6
    LEGACY_ENERGY_WINNER_DEMAND_RESPONSE: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 7
    LEGACY_ENERGY_WINNER_TIME_OF_USE: EnergyHistoryTrait.LegacyEnergyWinner.ValueType  # 8

    class _LegacySetPointType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LegacySetPointTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EnergyHistoryTrait._LegacySetPointType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LEGACY_SET_POINT_TYPE_UNSPECIFIED: EnergyHistoryTrait._LegacySetPointType.ValueType  # 0
        LEGACY_SET_POINT_TYPE_HEAT: EnergyHistoryTrait._LegacySetPointType.ValueType  # 1
        LEGACY_SET_POINT_TYPE_COOL: EnergyHistoryTrait._LegacySetPointType.ValueType  # 2
        LEGACY_SET_POINT_TYPE_RANGE: EnergyHistoryTrait._LegacySetPointType.ValueType  # 3
        LEGACY_SET_POINT_TYPE_EMERGENCY_HEAT: EnergyHistoryTrait._LegacySetPointType.ValueType  # 4

    class LegacySetPointType(_LegacySetPointType, metaclass=_LegacySetPointTypeEnumTypeWrapper): ...
    LEGACY_SET_POINT_TYPE_UNSPECIFIED: EnergyHistoryTrait.LegacySetPointType.ValueType  # 0
    LEGACY_SET_POINT_TYPE_HEAT: EnergyHistoryTrait.LegacySetPointType.ValueType  # 1
    LEGACY_SET_POINT_TYPE_COOL: EnergyHistoryTrait.LegacySetPointType.ValueType  # 2
    LEGACY_SET_POINT_TYPE_RANGE: EnergyHistoryTrait.LegacySetPointType.ValueType  # 3
    LEGACY_SET_POINT_TYPE_EMERGENCY_HEAT: EnergyHistoryTrait.LegacySetPointType.ValueType  # 4

    class _LegacyEventType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LegacyEventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EnergyHistoryTrait._LegacyEventType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LEGACY_EVENT_TYPE_UNSPECIFIED: EnergyHistoryTrait._LegacyEventType.ValueType  # 0
        LEGACY_EVENT_TYPE_HEAT: EnergyHistoryTrait._LegacyEventType.ValueType  # 1
        LEGACY_EVENT_TYPE_COOL: EnergyHistoryTrait._LegacyEventType.ValueType  # 2
        LEGACY_EVENT_TYPE_RANGE: EnergyHistoryTrait._LegacyEventType.ValueType  # 3
        LEGACY_EVENT_TYPE_AWAY: EnergyHistoryTrait._LegacyEventType.ValueType  # 4
        LEGACY_EVENT_TYPE_AUTOAWAY: EnergyHistoryTrait._LegacyEventType.ValueType  # 5
        LEGACY_EVENT_TYPE_OFF: EnergyHistoryTrait._LegacyEventType.ValueType  # 6
        LEGACY_EVENT_TYPE_ON: EnergyHistoryTrait._LegacyEventType.ValueType  # 8
        LEGACY_EVENT_TYPE_EMERGENCY_HEAT: EnergyHistoryTrait._LegacyEventType.ValueType  # 9
        LEGACY_EVENT_TYPE_SUNLIGHT_CORRECTION: EnergyHistoryTrait._LegacyEventType.ValueType  # 10

    class LegacyEventType(_LegacyEventType, metaclass=_LegacyEventTypeEnumTypeWrapper): ...
    LEGACY_EVENT_TYPE_UNSPECIFIED: EnergyHistoryTrait.LegacyEventType.ValueType  # 0
    LEGACY_EVENT_TYPE_HEAT: EnergyHistoryTrait.LegacyEventType.ValueType  # 1
    LEGACY_EVENT_TYPE_COOL: EnergyHistoryTrait.LegacyEventType.ValueType  # 2
    LEGACY_EVENT_TYPE_RANGE: EnergyHistoryTrait.LegacyEventType.ValueType  # 3
    LEGACY_EVENT_TYPE_AWAY: EnergyHistoryTrait.LegacyEventType.ValueType  # 4
    LEGACY_EVENT_TYPE_AUTOAWAY: EnergyHistoryTrait.LegacyEventType.ValueType  # 5
    LEGACY_EVENT_TYPE_OFF: EnergyHistoryTrait.LegacyEventType.ValueType  # 6
    LEGACY_EVENT_TYPE_ON: EnergyHistoryTrait.LegacyEventType.ValueType  # 8
    LEGACY_EVENT_TYPE_EMERGENCY_HEAT: EnergyHistoryTrait.LegacyEventType.ValueType  # 9
    LEGACY_EVENT_TYPE_SUNLIGHT_CORRECTION: EnergyHistoryTrait.LegacyEventType.ValueType  # 10

    class _LegacyTouchedWhere:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LegacyTouchedWhereEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EnergyHistoryTrait._LegacyTouchedWhere.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LEGACY_TOUCHED_WHERE_UNSPECIFIED: EnergyHistoryTrait._LegacyTouchedWhere.ValueType  # 0
        LEGACY_TOUCHED_WHERE_SCHEDULE: EnergyHistoryTrait._LegacyTouchedWhere.ValueType  # 1
        LEGACY_TOUCHED_WHERE_ADHOC: EnergyHistoryTrait._LegacyTouchedWhere.ValueType  # 2

    class LegacyTouchedWhere(_LegacyTouchedWhere, metaclass=_LegacyTouchedWhereEnumTypeWrapper): ...
    LEGACY_TOUCHED_WHERE_UNSPECIFIED: EnergyHistoryTrait.LegacyTouchedWhere.ValueType  # 0
    LEGACY_TOUCHED_WHERE_SCHEDULE: EnergyHistoryTrait.LegacyTouchedWhere.ValueType  # 1
    LEGACY_TOUCHED_WHERE_ADHOC: EnergyHistoryTrait.LegacyTouchedWhere.ValueType  # 2

    @_typing.final
    class LegacyEnergyHistoryRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        QUERYSTARTTIME_FIELD_NUMBER: _builtins.int
        QUERYENDTIME_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def queryStartTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def queryEndTime(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            queryStartTime: _timestamp_pb2.Timestamp | None = ...,
            queryEndTime: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["queryEndTime", b"queryEndTime", "queryStartTime", b"queryStartTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["queryEndTime", b"queryEndTime", "queryStartTime", b"queryStartTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEnergyHistoryResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DAYS_FIELD_NUMBER: _builtins.int
        RECENTMAXUSEDSECONDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def days(self) -> _containers.RepeatedCompositeFieldContainer[Global___EnergyHistoryTrait.LegacyDayUsage]: ...
        @_builtins.property
        def recentMaxUsedSeconds(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            days: _abc.Iterable[Global___EnergyHistoryTrait.LegacyDayUsage] | None = ...,
            recentMaxUsedSeconds: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["recentMaxUsedSeconds", b"recentMaxUsedSeconds"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["days", b"days", "recentMaxUsedSeconds", b"recentMaxUsedSeconds"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyDayUsage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DAYSTART_FIELD_NUMBER: _builtins.int
        DAYEND_FIELD_NUMBER: _builtins.int
        TOTALHEATINGSECONDS_FIELD_NUMBER: _builtins.int
        TOTALCOOLINGSECONDS_FIELD_NUMBER: _builtins.int
        TOTALFANCOOLINGSECONDS_FIELD_NUMBER: _builtins.int
        TOTALHUMIDIFIERSECONDS_FIELD_NUMBER: _builtins.int
        TOTALDEHUMIDIFIERSECONDS_FIELD_NUMBER: _builtins.int
        ENERGYWINNER_FIELD_NUMBER: _builtins.int
        ENERGYLEAF_FIELD_NUMBER: _builtins.int
        RECENTAVERAGEUSEDSECONDS_FIELD_NUMBER: _builtins.int
        SECONDSUSAGEOVERAVERAGE_FIELD_NUMBER: _builtins.int
        SYSTEMCAPABILITIES_FIELD_NUMBER: _builtins.int
        CYCLESINCOMPLETE_FIELD_NUMBER: _builtins.int
        CYCLES_FIELD_NUMBER: _builtins.int
        EVENTSINCOMPLETE_FIELD_NUMBER: _builtins.int
        USAGEEVENTS_FIELD_NUMBER: _builtins.int
        RATES_FIELD_NUMBER: _builtins.int
        energyWinner: Global___EnergyHistoryTrait.LegacyEnergyWinner.ValueType
        cyclesIncomplete: _builtins.bool
        eventsIncomplete: _builtins.bool
        @_builtins.property
        def dayStart(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def dayEnd(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def totalHeatingSeconds(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def totalCoolingSeconds(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def totalFanCoolingSeconds(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def totalHumidifierSeconds(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def totalDehumidifierSeconds(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def energyLeaf(self) -> _wrappers_pb2.BoolValue: ...
        @_builtins.property
        def recentAverageUsedSeconds(self) -> _wrappers_pb2.Int32Value: ...
        @_builtins.property
        def secondsUsageOverAverage(self) -> _wrappers_pb2.Int32Value: ...
        @_builtins.property
        def systemCapabilities(self) -> Global___EnergyHistoryTrait.LegacySystemCapabilities: ...
        @_builtins.property
        def cycles(self) -> _containers.RepeatedCompositeFieldContainer[Global___EnergyHistoryTrait.LegacyHVACCycle]: ...
        @_builtins.property
        def usageEvents(self) -> _containers.RepeatedCompositeFieldContainer[Global___EnergyHistoryTrait.LegacyHVACUsage]: ...
        @_builtins.property
        def rates(self) -> _containers.RepeatedCompositeFieldContainer[Global___EnergyHistoryTrait.LegacyRatePlanChange]: ...
        def __init__(
            self,
            *,
            dayStart: _timestamp_pb2.Timestamp | None = ...,
            dayEnd: _timestamp_pb2.Timestamp | None = ...,
            totalHeatingSeconds: _duration_pb2.Duration | None = ...,
            totalCoolingSeconds: _duration_pb2.Duration | None = ...,
            totalFanCoolingSeconds: _duration_pb2.Duration | None = ...,
            totalHumidifierSeconds: _duration_pb2.Duration | None = ...,
            totalDehumidifierSeconds: _duration_pb2.Duration | None = ...,
            energyWinner: Global___EnergyHistoryTrait.LegacyEnergyWinner.ValueType = ...,
            energyLeaf: _wrappers_pb2.BoolValue | None = ...,
            recentAverageUsedSeconds: _wrappers_pb2.Int32Value | None = ...,
            secondsUsageOverAverage: _wrappers_pb2.Int32Value | None = ...,
            systemCapabilities: Global___EnergyHistoryTrait.LegacySystemCapabilities | None = ...,
            cyclesIncomplete: _builtins.bool = ...,
            cycles: _abc.Iterable[Global___EnergyHistoryTrait.LegacyHVACCycle] | None = ...,
            eventsIncomplete: _builtins.bool = ...,
            usageEvents: _abc.Iterable[Global___EnergyHistoryTrait.LegacyHVACUsage] | None = ...,
            rates: _abc.Iterable[Global___EnergyHistoryTrait.LegacyRatePlanChange] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["dayEnd", b"dayEnd", "dayStart", b"dayStart", "energyLeaf", b"energyLeaf", "recentAverageUsedSeconds", b"recentAverageUsedSeconds", "secondsUsageOverAverage", b"secondsUsageOverAverage", "systemCapabilities", b"systemCapabilities", "totalCoolingSeconds", b"totalCoolingSeconds", "totalDehumidifierSeconds", b"totalDehumidifierSeconds", "totalFanCoolingSeconds", b"totalFanCoolingSeconds", "totalHeatingSeconds", b"totalHeatingSeconds", "totalHumidifierSeconds", b"totalHumidifierSeconds"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["cycles", b"cycles", "cyclesIncomplete", b"cyclesIncomplete", "dayEnd", b"dayEnd", "dayStart", b"dayStart", "energyLeaf", b"energyLeaf", "energyWinner", b"energyWinner", "eventsIncomplete", b"eventsIncomplete", "rates", b"rates", "recentAverageUsedSeconds", b"recentAverageUsedSeconds", "secondsUsageOverAverage", b"secondsUsageOverAverage", "systemCapabilities", b"systemCapabilities", "totalCoolingSeconds", b"totalCoolingSeconds", "totalDehumidifierSeconds", b"totalDehumidifierSeconds", "totalFanCoolingSeconds", b"totalFanCoolingSeconds", "totalHeatingSeconds", b"totalHeatingSeconds", "totalHumidifierSeconds", b"totalHumidifierSeconds", "usageEvents", b"usageEvents"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyHVACCycle(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CYCLESTART_FIELD_NUMBER: _builtins.int
        DURATION_FIELD_NUMBER: _builtins.int
        ISCOMPLETE_FIELD_NUMBER: _builtins.int
        HEAT1_FIELD_NUMBER: _builtins.int
        HEAT2_FIELD_NUMBER: _builtins.int
        HEAT3_FIELD_NUMBER: _builtins.int
        HEATAUX_FIELD_NUMBER: _builtins.int
        ALTHEAT_FIELD_NUMBER: _builtins.int
        ALTHEAT2_FIELD_NUMBER: _builtins.int
        EMERGENCYHEAT_FIELD_NUMBER: _builtins.int
        COOL1_FIELD_NUMBER: _builtins.int
        COOL2_FIELD_NUMBER: _builtins.int
        COOL3_FIELD_NUMBER: _builtins.int
        FAN_FIELD_NUMBER: _builtins.int
        FANCOOLING_FIELD_NUMBER: _builtins.int
        HUMIDIFIER_FIELD_NUMBER: _builtins.int
        DEHUMIDIFIER_FIELD_NUMBER: _builtins.int
        AUTODEHUMDIFIER_FIELD_NUMBER: _builtins.int
        WATERHEATER_FIELD_NUMBER: _builtins.int
        isComplete: _builtins.bool
        heat1: _builtins.bool
        heat2: _builtins.bool
        heat3: _builtins.bool
        heatAux: _builtins.bool
        altHeat: _builtins.bool
        altHeat2: _builtins.bool
        emergencyHeat: _builtins.bool
        cool1: _builtins.bool
        cool2: _builtins.bool
        cool3: _builtins.bool
        fan: _builtins.bool
        fanCooling: _builtins.bool
        humidifier: _builtins.bool
        dehumidifier: _builtins.bool
        autoDehumdifier: _builtins.bool
        waterHeater: _builtins.bool
        @_builtins.property
        def cycleStart(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def duration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            cycleStart: _timestamp_pb2.Timestamp | None = ...,
            duration: _duration_pb2.Duration | None = ...,
            isComplete: _builtins.bool = ...,
            heat1: _builtins.bool = ...,
            heat2: _builtins.bool = ...,
            heat3: _builtins.bool = ...,
            heatAux: _builtins.bool = ...,
            altHeat: _builtins.bool = ...,
            altHeat2: _builtins.bool = ...,
            emergencyHeat: _builtins.bool = ...,
            cool1: _builtins.bool = ...,
            cool2: _builtins.bool = ...,
            cool3: _builtins.bool = ...,
            fan: _builtins.bool = ...,
            fanCooling: _builtins.bool = ...,
            humidifier: _builtins.bool = ...,
            dehumidifier: _builtins.bool = ...,
            autoDehumdifier: _builtins.bool = ...,
            waterHeater: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["cycleStart", b"cycleStart", "duration", b"duration"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["altHeat", b"altHeat", "altHeat2", b"altHeat2", "autoDehumdifier", b"autoDehumdifier", "cool1", b"cool1", "cool2", b"cool2", "cool3", b"cool3", "cycleStart", b"cycleStart", "dehumidifier", b"dehumidifier", "duration", b"duration", "emergencyHeat", b"emergencyHeat", "fan", b"fan", "fanCooling", b"fanCooling", "heat1", b"heat1", "heat2", b"heat2", "heat3", b"heat3", "heatAux", b"heatAux", "humidifier", b"humidifier", "isComplete", b"isComplete", "waterHeater", b"waterHeater"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacySystemCapabilities(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        HASSTAGE1COOL_FIELD_NUMBER: _builtins.int
        HASSTAGE2COOL_FIELD_NUMBER: _builtins.int
        HASSTAGE3COOL_FIELD_NUMBER: _builtins.int
        HASSTAGE1HEAT_FIELD_NUMBER: _builtins.int
        HASSTAGE2HEAT_FIELD_NUMBER: _builtins.int
        HASSTAGE3HEAT_FIELD_NUMBER: _builtins.int
        HASSTAGE1ALTERNATEHEAT_FIELD_NUMBER: _builtins.int
        HASSTAGE2ALTERNATEHEAT_FIELD_NUMBER: _builtins.int
        HASHUMIDIFIER_FIELD_NUMBER: _builtins.int
        HASDEHUMIDIFIER_FIELD_NUMBER: _builtins.int
        HASDUALFUEL_FIELD_NUMBER: _builtins.int
        HASAUXHEAT_FIELD_NUMBER: _builtins.int
        HASEMERGENCYHEAT_FIELD_NUMBER: _builtins.int
        HASAIRFILTER_FIELD_NUMBER: _builtins.int
        HASFOSSILFUEL_FIELD_NUMBER: _builtins.int
        HASHOTWATERCONTROL_FIELD_NUMBER: _builtins.int
        HASHEATPUMP_FIELD_NUMBER: _builtins.int
        HASHOTWATERTEMPERATURE_FIELD_NUMBER: _builtins.int
        HASFAN_FIELD_NUMBER: _builtins.int
        hasStage1Cool: _builtins.bool
        hasStage2Cool: _builtins.bool
        hasStage3Cool: _builtins.bool
        hasStage1Heat: _builtins.bool
        hasStage2Heat: _builtins.bool
        hasStage3Heat: _builtins.bool
        hasStage1AlternateHeat: _builtins.bool
        hasStage2AlternateHeat: _builtins.bool
        hasHumidifier: _builtins.bool
        hasDehumidifier: _builtins.bool
        hasDualFuel: _builtins.bool
        hasAuxHeat: _builtins.bool
        hasEmergencyHeat: _builtins.bool
        hasAirFilter: _builtins.bool
        hasFossilFuel: _builtins.bool
        hasHotWaterControl: _builtins.bool
        hasHeatPump: _builtins.bool
        hasHotWaterTemperature: _builtins.bool
        hasFan: _builtins.bool
        def __init__(
            self,
            *,
            hasStage1Cool: _builtins.bool = ...,
            hasStage2Cool: _builtins.bool = ...,
            hasStage3Cool: _builtins.bool = ...,
            hasStage1Heat: _builtins.bool = ...,
            hasStage2Heat: _builtins.bool = ...,
            hasStage3Heat: _builtins.bool = ...,
            hasStage1AlternateHeat: _builtins.bool = ...,
            hasStage2AlternateHeat: _builtins.bool = ...,
            hasHumidifier: _builtins.bool = ...,
            hasDehumidifier: _builtins.bool = ...,
            hasDualFuel: _builtins.bool = ...,
            hasAuxHeat: _builtins.bool = ...,
            hasEmergencyHeat: _builtins.bool = ...,
            hasAirFilter: _builtins.bool = ...,
            hasFossilFuel: _builtins.bool = ...,
            hasHotWaterControl: _builtins.bool = ...,
            hasHeatPump: _builtins.bool = ...,
            hasHotWaterTemperature: _builtins.bool = ...,
            hasFan: _builtins.bool = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["hasAirFilter", b"hasAirFilter", "hasAuxHeat", b"hasAuxHeat", "hasDehumidifier", b"hasDehumidifier", "hasDualFuel", b"hasDualFuel", "hasEmergencyHeat", b"hasEmergencyHeat", "hasFan", b"hasFan", "hasFossilFuel", b"hasFossilFuel", "hasHeatPump", b"hasHeatPump", "hasHotWaterControl", b"hasHotWaterControl", "hasHotWaterTemperature", b"hasHotWaterTemperature", "hasHumidifier", b"hasHumidifier", "hasStage1AlternateHeat", b"hasStage1AlternateHeat", "hasStage1Cool", b"hasStage1Cool", "hasStage1Heat", b"hasStage1Heat", "hasStage2AlternateHeat", b"hasStage2AlternateHeat", "hasStage2Cool", b"hasStage2Cool", "hasStage2Heat", b"hasStage2Heat", "hasStage3Cool", b"hasStage3Cool", "hasStage3Heat", b"hasStage3Heat"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyRatePlanChange(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TIMESTAMP_FIELD_NUMBER: _builtins.int
        RATEPLANSTART_FIELD_NUMBER: _builtins.int
        RATEPLANEND_FIELD_NUMBER: _builtins.int
        TIERLEVEL_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def ratePlanStart(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def ratePlanEnd(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def tierLevel(self) -> _wrappers_pb2.UInt32Value: ...
        def __init__(
            self,
            *,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
            ratePlanStart: _timestamp_pb2.Timestamp | None = ...,
            ratePlanEnd: _timestamp_pb2.Timestamp | None = ...,
            tierLevel: _wrappers_pb2.UInt32Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["ratePlanEnd", b"ratePlanEnd", "ratePlanStart", b"ratePlanStart", "tierLevel", b"tierLevel", "timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["ratePlanEnd", b"ratePlanEnd", "ratePlanStart", b"ratePlanStart", "tierLevel", b"tierLevel", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyHVACUsage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EVENTSTART_FIELD_NUMBER: _builtins.int
        TIMEZONEOFFSET_FIELD_NUMBER: _builtins.int
        DURATION_FIELD_NUMBER: _builtins.int
        CONTINUATION_FIELD_NUMBER: _builtins.int
        EVENTTYPE_FIELD_NUMBER: _builtins.int
        ON_FIELD_NUMBER: _builtins.int
        OFF_FIELD_NUMBER: _builtins.int
        ECOAWAY_FIELD_NUMBER: _builtins.int
        ECOAUTOAWAY_FIELD_NUMBER: _builtins.int
        SUNLIGHTCORRECTION_FIELD_NUMBER: _builtins.int
        SETPOINT_FIELD_NUMBER: _builtins.int
        timezoneOffset: _builtins.int
        continuation: _builtins.bool
        eventType: Global___EnergyHistoryTrait.LegacyEventType.ValueType
        @_builtins.property
        def eventStart(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def duration(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def on(self) -> Global___EnergyHistoryTrait.LegacyEventOnMode: ...
        @_builtins.property
        def off(self) -> Global___EnergyHistoryTrait.LegacyEventOffMode: ...
        @_builtins.property
        def ecoAway(self) -> Global___EnergyHistoryTrait.LegacyEventEcoAwayMode: ...
        @_builtins.property
        def ecoAutoAway(self) -> Global___EnergyHistoryTrait.LegacyEventEcoAutoAwayMode: ...
        @_builtins.property
        def sunlightCorrection(self) -> Global___EnergyHistoryTrait.LegacyEventSunlightCorrection: ...
        @_builtins.property
        def setPoint(self) -> Global___EnergyHistoryTrait.LegacyEventSetPoint: ...
        def __init__(
            self,
            *,
            eventStart: _timestamp_pb2.Timestamp | None = ...,
            timezoneOffset: _builtins.int = ...,
            duration: _duration_pb2.Duration | None = ...,
            continuation: _builtins.bool = ...,
            eventType: Global___EnergyHistoryTrait.LegacyEventType.ValueType = ...,
            on: Global___EnergyHistoryTrait.LegacyEventOnMode | None = ...,
            off: Global___EnergyHistoryTrait.LegacyEventOffMode | None = ...,
            ecoAway: Global___EnergyHistoryTrait.LegacyEventEcoAwayMode | None = ...,
            ecoAutoAway: Global___EnergyHistoryTrait.LegacyEventEcoAutoAwayMode | None = ...,
            sunlightCorrection: Global___EnergyHistoryTrait.LegacyEventSunlightCorrection | None = ...,
            setPoint: Global___EnergyHistoryTrait.LegacyEventSetPoint | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["duration", b"duration", "ecoAutoAway", b"ecoAutoAway", "ecoAway", b"ecoAway", "eventStart", b"eventStart", "off", b"off", "on", b"on", "setPoint", b"setPoint", "sunlightCorrection", b"sunlightCorrection"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["continuation", b"continuation", "duration", b"duration", "ecoAutoAway", b"ecoAutoAway", "ecoAway", b"ecoAway", "eventStart", b"eventStart", "eventType", b"eventType", "off", b"off", "on", b"on", "setPoint", b"setPoint", "sunlightCorrection", b"sunlightCorrection", "timezoneOffset", b"timezoneOffset"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEventOnMode(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EVENTSOURCE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def eventSource(self) -> Global___EnergyHistoryTrait.LegacyEventSource: ...
        def __init__(
            self,
            *,
            eventSource: Global___EnergyHistoryTrait.LegacyEventSource | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["eventSource", b"eventSource"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["eventSource", b"eventSource"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEventOffMode(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EVENTSOURCE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def eventSource(self) -> Global___EnergyHistoryTrait.LegacyEventSource: ...
        def __init__(
            self,
            *,
            eventSource: Global___EnergyHistoryTrait.LegacyEventSource | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["eventSource", b"eventSource"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["eventSource", b"eventSource"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEventEcoAwayMode(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        HEATINGTARGET_FIELD_NUMBER: _builtins.int
        COOLINGTARGET_FIELD_NUMBER: _builtins.int
        EVENTSOURCE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def heatingTarget(self) -> _hvac_pb2.HvacControl.TemperatureThreshold: ...
        @_builtins.property
        def coolingTarget(self) -> _hvac_pb2.HvacControl.TemperatureThreshold: ...
        @_builtins.property
        def eventSource(self) -> Global___EnergyHistoryTrait.LegacyEventSource: ...
        def __init__(
            self,
            *,
            heatingTarget: _hvac_pb2.HvacControl.TemperatureThreshold | None = ...,
            coolingTarget: _hvac_pb2.HvacControl.TemperatureThreshold | None = ...,
            eventSource: Global___EnergyHistoryTrait.LegacyEventSource | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["coolingTarget", b"coolingTarget", "eventSource", b"eventSource", "heatingTarget", b"heatingTarget"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["coolingTarget", b"coolingTarget", "eventSource", b"eventSource", "heatingTarget", b"heatingTarget"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEventEcoAutoAwayMode(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        HEATINGTARGET_FIELD_NUMBER: _builtins.int
        COOLINGTARGET_FIELD_NUMBER: _builtins.int
        EVENTSOURCE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def heatingTarget(self) -> _hvac_pb2.HvacControl.TemperatureThreshold: ...
        @_builtins.property
        def coolingTarget(self) -> _hvac_pb2.HvacControl.TemperatureThreshold: ...
        @_builtins.property
        def eventSource(self) -> Global___EnergyHistoryTrait.LegacyEventSource: ...
        def __init__(
            self,
            *,
            heatingTarget: _hvac_pb2.HvacControl.TemperatureThreshold | None = ...,
            coolingTarget: _hvac_pb2.HvacControl.TemperatureThreshold | None = ...,
            eventSource: Global___EnergyHistoryTrait.LegacyEventSource | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["coolingTarget", b"coolingTarget", "eventSource", b"eventSource", "heatingTarget", b"heatingTarget"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["coolingTarget", b"coolingTarget", "eventSource", b"eventSource", "heatingTarget", b"heatingTarget"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEventSunlightCorrection(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EVENTSOURCE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def eventSource(self) -> Global___EnergyHistoryTrait.LegacyEventSource: ...
        def __init__(
            self,
            *,
            eventSource: Global___EnergyHistoryTrait.LegacyEventSource | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["eventSource", b"eventSource"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["eventSource", b"eventSource"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEventSetPoint(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SETPOINTTYPE_FIELD_NUMBER: _builtins.int
        SCHEDULETYPE_FIELD_NUMBER: _builtins.int
        HEATINGTARGET_FIELD_NUMBER: _builtins.int
        COOLINGTARGET_FIELD_NUMBER: _builtins.int
        ACTOR_FIELD_NUMBER: _builtins.int
        TOUCHEDWHEN_FIELD_NUMBER: _builtins.int
        TOUCHEDTIMEZONEOFFSET_FIELD_NUMBER: _builtins.int
        TOUCHEDWHERE_FIELD_NUMBER: _builtins.int
        TOUCHEDUSERID_FIELD_NUMBER: _builtins.int
        SCHEDULEDSTART_FIELD_NUMBER: _builtins.int
        SCHEDULEDDAY_FIELD_NUMBER: _builtins.int
        PREVIOUSEVENTTYPE_FIELD_NUMBER: _builtins.int
        SOURCE_FIELD_NUMBER: _builtins.int
        setPointType: Global___EnergyHistoryTrait.LegacySetPointType.ValueType
        scheduleType: _hvac_pb2.SetPointScheduleSettingsTrait.SetPointScheduleType.ValueType
        actor: _hvac_pb2.HvacActor.HvacActorMethod.ValueType
        touchedWhere: Global___EnergyHistoryTrait.LegacyTouchedWhere.ValueType
        previousEventType: Global___EnergyHistoryTrait.LegacyEventType.ValueType
        @_builtins.property
        def heatingTarget(self) -> _hvac_pb2.HvacControl.TemperatureThreshold: ...
        @_builtins.property
        def coolingTarget(self) -> _hvac_pb2.HvacControl.TemperatureThreshold: ...
        @_builtins.property
        def touchedWhen(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def touchedTimezoneOffset(self) -> _wrappers_pb2.Int32Value: ...
        @_builtins.property
        def touchedUserId(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def scheduledStart(self) -> _wrappers_pb2.UInt32Value: ...
        @_builtins.property
        def scheduledDay(self) -> _wrappers_pb2.UInt32Value: ...
        @_builtins.property
        def source(self) -> Global___EnergyHistoryTrait.LegacyEventSource: ...
        def __init__(
            self,
            *,
            setPointType: Global___EnergyHistoryTrait.LegacySetPointType.ValueType = ...,
            scheduleType: _hvac_pb2.SetPointScheduleSettingsTrait.SetPointScheduleType.ValueType = ...,
            heatingTarget: _hvac_pb2.HvacControl.TemperatureThreshold | None = ...,
            coolingTarget: _hvac_pb2.HvacControl.TemperatureThreshold | None = ...,
            actor: _hvac_pb2.HvacActor.HvacActorMethod.ValueType = ...,
            touchedWhen: _timestamp_pb2.Timestamp | None = ...,
            touchedTimezoneOffset: _wrappers_pb2.Int32Value | None = ...,
            touchedWhere: Global___EnergyHistoryTrait.LegacyTouchedWhere.ValueType = ...,
            touchedUserId: _wrappers_pb2.StringValue | None = ...,
            scheduledStart: _wrappers_pb2.UInt32Value | None = ...,
            scheduledDay: _wrappers_pb2.UInt32Value | None = ...,
            previousEventType: Global___EnergyHistoryTrait.LegacyEventType.ValueType = ...,
            source: Global___EnergyHistoryTrait.LegacyEventSource | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["coolingTarget", b"coolingTarget", "heatingTarget", b"heatingTarget", "scheduledDay", b"scheduledDay", "scheduledStart", b"scheduledStart", "source", b"source", "touchedTimezoneOffset", b"touchedTimezoneOffset", "touchedUserId", b"touchedUserId", "touchedWhen", b"touchedWhen"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "coolingTarget", b"coolingTarget", "heatingTarget", b"heatingTarget", "previousEventType", b"previousEventType", "scheduleType", b"scheduleType", "scheduledDay", b"scheduledDay", "scheduledStart", b"scheduledStart", "setPointType", b"setPointType", "source", b"source", "touchedTimezoneOffset", b"touchedTimezoneOffset", "touchedUserId", b"touchedUserId", "touchedWhen", b"touchedWhen", "touchedWhere", b"touchedWhere"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LegacyEventSource(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ACTOR_FIELD_NUMBER: _builtins.int
        TOUCHEDWHERE_FIELD_NUMBER: _builtins.int
        USERNAME_FIELD_NUMBER: _builtins.int
        actor: _hvac_pb2.HvacActor.HvacActorMethod.ValueType
        touchedWhere: Global___EnergyHistoryTrait.LegacyTouchedWhere.ValueType
        @_builtins.property
        def userName(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            actor: _hvac_pb2.HvacActor.HvacActorMethod.ValueType = ...,
            touchedWhere: Global___EnergyHistoryTrait.LegacyTouchedWhere.ValueType = ...,
            userName: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["userName", b"userName"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "touchedWhere", b"touchedWhere", "userName", b"userName"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___EnergyHistoryTrait: _TypeAlias = EnergyHistoryTrait  # noqa: Y015

@_typing.final
class OccupancyHistoryTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ImplicitChangeReason:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ImplicitChangeReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[OccupancyHistoryTrait._ImplicitChangeReason.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        IMPLICIT_CHANGE_REASON_UNSPECIFIED: OccupancyHistoryTrait._ImplicitChangeReason.ValueType  # 0
        IMPLICIT_CHANGE_REASON_ARM: OccupancyHistoryTrait._ImplicitChangeReason.ValueType  # 1
        IMPLICIT_CHANGE_REASON_DISARM: OccupancyHistoryTrait._ImplicitChangeReason.ValueType  # 2
        IMPLICIT_CHANGE_REASON_UNLOCK: OccupancyHistoryTrait._ImplicitChangeReason.ValueType  # 3

    class ImplicitChangeReason(_ImplicitChangeReason, metaclass=_ImplicitChangeReasonEnumTypeWrapper): ...
    IMPLICIT_CHANGE_REASON_UNSPECIFIED: OccupancyHistoryTrait.ImplicitChangeReason.ValueType  # 0
    IMPLICIT_CHANGE_REASON_ARM: OccupancyHistoryTrait.ImplicitChangeReason.ValueType  # 1
    IMPLICIT_CHANGE_REASON_DISARM: OccupancyHistoryTrait.ImplicitChangeReason.ValueType  # 2
    IMPLICIT_CHANGE_REASON_UNLOCK: OccupancyHistoryTrait.ImplicitChangeReason.ValueType  # 3

    @_typing.final
    class FindOccupancyEventListRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        QUERYSTARTTIME_FIELD_NUMBER: _builtins.int
        QUERYENDTIME_FIELD_NUMBER: _builtins.int
        FENCEID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def queryStartTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def queryEndTime(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def fenceId(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            queryStartTime: _timestamp_pb2.Timestamp | None = ...,
            queryEndTime: _timestamp_pb2.Timestamp | None = ...,
            fenceId: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["fenceId", b"fenceId", "queryEndTime", b"queryEndTime", "queryStartTime", b"queryStartTime"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["fenceId", b"fenceId", "queryEndTime", b"queryEndTime", "queryStartTime", b"queryStartTime"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ExplicitStructureModeChange(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MODE_FIELD_NUMBER: _builtins.int
        USER_FIELD_NUMBER: _builtins.int
        WWNCLIENTID_FIELD_NUMBER: _builtins.int
        PRIORMODE_FIELD_NUMBER: _builtins.int
        mode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType
        priorMode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType
        @_builtins.property
        def user(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def wwnClientId(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            mode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType = ...,
            user: _common_pb2.ResourceId | None = ...,
            wwnClientId: _wrappers_pb2.StringValue | None = ...,
            priorMode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["user", b"user", "wwnClientId", b"wwnClientId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "priorMode", b"priorMode", "user", b"user", "wwnClientId", b"wwnClientId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ImplicitStructureModeChange(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MODE_FIELD_NUMBER: _builtins.int
        ACTOR_FIELD_NUMBER: _builtins.int
        REASON_FIELD_NUMBER: _builtins.int
        PRIORMODE_FIELD_NUMBER: _builtins.int
        mode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType
        reason: Global___OccupancyHistoryTrait.ImplicitChangeReason.ValueType
        priorMode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType
        @_builtins.property
        def actor(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            mode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType = ...,
            actor: _common_pb2.ResourceId | None = ...,
            reason: Global___OccupancyHistoryTrait.ImplicitChangeReason.ValueType = ...,
            priorMode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["actor", b"actor", "mode", b"mode", "priorMode", b"priorMode", "reason", b"reason"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class EstimatedOccupancyStructureModeChange(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MODE_FIELD_NUMBER: _builtins.int
        REASON_FIELD_NUMBER: _builtins.int
        WEAVEDEVICEID_FIELD_NUMBER: _builtins.int
        RTSSERIALNUMBER_FIELD_NUMBER: _builtins.int
        PRIORMODE_FIELD_NUMBER: _builtins.int
        mode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType
        reason: _occupancy_pb2.StructureModeTrait.StructureModeReason.ValueType
        priorMode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType
        @_builtins.property
        def weaveDeviceId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def rtsSerialNumber(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            mode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType = ...,
            reason: _occupancy_pb2.StructureModeTrait.StructureModeReason.ValueType = ...,
            weaveDeviceId: _common_pb2.ResourceId | None = ...,
            rtsSerialNumber: _wrappers_pb2.StringValue | None = ...,
            priorMode: _occupancy_pb2.StructureModeTrait.StructureMode.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["rtsSerialNumber", b"rtsSerialNumber", "weaveDeviceId", b"weaveDeviceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "priorMode", b"priorMode", "reason", b"reason", "rtsSerialNumber", b"rtsSerialNumber", "weaveDeviceId", b"weaveDeviceId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CombinedPresenceChange(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PRESENCE_FIELD_NUMBER: _builtins.int
        PRIORPRESENCE_FIELD_NUMBER: _builtins.int
        presence: _occupancy_pb2.StructureModeTrait.Presence.ValueType
        priorPresence: _occupancy_pb2.StructureModeTrait.Presence.ValueType
        def __init__(
            self,
            *,
            presence: _occupancy_pb2.StructureModeTrait.Presence.ValueType = ...,
            priorPresence: _occupancy_pb2.StructureModeTrait.Presence.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["presence", b"presence", "priorPresence", b"priorPresence"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class GeofenceStateChange(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GEOFENCESTATE_FIELD_NUMBER: _builtins.int
        USERID_FIELD_NUMBER: _builtins.int
        RTSDEVICEID_FIELD_NUMBER: _builtins.int
        WEAVEMOBILEDEVICEID_FIELD_NUMBER: _builtins.int
        ASSERTIONTIMESTAMP_FIELD_NUMBER: _builtins.int
        geofenceState: _occupancy_pb2.Geofencing.GeofenceState.ValueType
        @_builtins.property
        def userId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def rtsDeviceId(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def weaveMobileDeviceId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def assertionTimestamp(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            geofenceState: _occupancy_pb2.Geofencing.GeofenceState.ValueType = ...,
            userId: _common_pb2.ResourceId | None = ...,
            rtsDeviceId: _wrappers_pb2.StringValue | None = ...,
            weaveMobileDeviceId: _common_pb2.ResourceId | None = ...,
            assertionTimestamp: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["assertionTimestamp", b"assertionTimestamp", "rtsDeviceId", b"rtsDeviceId", "userId", b"userId", "weaveMobileDeviceId", b"weaveMobileDeviceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["assertionTimestamp", b"assertionTimestamp", "geofenceState", b"geofenceState", "rtsDeviceId", b"rtsDeviceId", "userId", b"userId", "weaveMobileDeviceId", b"weaveMobileDeviceId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class OccupancyHistoryRecord(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EVENTTIMESTAMP_FIELD_NUMBER: _builtins.int
        EXPLICITCHANGEEVENT_FIELD_NUMBER: _builtins.int
        IMPLICITCHANGEEVENT_FIELD_NUMBER: _builtins.int
        ESTIMATEDOCCUPANCYCHANGEEVENT_FIELD_NUMBER: _builtins.int
        PRESENCEEVENT_FIELD_NUMBER: _builtins.int
        GEOFENCEEVENT_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def eventTimestamp(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def explicitChangeEvent(self) -> Global___OccupancyHistoryTrait.ExplicitStructureModeChange: ...
        @_builtins.property
        def implicitChangeEvent(self) -> Global___OccupancyHistoryTrait.ImplicitStructureModeChange: ...
        @_builtins.property
        def estimatedOccupancyChangeEvent(self) -> Global___OccupancyHistoryTrait.EstimatedOccupancyStructureModeChange: ...
        @_builtins.property
        def presenceEvent(self) -> Global___OccupancyHistoryTrait.CombinedPresenceChange: ...
        @_builtins.property
        def geofenceEvent(self) -> Global___OccupancyHistoryTrait.GeofenceStateChange: ...
        def __init__(
            self,
            *,
            eventTimestamp: _timestamp_pb2.Timestamp | None = ...,
            explicitChangeEvent: Global___OccupancyHistoryTrait.ExplicitStructureModeChange | None = ...,
            implicitChangeEvent: Global___OccupancyHistoryTrait.ImplicitStructureModeChange | None = ...,
            estimatedOccupancyChangeEvent: Global___OccupancyHistoryTrait.EstimatedOccupancyStructureModeChange | None = ...,
            presenceEvent: Global___OccupancyHistoryTrait.CombinedPresenceChange | None = ...,
            geofenceEvent: Global___OccupancyHistoryTrait.GeofenceStateChange | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["estimatedOccupancyChangeEvent", b"estimatedOccupancyChangeEvent", "eventTimestamp", b"eventTimestamp", "explicitChangeEvent", b"explicitChangeEvent", "geofenceEvent", b"geofenceEvent", "implicitChangeEvent", b"implicitChangeEvent", "presenceEvent", b"presenceEvent"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["estimatedOccupancyChangeEvent", b"estimatedOccupancyChangeEvent", "eventTimestamp", b"eventTimestamp", "explicitChangeEvent", b"explicitChangeEvent", "geofenceEvent", b"geofenceEvent", "implicitChangeEvent", b"implicitChangeEvent", "presenceEvent", b"presenceEvent"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class FindOccupancyEventsResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RECORD_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def record(self) -> Global___OccupancyHistoryTrait.OccupancyHistoryRecord: ...
        def __init__(
            self,
            *,
            record: Global___OccupancyHistoryTrait.OccupancyHistoryRecord | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["record", b"record"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["record", b"record"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class FindOccupancyEventListResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESPONSES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def responses(self) -> _containers.RepeatedCompositeFieldContainer[Global___OccupancyHistoryTrait.FindOccupancyEventsResponse]: ...
        def __init__(
            self,
            *,
            responses: _abc.Iterable[Global___OccupancyHistoryTrait.FindOccupancyEventsResponse] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["responses", b"responses"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___OccupancyHistoryTrait: _TypeAlias = OccupancyHistoryTrait  # noqa: Y015
