"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...nest.trait import sensor_pb2 as _sensor_pb2
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SafetyAlarmTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _AlarmLevel:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AlarmLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SafetyAlarmTrait._AlarmLevel.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ALARM_LEVEL_UNSPECIFIED: SafetyAlarmTrait._AlarmLevel.ValueType  # 0
        ALARM_LEVEL_IDLE: SafetyAlarmTrait._AlarmLevel.ValueType  # 1
        ALARM_LEVEL_MONITOR: SafetyAlarmTrait._AlarmLevel.ValueType  # 2
        ALARM_LEVEL_MODERATE: SafetyAlarmTrait._AlarmLevel.ValueType  # 3
        ALARM_LEVEL_SUBSTANTIAL: SafetyAlarmTrait._AlarmLevel.ValueType  # 4
        ALARM_LEVEL_SEVERE: SafetyAlarmTrait._AlarmLevel.ValueType  # 5
        ALARM_LEVEL_CRITICAL: SafetyAlarmTrait._AlarmLevel.ValueType  # 6

    class AlarmLevel(_AlarmLevel, metaclass=_AlarmLevelEnumTypeWrapper): ...
    ALARM_LEVEL_UNSPECIFIED: SafetyAlarmTrait.AlarmLevel.ValueType  # 0
    ALARM_LEVEL_IDLE: SafetyAlarmTrait.AlarmLevel.ValueType  # 1
    ALARM_LEVEL_MONITOR: SafetyAlarmTrait.AlarmLevel.ValueType  # 2
    ALARM_LEVEL_MODERATE: SafetyAlarmTrait.AlarmLevel.ValueType  # 3
    ALARM_LEVEL_SUBSTANTIAL: SafetyAlarmTrait.AlarmLevel.ValueType  # 4
    ALARM_LEVEL_SEVERE: SafetyAlarmTrait.AlarmLevel.ValueType  # 5
    ALARM_LEVEL_CRITICAL: SafetyAlarmTrait.AlarmLevel.ValueType  # 6

    class _AlarmState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AlarmStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SafetyAlarmTrait._AlarmState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ALARM_STATE_UNSPECIFIED: SafetyAlarmTrait._AlarmState.ValueType  # 0
        ALARM_STATE_IDLE: SafetyAlarmTrait._AlarmState.ValueType  # 1
        ALARM_STATE_HEADS_UP1: SafetyAlarmTrait._AlarmState.ValueType  # 2
        ALARM_STATE_HEADS_UP2: SafetyAlarmTrait._AlarmState.ValueType  # 3
        ALARM_STATE_ALARM: SafetyAlarmTrait._AlarmState.ValueType  # 4

    class AlarmState(_AlarmState, metaclass=_AlarmStateEnumTypeWrapper): ...
    ALARM_STATE_UNSPECIFIED: SafetyAlarmTrait.AlarmState.ValueType  # 0
    ALARM_STATE_IDLE: SafetyAlarmTrait.AlarmState.ValueType  # 1
    ALARM_STATE_HEADS_UP1: SafetyAlarmTrait.AlarmState.ValueType  # 2
    ALARM_STATE_HEADS_UP2: SafetyAlarmTrait.AlarmState.ValueType  # 3
    ALARM_STATE_ALARM: SafetyAlarmTrait.AlarmState.ValueType  # 4

    class _SilenceState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SilenceStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SafetyAlarmTrait._SilenceState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SILENCE_STATE_UNSPECIFIED: SafetyAlarmTrait._SilenceState.ValueType  # 0
        SILENCE_STATE_DISALLOWED: SafetyAlarmTrait._SilenceState.ValueType  # 1
        SILENCE_STATE_ALLOWED: SafetyAlarmTrait._SilenceState.ValueType  # 2
        SILENCE_STATE_SILENCED: SafetyAlarmTrait._SilenceState.ValueType  # 3

    class SilenceState(_SilenceState, metaclass=_SilenceStateEnumTypeWrapper): ...
    SILENCE_STATE_UNSPECIFIED: SafetyAlarmTrait.SilenceState.ValueType  # 0
    SILENCE_STATE_DISALLOWED: SafetyAlarmTrait.SilenceState.ValueType  # 1
    SILENCE_STATE_ALLOWED: SafetyAlarmTrait.SilenceState.ValueType  # 2
    SILENCE_STATE_SILENCED: SafetyAlarmTrait.SilenceState.ValueType  # 3

    @_typing.final
    class SafetyAlarmChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SESSIONID_FIELD_NUMBER: _builtins.int
        ALARMLEVEL_FIELD_NUMBER: _builtins.int
        ALARMSTATE_FIELD_NUMBER: _builtins.int
        PREVALARMSTATE_FIELD_NUMBER: _builtins.int
        SILENCESTATE_FIELD_NUMBER: _builtins.int
        PREVSILENCESTATE_FIELD_NUMBER: _builtins.int
        PREVSTATEDURATION_FIELD_NUMBER: _builtins.int
        sessionId: _builtins.int
        alarmLevel: Global___SafetyAlarmTrait.AlarmLevel.ValueType
        alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
        prevAlarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
        silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
        prevSilenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
        @_builtins.property
        def prevStateDuration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            sessionId: _builtins.int = ...,
            alarmLevel: Global___SafetyAlarmTrait.AlarmLevel.ValueType = ...,
            alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
            prevAlarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
            silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
            prevSilenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
            prevStateDuration: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["prevStateDuration", b"prevStateDuration"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["alarmLevel", b"alarmLevel", "alarmState", b"alarmState", "prevAlarmState", b"prevAlarmState", "prevSilenceState", b"prevSilenceState", "prevStateDuration", b"prevStateDuration", "sessionId", b"sessionId", "silenceState", b"silenceState"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SESSIONID_FIELD_NUMBER: _builtins.int
    ALARMSTATE_FIELD_NUMBER: _builtins.int
    SILENCESTATE_FIELD_NUMBER: _builtins.int
    sessionId: _builtins.int
    alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
    silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
    def __init__(
        self,
        *,
        sessionId: _builtins.int = ...,
        alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
        silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarmState", b"alarmState", "sessionId", b"sessionId", "silenceState", b"silenceState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SafetyAlarmTrait: _TypeAlias = SafetyAlarmTrait  # noqa: Y015

@_typing.final
class SafetyAlarmRemoteTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SafetyAlarmStatus(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ORIGINATOR_FIELD_NUMBER: _builtins.int
        ALARMSTATE_FIELD_NUMBER: _builtins.int
        SILENCESTATE_FIELD_NUMBER: _builtins.int
        alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
        silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
        @_builtins.property
        def originator(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            originator: _common_pb2.ResourceId | None = ...,
            alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
            silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["originator", b"originator"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["alarmState", b"alarmState", "originator", b"originator", "silenceState", b"silenceState"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SafetyAlarmRemoteChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        REMOTESTATUS_FIELD_NUMBER: _builtins.int
        PREVREMOTESTATUS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def remoteStatus(self) -> Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus: ...
        @_builtins.property
        def prevRemoteStatus(self) -> Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus: ...
        def __init__(
            self,
            *,
            remoteStatus: Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus | None = ...,
            prevRemoteStatus: Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["prevRemoteStatus", b"prevRemoteStatus", "remoteStatus", b"remoteStatus"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["prevRemoteStatus", b"prevRemoteStatus", "remoteStatus", b"remoteStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___SafetyAlarmRemoteTrait: _TypeAlias = SafetyAlarmRemoteTrait  # noqa: Y015

@_typing.final
class SafetyAlarmCOTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SafetyAlarmCOChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SESSIONID_FIELD_NUMBER: _builtins.int
        ALARMLEVEL_FIELD_NUMBER: _builtins.int
        ALARMSTATE_FIELD_NUMBER: _builtins.int
        PREVALARMSTATE_FIELD_NUMBER: _builtins.int
        SILENCESTATE_FIELD_NUMBER: _builtins.int
        PREVSILENCESTATE_FIELD_NUMBER: _builtins.int
        PREVSTATEDURATION_FIELD_NUMBER: _builtins.int
        PEAKCONCENTRATION_FIELD_NUMBER: _builtins.int
        BLAMETHRESHOLD_FIELD_NUMBER: _builtins.int
        BLAMEDURATION_FIELD_NUMBER: _builtins.int
        sessionId: _builtins.int
        alarmLevel: Global___SafetyAlarmTrait.AlarmLevel.ValueType
        alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
        prevAlarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
        silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
        prevSilenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
        @_builtins.property
        def prevStateDuration(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def peakConcentration(self) -> _sensor_pb2.CarbonMonoxideTrait.CoSample: ...
        @_builtins.property
        def blameThreshold(self) -> _sensor_pb2.CarbonMonoxideTrait.CoSample: ...
        @_builtins.property
        def blameDuration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            sessionId: _builtins.int = ...,
            alarmLevel: Global___SafetyAlarmTrait.AlarmLevel.ValueType = ...,
            alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
            prevAlarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
            silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
            prevSilenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
            prevStateDuration: _duration_pb2.Duration | None = ...,
            peakConcentration: _sensor_pb2.CarbonMonoxideTrait.CoSample | None = ...,
            blameThreshold: _sensor_pb2.CarbonMonoxideTrait.CoSample | None = ...,
            blameDuration: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["blameDuration", b"blameDuration", "blameThreshold", b"blameThreshold", "peakConcentration", b"peakConcentration", "prevStateDuration", b"prevStateDuration"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["alarmLevel", b"alarmLevel", "alarmState", b"alarmState", "blameDuration", b"blameDuration", "blameThreshold", b"blameThreshold", "peakConcentration", b"peakConcentration", "prevAlarmState", b"prevAlarmState", "prevSilenceState", b"prevSilenceState", "prevStateDuration", b"prevStateDuration", "sessionId", b"sessionId", "silenceState", b"silenceState"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SESSIONID_FIELD_NUMBER: _builtins.int
    ALARMSTATE_FIELD_NUMBER: _builtins.int
    SILENCESTATE_FIELD_NUMBER: _builtins.int
    PEAKCONCENTRATION_FIELD_NUMBER: _builtins.int
    BLAMETHRESHOLD_FIELD_NUMBER: _builtins.int
    BLAMEDURATION_FIELD_NUMBER: _builtins.int
    sessionId: _builtins.int
    alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
    silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
    @_builtins.property
    def peakConcentration(self) -> _sensor_pb2.CarbonMonoxideTrait.CoSample: ...
    @_builtins.property
    def blameThreshold(self) -> _sensor_pb2.CarbonMonoxideTrait.CoSample: ...
    @_builtins.property
    def blameDuration(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        sessionId: _builtins.int = ...,
        alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
        silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
        peakConcentration: _sensor_pb2.CarbonMonoxideTrait.CoSample | None = ...,
        blameThreshold: _sensor_pb2.CarbonMonoxideTrait.CoSample | None = ...,
        blameDuration: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blameDuration", b"blameDuration", "blameThreshold", b"blameThreshold", "peakConcentration", b"peakConcentration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarmState", b"alarmState", "blameDuration", b"blameDuration", "blameThreshold", b"blameThreshold", "peakConcentration", b"peakConcentration", "sessionId", b"sessionId", "silenceState", b"silenceState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SafetyAlarmCOTrait: _TypeAlias = SafetyAlarmCOTrait  # noqa: Y015

@_typing.final
class SafetyAlarmRemoteCOTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SafetyAlarmRemoteCOChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        REMOTESTATUS_FIELD_NUMBER: _builtins.int
        PREVREMOTESTATUS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def remoteStatus(self) -> Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus: ...
        @_builtins.property
        def prevRemoteStatus(self) -> Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus: ...
        def __init__(
            self,
            *,
            remoteStatus: Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus | None = ...,
            prevRemoteStatus: Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["prevRemoteStatus", b"prevRemoteStatus", "remoteStatus", b"remoteStatus"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["prevRemoteStatus", b"prevRemoteStatus", "remoteStatus", b"remoteStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___SafetyAlarmRemoteCOTrait: _TypeAlias = SafetyAlarmRemoteCOTrait  # noqa: Y015

@_typing.final
class SafetyAlarmRemoteSmokeTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SafetyAlarmRemoteSmokeChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        REMOTESTATUS_FIELD_NUMBER: _builtins.int
        PREVREMOTESTATUS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def remoteStatus(self) -> Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus: ...
        @_builtins.property
        def prevRemoteStatus(self) -> Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus: ...
        def __init__(
            self,
            *,
            remoteStatus: Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus | None = ...,
            prevRemoteStatus: Global___SafetyAlarmRemoteTrait.SafetyAlarmStatus | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["prevRemoteStatus", b"prevRemoteStatus", "remoteStatus", b"remoteStatus"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["prevRemoteStatus", b"prevRemoteStatus", "remoteStatus", b"remoteStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___SafetyAlarmRemoteSmokeTrait: _TypeAlias = SafetyAlarmRemoteSmokeTrait  # noqa: Y015

@_typing.final
class SafetyAlarmSmokeTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SafetyAlarmSmokeChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SESSIONID_FIELD_NUMBER: _builtins.int
        ALARMLEVEL_FIELD_NUMBER: _builtins.int
        ALARMSTATE_FIELD_NUMBER: _builtins.int
        PREVALARMSTATE_FIELD_NUMBER: _builtins.int
        SILENCESTATE_FIELD_NUMBER: _builtins.int
        PREVSILENCESTATE_FIELD_NUMBER: _builtins.int
        PREVSTATEDURATION_FIELD_NUMBER: _builtins.int
        STEAMDETECTED_FIELD_NUMBER: _builtins.int
        sessionId: _builtins.int
        alarmLevel: Global___SafetyAlarmTrait.AlarmLevel.ValueType
        alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
        prevAlarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
        silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
        prevSilenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
        steamDetected: _builtins.bool
        @_builtins.property
        def prevStateDuration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            sessionId: _builtins.int = ...,
            alarmLevel: Global___SafetyAlarmTrait.AlarmLevel.ValueType = ...,
            alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
            prevAlarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
            silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
            prevSilenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
            prevStateDuration: _duration_pb2.Duration | None = ...,
            steamDetected: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["prevStateDuration", b"prevStateDuration"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["alarmLevel", b"alarmLevel", "alarmState", b"alarmState", "prevAlarmState", b"prevAlarmState", "prevSilenceState", b"prevSilenceState", "prevStateDuration", b"prevStateDuration", "sessionId", b"sessionId", "silenceState", b"silenceState", "steamDetected", b"steamDetected"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SESSIONID_FIELD_NUMBER: _builtins.int
    ALARMSTATE_FIELD_NUMBER: _builtins.int
    SILENCESTATE_FIELD_NUMBER: _builtins.int
    sessionId: _builtins.int
    alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType
    silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType
    def __init__(
        self,
        *,
        sessionId: _builtins.int = ...,
        alarmState: Global___SafetyAlarmTrait.AlarmState.ValueType = ...,
        silenceState: Global___SafetyAlarmTrait.SilenceState.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alarmState", b"alarmState", "sessionId", b"sessionId", "silenceState", b"silenceState"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SafetyAlarmSmokeTrait: _TypeAlias = SafetyAlarmSmokeTrait  # noqa: Y015

@_typing.final
class SafetyAlarmSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADSUPENABLED_FIELD_NUMBER: _builtins.int
    STEAMDETECTIONENABLED_FIELD_NUMBER: _builtins.int
    headsUpEnabled: _builtins.bool
    steamDetectionEnabled: _builtins.bool
    def __init__(
        self,
        *,
        headsUpEnabled: _builtins.bool = ...,
        steamDetectionEnabled: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["headsUpEnabled", b"headsUpEnabled", "steamDetectionEnabled", b"steamDetectionEnabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SafetyAlarmSettingsTrait: _TypeAlias = SafetyAlarmSettingsTrait  # noqa: Y015
