"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SelfTestRunnerTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SelfTestType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SelfTestTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SelfTestRunnerTrait._SelfTestType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SELF_TEST_TYPE_UNSPECIFIED: SelfTestRunnerTrait._SelfTestType.ValueType  # 0
        SELF_TEST_TYPE_SOUND_CHECK: SelfTestRunnerTrait._SelfTestType.ValueType  # 1
        SELF_TEST_TYPE_SAFETY_CHECK: SelfTestRunnerTrait._SelfTestType.ValueType  # 2
        SELF_TEST_TYPE_SECURITY_CHECK: SelfTestRunnerTrait._SelfTestType.ValueType  # 3

    class SelfTestType(_SelfTestType, metaclass=_SelfTestTypeEnumTypeWrapper): ...
    SELF_TEST_TYPE_UNSPECIFIED: SelfTestRunnerTrait.SelfTestType.ValueType  # 0
    SELF_TEST_TYPE_SOUND_CHECK: SelfTestRunnerTrait.SelfTestType.ValueType  # 1
    SELF_TEST_TYPE_SAFETY_CHECK: SelfTestRunnerTrait.SelfTestType.ValueType  # 2
    SELF_TEST_TYPE_SECURITY_CHECK: SelfTestRunnerTrait.SelfTestType.ValueType  # 3

    class _SelfTestResult:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SelfTestResultEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SelfTestRunnerTrait._SelfTestResult.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SELF_TEST_RESULT_UNSPECIFIED: SelfTestRunnerTrait._SelfTestResult.ValueType  # 0
        SELF_TEST_RESULT_PASS: SelfTestRunnerTrait._SelfTestResult.ValueType  # 1
        SELF_TEST_RESULT_FAIL_WARN: SelfTestRunnerTrait._SelfTestResult.ValueType  # 2
        SELF_TEST_RESULT_FAIL_CRITICAL: SelfTestRunnerTrait._SelfTestResult.ValueType  # 3

    class SelfTestResult(_SelfTestResult, metaclass=_SelfTestResultEnumTypeWrapper): ...
    SELF_TEST_RESULT_UNSPECIFIED: SelfTestRunnerTrait.SelfTestResult.ValueType  # 0
    SELF_TEST_RESULT_PASS: SelfTestRunnerTrait.SelfTestResult.ValueType  # 1
    SELF_TEST_RESULT_FAIL_WARN: SelfTestRunnerTrait.SelfTestResult.ValueType  # 2
    SELF_TEST_RESULT_FAIL_CRITICAL: SelfTestRunnerTrait.SelfTestResult.ValueType  # 3

    class _RunSelfTestStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RunSelfTestStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SelfTestRunnerTrait._RunSelfTestStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        RUN_SELF_TEST_STATUS_UNSPECIFIED: SelfTestRunnerTrait._RunSelfTestStatus.ValueType  # 0
        RUN_SELF_TEST_STATUS_SUCCESS: SelfTestRunnerTrait._RunSelfTestStatus.ValueType  # 1
        RUN_SELF_TEST_STATUS_WILL_NOT_RUN: SelfTestRunnerTrait._RunSelfTestStatus.ValueType  # 2
        RUN_SELF_TEST_STATUS_EXCEEDS_TIMEOUT: SelfTestRunnerTrait._RunSelfTestStatus.ValueType  # 4
        RUN_SELF_TEST_STATUS_ALREADY_RUN: SelfTestRunnerTrait._RunSelfTestStatus.ValueType  # 5
        RUN_SELF_TEST_STATUS_BUSY: SelfTestRunnerTrait._RunSelfTestStatus.ValueType  # 6
        RUN_SELF_TEST_STATUS_INTERNAL_ERROR: SelfTestRunnerTrait._RunSelfTestStatus.ValueType  # 7

    class RunSelfTestStatus(_RunSelfTestStatus, metaclass=_RunSelfTestStatusEnumTypeWrapper): ...
    RUN_SELF_TEST_STATUS_UNSPECIFIED: SelfTestRunnerTrait.RunSelfTestStatus.ValueType  # 0
    RUN_SELF_TEST_STATUS_SUCCESS: SelfTestRunnerTrait.RunSelfTestStatus.ValueType  # 1
    RUN_SELF_TEST_STATUS_WILL_NOT_RUN: SelfTestRunnerTrait.RunSelfTestStatus.ValueType  # 2
    RUN_SELF_TEST_STATUS_EXCEEDS_TIMEOUT: SelfTestRunnerTrait.RunSelfTestStatus.ValueType  # 4
    RUN_SELF_TEST_STATUS_ALREADY_RUN: SelfTestRunnerTrait.RunSelfTestStatus.ValueType  # 5
    RUN_SELF_TEST_STATUS_BUSY: SelfTestRunnerTrait.RunSelfTestStatus.ValueType  # 6
    RUN_SELF_TEST_STATUS_INTERNAL_ERROR: SelfTestRunnerTrait.RunSelfTestStatus.ValueType  # 7

    @_typing.final
    class TestId(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ROOTORCHESTRATORID_FIELD_NUMBER: _builtins.int
        INSTANCEID_FIELD_NUMBER: _builtins.int
        instanceId: _builtins.int
        @_builtins.property
        def rootOrchestratorId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            rootOrchestratorId: _common_pb2.ResourceId | None = ...,
            instanceId: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["rootOrchestratorId", b"rootOrchestratorId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["instanceId", b"instanceId", "rootOrchestratorId", b"rootOrchestratorId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SelfTestStartedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TESTID_FIELD_NUMBER: _builtins.int
        ORCHESTRATORID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def testId(self) -> Global___SelfTestRunnerTrait.TestId: ...
        @_builtins.property
        def orchestratorId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            testId: Global___SelfTestRunnerTrait.TestId | None = ...,
            orchestratorId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["orchestratorId", b"orchestratorId", "testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["orchestratorId", b"orchestratorId", "testId", b"testId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SelfTestEndedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TESTID_FIELD_NUMBER: _builtins.int
        RESULT_FIELD_NUMBER: _builtins.int
        TESTSTATUS_FIELD_NUMBER: _builtins.int
        RELATEDRESULTS_FIELD_NUMBER: _builtins.int
        result: Global___SelfTestRunnerTrait.SelfTestResult.ValueType
        testStatus: Global___SelfTestRunnerTrait.RunSelfTestStatus.ValueType
        @_builtins.property
        def testId(self) -> Global___SelfTestRunnerTrait.TestId: ...
        @_builtins.property
        def relatedResults(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.EventId]: ...
        def __init__(
            self,
            *,
            testId: Global___SelfTestRunnerTrait.TestId | None = ...,
            result: Global___SelfTestRunnerTrait.SelfTestResult.ValueType = ...,
            testStatus: Global___SelfTestRunnerTrait.RunSelfTestStatus.ValueType = ...,
            relatedResults: _abc.Iterable[_common_pb2.EventId] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["relatedResults", b"relatedResults", "result", b"result", "testId", b"testId", "testStatus", b"testStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class OrchestrationStartedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TESTID_FIELD_NUMBER: _builtins.int
        PARENTID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def testId(self) -> Global___SelfTestRunnerTrait.TestId: ...
        @_builtins.property
        def parentId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            testId: Global___SelfTestRunnerTrait.TestId | None = ...,
            parentId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["parentId", b"parentId", "testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["parentId", b"parentId", "testId", b"testId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class OrchestrationEndedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TESTID_FIELD_NUMBER: _builtins.int
        RESULT_FIELD_NUMBER: _builtins.int
        result: Global___SelfTestRunnerTrait.SelfTestResult.ValueType
        @_builtins.property
        def testId(self) -> Global___SelfTestRunnerTrait.TestId: ...
        def __init__(
            self,
            *,
            testId: Global___SelfTestRunnerTrait.TestId | None = ...,
            result: Global___SelfTestRunnerTrait.SelfTestResult.ValueType = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "testId", b"testId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RunnerTimoutEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TESTID_FIELD_NUMBER: _builtins.int
        RUNNERID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def testId(self) -> Global___SelfTestRunnerTrait.TestId: ...
        @_builtins.property
        def runnerId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            testId: Global___SelfTestRunnerTrait.TestId | None = ...,
            runnerId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["runnerId", b"runnerId", "testId", b"testId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["runnerId", b"runnerId", "testId", b"testId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RunSelfTestRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TESTID_FIELD_NUMBER: _builtins.int
        TESTTIMEOUT_FIELD_NUMBER: _builtins.int
        TESTTYPES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def testId(self) -> Global___SelfTestRunnerTrait.TestId: ...
        @_builtins.property
        def testTimeout(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def testTypes(self) -> _containers.RepeatedScalarFieldContainer[Global___SelfTestRunnerTrait.SelfTestType.ValueType]: ...
        def __init__(
            self,
            *,
            testId: Global___SelfTestRunnerTrait.TestId | None = ...,
            testTimeout: _duration_pb2.Duration | None = ...,
            testTypes: _abc.Iterable[Global___SelfTestRunnerTrait.SelfTestType.ValueType] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId", "testTimeout", b"testTimeout"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["testId", b"testId", "testTimeout", b"testTimeout", "testTypes", b"testTypes"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RunSelfTestResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESULT_FIELD_NUMBER: _builtins.int
        TESTSTATUS_FIELD_NUMBER: _builtins.int
        result: Global___SelfTestRunnerTrait.SelfTestResult.ValueType
        testStatus: Global___SelfTestRunnerTrait.RunSelfTestStatus.ValueType
        def __init__(
            self,
            *,
            result: Global___SelfTestRunnerTrait.SelfTestResult.ValueType = ...,
            testStatus: Global___SelfTestRunnerTrait.RunSelfTestStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "testStatus", b"testStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CURRENTSELFTESTID_FIELD_NUMBER: _builtins.int
    PREVIOUSSELFTESTID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def currentSelfTestId(self) -> Global___SelfTestRunnerTrait.TestId: ...
    @_builtins.property
    def previousSelfTestId(self) -> Global___SelfTestRunnerTrait.TestId: ...
    def __init__(
        self,
        *,
        currentSelfTestId: Global___SelfTestRunnerTrait.TestId | None = ...,
        previousSelfTestId: Global___SelfTestRunnerTrait.TestId | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["currentSelfTestId", b"currentSelfTestId", "previousSelfTestId", b"previousSelfTestId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currentSelfTestId", b"currentSelfTestId", "previousSelfTestId", b"previousSelfTestId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SelfTestRunnerTrait: _TypeAlias = SelfTestRunnerTrait  # noqa: Y015
