"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PassiveInfraredTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PassiveInfraredFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PassiveInfraredFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PassiveInfraredTrait._PassiveInfraredFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PASSIVE_INFRARED_FAULT_TYPE_UNSPECIFIED: PassiveInfraredTrait._PassiveInfraredFaultType.ValueType  # 0
        PASSIVE_INFRARED_FAULT_TYPE_NONE: PassiveInfraredTrait._PassiveInfraredFaultType.ValueType  # 1
        PASSIVE_INFRARED_FAULT_TYPE_UNRESPONSIVE: PassiveInfraredTrait._PassiveInfraredFaultType.ValueType  # 2
        PASSIVE_INFRARED_FAULT_TYPE_STUCK: PassiveInfraredTrait._PassiveInfraredFaultType.ValueType  # 3

    class PassiveInfraredFaultType(_PassiveInfraredFaultType, metaclass=_PassiveInfraredFaultTypeEnumTypeWrapper): ...
    PASSIVE_INFRARED_FAULT_TYPE_UNSPECIFIED: PassiveInfraredTrait.PassiveInfraredFaultType.ValueType  # 0
    PASSIVE_INFRARED_FAULT_TYPE_NONE: PassiveInfraredTrait.PassiveInfraredFaultType.ValueType  # 1
    PASSIVE_INFRARED_FAULT_TYPE_UNRESPONSIVE: PassiveInfraredTrait.PassiveInfraredFaultType.ValueType  # 2
    PASSIVE_INFRARED_FAULT_TYPE_STUCK: PassiveInfraredTrait.PassiveInfraredFaultType.ValueType  # 3

    @_typing.final
    class PassiveInfraredSample(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _wrappers_pb2.FloatValue: ...
        def __init__(
            self,
            *,
            value: _wrappers_pb2.FloatValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PassiveInfraredFaultInformation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        SIGNALLASTVALUE_FIELD_NUMBER: _builtins.int
        BASELINELASTVALUE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___PassiveInfraredTrait.PassiveInfraredFaultType.ValueType
        @_builtins.property
        def signalLastValue(self) -> Global___PassiveInfraredTrait.PassiveInfraredSample: ...
        @_builtins.property
        def baselineLastValue(self) -> Global___PassiveInfraredTrait.PassiveInfraredSample: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___PassiveInfraredTrait.PassiveInfraredFaultType.ValueType = ...,
            signalLastValue: Global___PassiveInfraredTrait.PassiveInfraredSample | None = ...,
            baselineLastValue: Global___PassiveInfraredTrait.PassiveInfraredSample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["baselineLastValue", b"baselineLastValue", "signalLastValue", b"signalLastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "baselineLastValue", b"baselineLastValue", "signalLastValue", b"signalLastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PassiveInfraredSignalPeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SIGNALSAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def signalSamples(self) -> _containers.RepeatedCompositeFieldContainer[Global___PassiveInfraredTrait.PassiveInfraredSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            signalSamples: _abc.Iterable[Global___PassiveInfraredTrait.PassiveInfraredSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "signalSamples", b"signalSamples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PassiveInfraredBaselinePeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        BASELINESAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def baselineSamples(self) -> _containers.RepeatedCompositeFieldContainer[Global___PassiveInfraredTrait.PassiveInfraredSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            baselineSamples: _abc.Iterable[Global___PassiveInfraredTrait.PassiveInfraredSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["baselineSamples", b"baselineSamples", "sampleInterval", b"sampleInterval"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PassiveInfraredDifferentialPeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        DELTASAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def deltaSamples(self) -> _containers.RepeatedCompositeFieldContainer[Global___PassiveInfraredTrait.PassiveInfraredSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            deltaSamples: _abc.Iterable[Global___PassiveInfraredTrait.PassiveInfraredSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["deltaSamples", b"deltaSamples", "sampleInterval", b"sampleInterval"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PassiveInfraredFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        SIGNALLASTVALUE_FIELD_NUMBER: _builtins.int
        BASELINELASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        LASTSAMPLEPERIOD_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___PassiveInfraredTrait.PassiveInfraredFaultType.ValueType
        @_builtins.property
        def signalLastValue(self) -> Global___PassiveInfraredTrait.PassiveInfraredSample: ...
        @_builtins.property
        def baselineLastValue(self) -> Global___PassiveInfraredTrait.PassiveInfraredSample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def lastSamplePeriod(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___PassiveInfraredTrait.PassiveInfraredFaultType.ValueType = ...,
            signalLastValue: Global___PassiveInfraredTrait.PassiveInfraredSample | None = ...,
            baselineLastValue: Global___PassiveInfraredTrait.PassiveInfraredSample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
            lastSamplePeriod: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["baselineLastValue", b"baselineLastValue", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "signalLastValue", b"signalLastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "baselineLastValue", b"baselineLastValue", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "signalLastValue", b"signalLastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PassiveInfraredSignalStatisticsEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        HISTOGRAMBOUNDARIES_FIELD_NUMBER: _builtins.int
        HISTOGRAMCOUNTS_FIELD_NUMBER: _builtins.int
        VACANCYEXPECTED_FIELD_NUMBER: _builtins.int
        vacancyExpected: _builtins.bool
        @_builtins.property
        def histogramBoundaries(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        @_builtins.property
        def histogramCounts(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(
            self,
            *,
            histogramBoundaries: _abc.Iterable[_builtins.int] | None = ...,
            histogramCounts: _abc.Iterable[_builtins.int] | None = ...,
            vacancyExpected: _builtins.bool = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["histogramBoundaries", b"histogramBoundaries", "histogramCounts", b"histogramCounts", "vacancyExpected", b"vacancyExpected"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PASSIVEINFRAREDSIGNALVALUE_FIELD_NUMBER: _builtins.int
    PASSIVEINFRAREDBASELINEVALUE_FIELD_NUMBER: _builtins.int
    FAULTINFORMATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def passiveInfraredSignalValue(self) -> Global___PassiveInfraredTrait.PassiveInfraredSample: ...
    @_builtins.property
    def passiveInfraredBaselineValue(self) -> Global___PassiveInfraredTrait.PassiveInfraredSample: ...
    @_builtins.property
    def faultInformation(self) -> Global___PassiveInfraredTrait.PassiveInfraredFaultInformation: ...
    def __init__(
        self,
        *,
        passiveInfraredSignalValue: Global___PassiveInfraredTrait.PassiveInfraredSample | None = ...,
        passiveInfraredBaselineValue: Global___PassiveInfraredTrait.PassiveInfraredSample | None = ...,
        faultInformation: Global___PassiveInfraredTrait.PassiveInfraredFaultInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "passiveInfraredBaselineValue", b"passiveInfraredBaselineValue", "passiveInfraredSignalValue", b"passiveInfraredSignalValue"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "passiveInfraredBaselineValue", b"passiveInfraredBaselineValue", "passiveInfraredSignalValue", b"passiveInfraredSignalValue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PassiveInfraredTrait: _TypeAlias = PassiveInfraredTrait  # noqa: Y015

@_typing.final
class SmokeTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _SmokeFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SmokeFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SmokeTrait._SmokeFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SMOKE_FAULT_TYPE_UNSPECIFIED: SmokeTrait._SmokeFaultType.ValueType  # 0
        SMOKE_FAULT_TYPE_NONE: SmokeTrait._SmokeFaultType.ValueType  # 1
        SMOKE_FAULT_TYPE_UNRESPONSIVE: SmokeTrait._SmokeFaultType.ValueType  # 2

    class SmokeFaultType(_SmokeFaultType, metaclass=_SmokeFaultTypeEnumTypeWrapper): ...
    SMOKE_FAULT_TYPE_UNSPECIFIED: SmokeTrait.SmokeFaultType.ValueType  # 0
    SMOKE_FAULT_TYPE_NONE: SmokeTrait.SmokeFaultType.ValueType  # 1
    SMOKE_FAULT_TYPE_UNRESPONSIVE: SmokeTrait.SmokeFaultType.ValueType  # 2

    @_typing.final
    class SmokeSample(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sample(self) -> _wrappers_pb2.FloatValue: ...
        def __init__(
            self,
            *,
            sample: _wrappers_pb2.FloatValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sample", b"sample"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sample", b"sample"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SmokeFaultInformation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___SmokeTrait.SmokeFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___SmokeTrait.SmokeSample: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___SmokeTrait.SmokeFaultType.ValueType = ...,
            lastValue: Global___SmokeTrait.SmokeSample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class InfraredLedFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        LASTSAMPLEPERIOD_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___SmokeTrait.SmokeFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___SmokeTrait.SmokeSample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def lastSamplePeriod(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___SmokeTrait.SmokeFaultType.ValueType = ...,
            lastValue: Global___SmokeTrait.SmokeSample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
            lastSamplePeriod: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BlueLedFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        LASTSAMPLEPERIOD_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___SmokeTrait.SmokeFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___SmokeTrait.SmokeSample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def lastSamplePeriod(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___SmokeTrait.SmokeFaultType.ValueType = ...,
            lastValue: Global___SmokeTrait.SmokeSample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
            lastSamplePeriod: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class InfraredLedPeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___SmokeTrait.SmokeSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            samples: _abc.Iterable[Global___SmokeTrait.SmokeSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "samples", b"samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BlueLedPeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___SmokeTrait.SmokeSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            samples: _abc.Iterable[Global___SmokeTrait.SmokeSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "samples", b"samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ClearAirOffsetSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        IRLEDSAMPLES_FIELD_NUMBER: _builtins.int
        BLUELEDSAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def irLedSamples(self) -> _containers.RepeatedCompositeFieldContainer[Global___SmokeTrait.SmokeSample]: ...
        @_builtins.property
        def blueLedSamples(self) -> _containers.RepeatedCompositeFieldContainer[Global___SmokeTrait.SmokeSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            irLedSamples: _abc.Iterable[Global___SmokeTrait.SmokeSample] | None = ...,
            blueLedSamples: _abc.Iterable[Global___SmokeTrait.SmokeSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["blueLedSamples", b"blueLedSamples", "irLedSamples", b"irLedSamples", "sampleInterval", b"sampleInterval"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    INFRAREDLEDVALUE_FIELD_NUMBER: _builtins.int
    BLUELEDVALUE_FIELD_NUMBER: _builtins.int
    INFRAREDLEDFAULT_FIELD_NUMBER: _builtins.int
    BLUELEDFAULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def infraredLedValue(self) -> Global___SmokeTrait.SmokeSample: ...
    @_builtins.property
    def blueLedValue(self) -> Global___SmokeTrait.SmokeSample: ...
    @_builtins.property
    def infraredLedFault(self) -> Global___SmokeTrait.SmokeFaultInformation: ...
    @_builtins.property
    def blueLedFault(self) -> Global___SmokeTrait.SmokeFaultInformation: ...
    def __init__(
        self,
        *,
        infraredLedValue: Global___SmokeTrait.SmokeSample | None = ...,
        blueLedValue: Global___SmokeTrait.SmokeSample | None = ...,
        infraredLedFault: Global___SmokeTrait.SmokeFaultInformation | None = ...,
        blueLedFault: Global___SmokeTrait.SmokeFaultInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blueLedFault", b"blueLedFault", "blueLedValue", b"blueLedValue", "infraredLedFault", b"infraredLedFault", "infraredLedValue", b"infraredLedValue"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blueLedFault", b"blueLedFault", "blueLedValue", b"blueLedValue", "infraredLedFault", b"infraredLedFault", "infraredLedValue", b"infraredLedValue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SmokeTrait: _TypeAlias = SmokeTrait  # noqa: Y015

@_typing.final
class TemperatureTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _TemperatureFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TemperatureFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TemperatureTrait._TemperatureFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TEMPERATURE_FAULT_TYPE_UNSPECIFIED: TemperatureTrait._TemperatureFaultType.ValueType  # 0
        TEMPERATURE_FAULT_TYPE_NONE: TemperatureTrait._TemperatureFaultType.ValueType  # 1
        TEMPERATURE_FAULT_TYPE_UNRESPONSIVE: TemperatureTrait._TemperatureFaultType.ValueType  # 2
        TEMPERATURE_FAULT_TYPE_OUT_OF_NORMAL_RANGE: TemperatureTrait._TemperatureFaultType.ValueType  # 3

    class TemperatureFaultType(_TemperatureFaultType, metaclass=_TemperatureFaultTypeEnumTypeWrapper): ...
    TEMPERATURE_FAULT_TYPE_UNSPECIFIED: TemperatureTrait.TemperatureFaultType.ValueType  # 0
    TEMPERATURE_FAULT_TYPE_NONE: TemperatureTrait.TemperatureFaultType.ValueType  # 1
    TEMPERATURE_FAULT_TYPE_UNRESPONSIVE: TemperatureTrait.TemperatureFaultType.ValueType  # 2
    TEMPERATURE_FAULT_TYPE_OUT_OF_NORMAL_RANGE: TemperatureTrait.TemperatureFaultType.ValueType  # 3

    @_typing.final
    class TemperatureSample(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TEMPERATURE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def temperature(self) -> _wrappers_pb2.FloatValue: ...
        def __init__(
            self,
            *,
            temperature: _wrappers_pb2.FloatValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["temperature", b"temperature"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["temperature", b"temperature"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class TemperatureFaultInformation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___TemperatureTrait.TemperatureFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___TemperatureTrait.TemperatureSample: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___TemperatureTrait.TemperatureFaultType.ValueType = ...,
            lastValue: Global___TemperatureTrait.TemperatureSample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class TemperatureSensorFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        LASTSAMPLEPERIOD_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___TemperatureTrait.TemperatureFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___TemperatureTrait.TemperatureSample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def lastSamplePeriod(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___TemperatureTrait.TemperatureFaultType.ValueType = ...,
            lastValue: Global___TemperatureTrait.TemperatureSample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
            lastSamplePeriod: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class TemperaturePeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___TemperatureTrait.TemperatureSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            samples: _abc.Iterable[Global___TemperatureTrait.TemperatureSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "samples", b"samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TEMPERATUREVALUE_FIELD_NUMBER: _builtins.int
    FAULTINFORMATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def temperatureValue(self) -> Global___TemperatureTrait.TemperatureSample: ...
    @_builtins.property
    def faultInformation(self) -> Global___TemperatureTrait.TemperatureFaultInformation: ...
    def __init__(
        self,
        *,
        temperatureValue: Global___TemperatureTrait.TemperatureSample | None = ...,
        faultInformation: Global___TemperatureTrait.TemperatureFaultInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "temperatureValue", b"temperatureValue"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "temperatureValue", b"temperatureValue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TemperatureTrait: _TypeAlias = TemperatureTrait  # noqa: Y015

@_typing.final
class CarbonMonoxideTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _CoFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CoFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[CarbonMonoxideTrait._CoFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CO_FAULT_TYPE_UNSPECIFIED: CarbonMonoxideTrait._CoFaultType.ValueType  # 0
        CO_FAULT_TYPE_NONE: CarbonMonoxideTrait._CoFaultType.ValueType  # 1
        CO_FAULT_TYPE_UNRESPONSIVE: CarbonMonoxideTrait._CoFaultType.ValueType  # 2
        CO_FAULT_TYPE_END_OF_LIFE: CarbonMonoxideTrait._CoFaultType.ValueType  # 3

    class CoFaultType(_CoFaultType, metaclass=_CoFaultTypeEnumTypeWrapper): ...
    CO_FAULT_TYPE_UNSPECIFIED: CarbonMonoxideTrait.CoFaultType.ValueType  # 0
    CO_FAULT_TYPE_NONE: CarbonMonoxideTrait.CoFaultType.ValueType  # 1
    CO_FAULT_TYPE_UNRESPONSIVE: CarbonMonoxideTrait.CoFaultType.ValueType  # 2
    CO_FAULT_TYPE_END_OF_LIFE: CarbonMonoxideTrait.CoFaultType.ValueType  # 3

    @_typing.final
    class CoSample(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PPM_FIELD_NUMBER: _builtins.int
        ppm: _builtins.int
        def __init__(
            self,
            *,
            ppm: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["ppm", b"ppm"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CoFaultInformation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___CarbonMonoxideTrait.CoFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___CarbonMonoxideTrait.CoSample: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___CarbonMonoxideTrait.CoFaultType.ValueType = ...,
            lastValue: Global___CarbonMonoxideTrait.CoSample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CoFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        LASTSAMPLEPERIOD_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___CarbonMonoxideTrait.CoFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___CarbonMonoxideTrait.CoSample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def lastSamplePeriod(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___CarbonMonoxideTrait.CoFaultType.ValueType = ...,
            lastValue: Global___CarbonMonoxideTrait.CoSample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
            lastSamplePeriod: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class CoPeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___CarbonMonoxideTrait.CoSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            samples: _abc.Iterable[Global___CarbonMonoxideTrait.CoSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "samples", b"samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    VALUE_FIELD_NUMBER: _builtins.int
    FAULTINFORMATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def value(self) -> Global___CarbonMonoxideTrait.CoSample: ...
    @_builtins.property
    def faultInformation(self) -> Global___CarbonMonoxideTrait.CoFaultInformation: ...
    def __init__(
        self,
        *,
        value: Global___CarbonMonoxideTrait.CoSample | None = ...,
        faultInformation: Global___CarbonMonoxideTrait.CoFaultInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CarbonMonoxideTrait: _TypeAlias = CarbonMonoxideTrait  # noqa: Y015

@_typing.final
class BatteryVoltageTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _BatteryVoltageFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BatteryVoltageFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BatteryVoltageTrait._BatteryVoltageFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        BATTERY_VOLTAGE_FAULT_TYPE_UNSPECIFIED: BatteryVoltageTrait._BatteryVoltageFaultType.ValueType  # 0
        BATTERY_VOLTAGE_FAULT_TYPE_NONE: BatteryVoltageTrait._BatteryVoltageFaultType.ValueType  # 1
        BATTERY_VOLTAGE_FAULT_TYPE_OUT_OF_OPERATING_RANGE: BatteryVoltageTrait._BatteryVoltageFaultType.ValueType  # 2
        BATTERY_VOLTAGE_FAULT_TYPE_UNRESPONSIVE: BatteryVoltageTrait._BatteryVoltageFaultType.ValueType  # 3
        BATTERY_VOLTAGE_FAULT_TYPE_DISCONNECTED: BatteryVoltageTrait._BatteryVoltageFaultType.ValueType  # 4
        BATTERY_VOLTAGE_FAULT_TYPE_END_OF_LIFE: BatteryVoltageTrait._BatteryVoltageFaultType.ValueType  # 5

    class BatteryVoltageFaultType(_BatteryVoltageFaultType, metaclass=_BatteryVoltageFaultTypeEnumTypeWrapper): ...
    BATTERY_VOLTAGE_FAULT_TYPE_UNSPECIFIED: BatteryVoltageTrait.BatteryVoltageFaultType.ValueType  # 0
    BATTERY_VOLTAGE_FAULT_TYPE_NONE: BatteryVoltageTrait.BatteryVoltageFaultType.ValueType  # 1
    BATTERY_VOLTAGE_FAULT_TYPE_OUT_OF_OPERATING_RANGE: BatteryVoltageTrait.BatteryVoltageFaultType.ValueType  # 2
    BATTERY_VOLTAGE_FAULT_TYPE_UNRESPONSIVE: BatteryVoltageTrait.BatteryVoltageFaultType.ValueType  # 3
    BATTERY_VOLTAGE_FAULT_TYPE_DISCONNECTED: BatteryVoltageTrait.BatteryVoltageFaultType.ValueType  # 4
    BATTERY_VOLTAGE_FAULT_TYPE_END_OF_LIFE: BatteryVoltageTrait.BatteryVoltageFaultType.ValueType  # 5

    @_typing.final
    class BatteryVoltageSample(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BATTERYVOLTAGE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def batteryVoltage(self) -> _wrappers_pb2.FloatValue: ...
        def __init__(
            self,
            *,
            batteryVoltage: _wrappers_pb2.FloatValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["batteryVoltage", b"batteryVoltage"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["batteryVoltage", b"batteryVoltage"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BatteryVoltageFaultInformation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___BatteryVoltageTrait.BatteryVoltageFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___BatteryVoltageTrait.BatteryVoltageSample: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___BatteryVoltageTrait.BatteryVoltageFaultType.ValueType = ...,
            lastValue: Global___BatteryVoltageTrait.BatteryVoltageSample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BatteryVoltageFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___BatteryVoltageTrait.BatteryVoltageFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___BatteryVoltageTrait.BatteryVoltageSample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___BatteryVoltageTrait.BatteryVoltageFaultType.ValueType = ...,
            lastValue: Global___BatteryVoltageTrait.BatteryVoltageSample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["durationSinceLastSample", b"durationSinceLastSample", "lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "durationSinceLastSample", b"durationSinceLastSample", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BatteryVoltagePeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___BatteryVoltageTrait.BatteryVoltageSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            samples: _abc.Iterable[Global___BatteryVoltageTrait.BatteryVoltageSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "samples", b"samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class BatteryVoltageStatisticsEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MEANVOLTAGE_FIELD_NUMBER: _builtins.int
        MINIMUMVOLTAGE_FIELD_NUMBER: _builtins.int
        MAXIMUMVOLTAGE_FIELD_NUMBER: _builtins.int
        NUMSAMPLES_FIELD_NUMBER: _builtins.int
        STATSSAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        numSamples: _builtins.int
        @_builtins.property
        def meanVoltage(self) -> Global___BatteryVoltageTrait.BatteryVoltageSample: ...
        @_builtins.property
        def minimumVoltage(self) -> Global___BatteryVoltageTrait.BatteryVoltageSample: ...
        @_builtins.property
        def maximumVoltage(self) -> Global___BatteryVoltageTrait.BatteryVoltageSample: ...
        @_builtins.property
        def statsSampleInterval(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            meanVoltage: Global___BatteryVoltageTrait.BatteryVoltageSample | None = ...,
            minimumVoltage: Global___BatteryVoltageTrait.BatteryVoltageSample | None = ...,
            maximumVoltage: Global___BatteryVoltageTrait.BatteryVoltageSample | None = ...,
            numSamples: _builtins.int = ...,
            statsSampleInterval: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["maximumVoltage", b"maximumVoltage", "meanVoltage", b"meanVoltage", "minimumVoltage", b"minimumVoltage", "statsSampleInterval", b"statsSampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["maximumVoltage", b"maximumVoltage", "meanVoltage", b"meanVoltage", "minimumVoltage", b"minimumVoltage", "numSamples", b"numSamples", "statsSampleInterval", b"statsSampleInterval"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    BATTERYVALUE_FIELD_NUMBER: _builtins.int
    FAULTINFORMATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def batteryValue(self) -> Global___BatteryVoltageTrait.BatteryVoltageSample: ...
    @_builtins.property
    def faultInformation(self) -> Global___BatteryVoltageTrait.BatteryVoltageFaultInformation: ...
    def __init__(
        self,
        *,
        batteryValue: Global___BatteryVoltageTrait.BatteryVoltageSample | None = ...,
        faultInformation: Global___BatteryVoltageTrait.BatteryVoltageFaultInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["batteryValue", b"batteryValue", "faultInformation", b"faultInformation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["batteryValue", b"batteryValue", "faultInformation", b"faultInformation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatteryVoltageTrait: _TypeAlias = BatteryVoltageTrait  # noqa: Y015

@_typing.final
class AmbientLightTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _AmbientLightFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AmbientLightFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AmbientLightTrait._AmbientLightFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        AMBIENT_LIGHT_FAULT_TYPE_UNSPECIFIED: AmbientLightTrait._AmbientLightFaultType.ValueType  # 0
        AMBIENT_LIGHT_FAULT_TYPE_NONE: AmbientLightTrait._AmbientLightFaultType.ValueType  # 1
        AMBIENT_LIGHT_FAULT_TYPE_UNRESPONSIVE: AmbientLightTrait._AmbientLightFaultType.ValueType  # 2

    class AmbientLightFaultType(_AmbientLightFaultType, metaclass=_AmbientLightFaultTypeEnumTypeWrapper): ...
    AMBIENT_LIGHT_FAULT_TYPE_UNSPECIFIED: AmbientLightTrait.AmbientLightFaultType.ValueType  # 0
    AMBIENT_LIGHT_FAULT_TYPE_NONE: AmbientLightTrait.AmbientLightFaultType.ValueType  # 1
    AMBIENT_LIGHT_FAULT_TYPE_UNRESPONSIVE: AmbientLightTrait.AmbientLightFaultType.ValueType  # 2

    @_typing.final
    class AmbientLightSample(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        AMBIENTLIGHT_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def ambientLight(self) -> _wrappers_pb2.FloatValue: ...
        def __init__(
            self,
            *,
            ambientLight: _wrappers_pb2.FloatValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["ambientLight", b"ambientLight"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["ambientLight", b"ambientLight"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AmbientLightFaultInformation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___AmbientLightTrait.AmbientLightFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___AmbientLightTrait.AmbientLightSample: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___AmbientLightTrait.AmbientLightFaultType.ValueType = ...,
            lastValue: Global___AmbientLightTrait.AmbientLightSample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AmbientLightFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        LASTSAMPLEPERIOD_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___AmbientLightTrait.AmbientLightFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___AmbientLightTrait.AmbientLightSample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def lastSamplePeriod(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___AmbientLightTrait.AmbientLightFaultType.ValueType = ...,
            lastValue: Global___AmbientLightTrait.AmbientLightSample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
            lastSamplePeriod: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AmbientLightPeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___AmbientLightTrait.AmbientLightSample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            samples: _abc.Iterable[Global___AmbientLightTrait.AmbientLightSample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "samples", b"samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    AMBIENTLIGHTVALUE_FIELD_NUMBER: _builtins.int
    FAULTINFORMATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ambientLightValue(self) -> Global___AmbientLightTrait.AmbientLightSample: ...
    @_builtins.property
    def faultInformation(self) -> Global___AmbientLightTrait.AmbientLightFaultInformation: ...
    def __init__(
        self,
        *,
        ambientLightValue: Global___AmbientLightTrait.AmbientLightSample | None = ...,
        faultInformation: Global___AmbientLightTrait.AmbientLightFaultInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ambientLightValue", b"ambientLightValue", "faultInformation", b"faultInformation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ambientLightValue", b"ambientLightValue", "faultInformation", b"faultInformation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AmbientLightTrait: _TypeAlias = AmbientLightTrait  # noqa: Y015

@_typing.final
class HumidityTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _HumidityFaultType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _HumidityFaultTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HumidityTrait._HumidityFaultType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        HUMIDITY_FAULT_TYPE_UNSPECIFIED: HumidityTrait._HumidityFaultType.ValueType  # 0
        HUMIDITY_FAULT_TYPE_NONE: HumidityTrait._HumidityFaultType.ValueType  # 1
        HUMIDITY_FAULT_TYPE_UNRESPONSIVE: HumidityTrait._HumidityFaultType.ValueType  # 2

    class HumidityFaultType(_HumidityFaultType, metaclass=_HumidityFaultTypeEnumTypeWrapper): ...
    HUMIDITY_FAULT_TYPE_UNSPECIFIED: HumidityTrait.HumidityFaultType.ValueType  # 0
    HUMIDITY_FAULT_TYPE_NONE: HumidityTrait.HumidityFaultType.ValueType  # 1
    HUMIDITY_FAULT_TYPE_UNRESPONSIVE: HumidityTrait.HumidityFaultType.ValueType  # 2

    @_typing.final
    class HumiditySample(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        HUMIDITY_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def humidity(self) -> _wrappers_pb2.FloatValue: ...
        def __init__(
            self,
            *,
            humidity: _wrappers_pb2.FloatValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["humidity", b"humidity"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["humidity", b"humidity"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class HumidityFaultInformation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___HumidityTrait.HumidityFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___HumidityTrait.HumiditySample: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___HumidityTrait.HumidityFaultType.ValueType = ...,
            lastValue: Global___HumidityTrait.HumiditySample | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class HumidityFaultEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ASSERTED_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        LASTVALUE_FIELD_NUMBER: _builtins.int
        DURATIONSINCELASTSAMPLE_FIELD_NUMBER: _builtins.int
        LASTSAMPLEPERIOD_FIELD_NUMBER: _builtins.int
        asserted: _builtins.bool
        type: Global___HumidityTrait.HumidityFaultType.ValueType
        @_builtins.property
        def lastValue(self) -> Global___HumidityTrait.HumiditySample: ...
        @_builtins.property
        def durationSinceLastSample(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def lastSamplePeriod(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            asserted: _builtins.bool = ...,
            type: Global___HumidityTrait.HumidityFaultType.ValueType = ...,
            lastValue: Global___HumidityTrait.HumiditySample | None = ...,
            durationSinceLastSample: _duration_pb2.Duration | None = ...,
            lastSamplePeriod: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "durationSinceLastSample", b"durationSinceLastSample", "lastSamplePeriod", b"lastSamplePeriod", "lastValue", b"lastValue", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class HumidityPeriodicSamplesEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SAMPLEINTERVAL_FIELD_NUMBER: _builtins.int
        SAMPLES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sampleInterval(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___HumidityTrait.HumiditySample]: ...
        def __init__(
            self,
            *,
            sampleInterval: _duration_pb2.Duration | None = ...,
            samples: _abc.Iterable[Global___HumidityTrait.HumiditySample] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sampleInterval", b"sampleInterval", "samples", b"samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    HUMIDITYVALUE_FIELD_NUMBER: _builtins.int
    FAULTINFORMATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def humidityValue(self) -> Global___HumidityTrait.HumiditySample: ...
    @_builtins.property
    def faultInformation(self) -> Global___HumidityTrait.HumidityFaultInformation: ...
    def __init__(
        self,
        *,
        humidityValue: Global___HumidityTrait.HumiditySample | None = ...,
        faultInformation: Global___HumidityTrait.HumidityFaultInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "humidityValue", b"humidityValue"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["faultInformation", b"faultInformation", "humidityValue", b"humidityValue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HumidityTrait: _TypeAlias = HumidityTrait  # noqa: Y015
