"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from ...weave import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HomeInfoSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _HouseType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _HouseTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeInfoSettingsTrait._HouseType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        HOUSE_TYPE_UNSPECIFIED: HomeInfoSettingsTrait._HouseType.ValueType  # 0
        HOUSE_TYPE_SINGLE_FAMILY: HomeInfoSettingsTrait._HouseType.ValueType  # 1
        HOUSE_TYPE_MULTI_FAMILY: HomeInfoSettingsTrait._HouseType.ValueType  # 2
        HOUSE_TYPE_CONDO: HomeInfoSettingsTrait._HouseType.ValueType  # 3
        HOUSE_TYPE_BUSINESS: HomeInfoSettingsTrait._HouseType.ValueType  # 4
        HOUSE_TYPE_UNKNOWN: HomeInfoSettingsTrait._HouseType.ValueType  # 5

    class HouseType(_HouseType, metaclass=_HouseTypeEnumTypeWrapper): ...
    HOUSE_TYPE_UNSPECIFIED: HomeInfoSettingsTrait.HouseType.ValueType  # 0
    HOUSE_TYPE_SINGLE_FAMILY: HomeInfoSettingsTrait.HouseType.ValueType  # 1
    HOUSE_TYPE_MULTI_FAMILY: HomeInfoSettingsTrait.HouseType.ValueType  # 2
    HOUSE_TYPE_CONDO: HomeInfoSettingsTrait.HouseType.ValueType  # 3
    HOUSE_TYPE_BUSINESS: HomeInfoSettingsTrait.HouseType.ValueType  # 4
    HOUSE_TYPE_UNKNOWN: HomeInfoSettingsTrait.HouseType.ValueType  # 5

    class _NumThermostats:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _NumThermostatsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeInfoSettingsTrait._NumThermostats.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NUM_THERMOSTATS_UNSPECIFIED: HomeInfoSettingsTrait._NumThermostats.ValueType  # 0
        NUM_THERMOSTATS_ONE: HomeInfoSettingsTrait._NumThermostats.ValueType  # 1
        NUM_THERMOSTATS_TWO: HomeInfoSettingsTrait._NumThermostats.ValueType  # 2
        NUM_THERMOSTATS_THREE: HomeInfoSettingsTrait._NumThermostats.ValueType  # 3
        NUM_THERMOSTATS_FOUR: HomeInfoSettingsTrait._NumThermostats.ValueType  # 4
        NUM_THERMOSTATS_FIVE_PLUS: HomeInfoSettingsTrait._NumThermostats.ValueType  # 5
        NUM_THERMOSTATS_UNKNOWN: HomeInfoSettingsTrait._NumThermostats.ValueType  # 6

    class NumThermostats(_NumThermostats, metaclass=_NumThermostatsEnumTypeWrapper): ...
    NUM_THERMOSTATS_UNSPECIFIED: HomeInfoSettingsTrait.NumThermostats.ValueType  # 0
    NUM_THERMOSTATS_ONE: HomeInfoSettingsTrait.NumThermostats.ValueType  # 1
    NUM_THERMOSTATS_TWO: HomeInfoSettingsTrait.NumThermostats.ValueType  # 2
    NUM_THERMOSTATS_THREE: HomeInfoSettingsTrait.NumThermostats.ValueType  # 3
    NUM_THERMOSTATS_FOUR: HomeInfoSettingsTrait.NumThermostats.ValueType  # 4
    NUM_THERMOSTATS_FIVE_PLUS: HomeInfoSettingsTrait.NumThermostats.ValueType  # 5
    NUM_THERMOSTATS_UNKNOWN: HomeInfoSettingsTrait.NumThermostats.ValueType  # 6

    class _RenovationDate:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RenovationDateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeInfoSettingsTrait._RenovationDate.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        RENOVATION_DATE_UNSPECIFIED: HomeInfoSettingsTrait._RenovationDate.ValueType  # 0
        RENOVATION_DATE_DONT_KNOW: HomeInfoSettingsTrait._RenovationDate.ValueType  # 1
        RENOVATION_DATE_PRE_1940: HomeInfoSettingsTrait._RenovationDate.ValueType  # 2
        RENOVATION_DATE_1940: HomeInfoSettingsTrait._RenovationDate.ValueType  # 3
        RENOVATION_DATE_1950: HomeInfoSettingsTrait._RenovationDate.ValueType  # 4
        RENOVATION_DATE_1960: HomeInfoSettingsTrait._RenovationDate.ValueType  # 5
        RENOVATION_DATE_1970: HomeInfoSettingsTrait._RenovationDate.ValueType  # 6
        RENOVATION_DATE_1980: HomeInfoSettingsTrait._RenovationDate.ValueType  # 7
        RENOVATION_DATE_1990: HomeInfoSettingsTrait._RenovationDate.ValueType  # 8
        RENOVATION_DATE_2000: HomeInfoSettingsTrait._RenovationDate.ValueType  # 9
        RENOVATION_DATE_2010: HomeInfoSettingsTrait._RenovationDate.ValueType  # 10
        RENOVATION_DATE_UNKNOWN: HomeInfoSettingsTrait._RenovationDate.ValueType  # 11

    class RenovationDate(_RenovationDate, metaclass=_RenovationDateEnumTypeWrapper): ...
    RENOVATION_DATE_UNSPECIFIED: HomeInfoSettingsTrait.RenovationDate.ValueType  # 0
    RENOVATION_DATE_DONT_KNOW: HomeInfoSettingsTrait.RenovationDate.ValueType  # 1
    RENOVATION_DATE_PRE_1940: HomeInfoSettingsTrait.RenovationDate.ValueType  # 2
    RENOVATION_DATE_1940: HomeInfoSettingsTrait.RenovationDate.ValueType  # 3
    RENOVATION_DATE_1950: HomeInfoSettingsTrait.RenovationDate.ValueType  # 4
    RENOVATION_DATE_1960: HomeInfoSettingsTrait.RenovationDate.ValueType  # 5
    RENOVATION_DATE_1970: HomeInfoSettingsTrait.RenovationDate.ValueType  # 6
    RENOVATION_DATE_1980: HomeInfoSettingsTrait.RenovationDate.ValueType  # 7
    RENOVATION_DATE_1990: HomeInfoSettingsTrait.RenovationDate.ValueType  # 8
    RENOVATION_DATE_2000: HomeInfoSettingsTrait.RenovationDate.ValueType  # 9
    RENOVATION_DATE_2010: HomeInfoSettingsTrait.RenovationDate.ValueType  # 10
    RENOVATION_DATE_UNKNOWN: HomeInfoSettingsTrait.RenovationDate.ValueType  # 11

    class _MeasurementScale:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MeasurementScaleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HomeInfoSettingsTrait._MeasurementScale.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MEASUREMENT_SCALE_UNSPECIFIED: HomeInfoSettingsTrait._MeasurementScale.ValueType  # 0
        MEASUREMENT_SCALE_METRIC: HomeInfoSettingsTrait._MeasurementScale.ValueType  # 1
        MEASUREMENT_SCALE_IMPERIAL: HomeInfoSettingsTrait._MeasurementScale.ValueType  # 2

    class MeasurementScale(_MeasurementScale, metaclass=_MeasurementScaleEnumTypeWrapper): ...
    MEASUREMENT_SCALE_UNSPECIFIED: HomeInfoSettingsTrait.MeasurementScale.ValueType  # 0
    MEASUREMENT_SCALE_METRIC: HomeInfoSettingsTrait.MeasurementScale.ValueType  # 1
    MEASUREMENT_SCALE_IMPERIAL: HomeInfoSettingsTrait.MeasurementScale.ValueType  # 2

    HOUSETYPE_FIELD_NUMBER: _builtins.int
    USERSPECIFIEDNUMTHERMOSTATS_FIELD_NUMBER: _builtins.int
    RENOVATIONDATE_FIELD_NUMBER: _builtins.int
    STRUCTUREAREA_FIELD_NUMBER: _builtins.int
    MEASUREMENTSCALE_FIELD_NUMBER: _builtins.int
    houseType: Global___HomeInfoSettingsTrait.HouseType.ValueType
    userSpecifiedNumThermostats: Global___HomeInfoSettingsTrait.NumThermostats.ValueType
    renovationDate: Global___HomeInfoSettingsTrait.RenovationDate.ValueType
    structureArea: _builtins.float
    measurementScale: Global___HomeInfoSettingsTrait.MeasurementScale.ValueType
    def __init__(
        self,
        *,
        houseType: Global___HomeInfoSettingsTrait.HouseType.ValueType = ...,
        userSpecifiedNumThermostats: Global___HomeInfoSettingsTrait.NumThermostats.ValueType = ...,
        renovationDate: Global___HomeInfoSettingsTrait.RenovationDate.ValueType = ...,
        structureArea: _builtins.float = ...,
        measurementScale: Global___HomeInfoSettingsTrait.MeasurementScale.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["houseType", b"houseType", "measurementScale", b"measurementScale", "renovationDate", b"renovationDate", "structureArea", b"structureArea", "userSpecifiedNumThermostats", b"userSpecifiedNumThermostats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HomeInfoSettingsTrait: _TypeAlias = HomeInfoSettingsTrait  # noqa: Y015

@_typing.final
class StructureInfoTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _StatusCode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StructureInfoTrait._StatusCode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_CODE_UNSPECIFIED: StructureInfoTrait._StatusCode.ValueType  # 0
        STATUS_CODE_SUCCESS: StructureInfoTrait._StatusCode.ValueType  # 1
        STATUS_CODE_FAILURE: StructureInfoTrait._StatusCode.ValueType  # 2
        STATUS_CODE_UNAUTHORIZED: StructureInfoTrait._StatusCode.ValueType  # 3
        STATUS_CODE_RESOURCE_NOT_FOUND: StructureInfoTrait._StatusCode.ValueType  # 4

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    STATUS_CODE_UNSPECIFIED: StructureInfoTrait.StatusCode.ValueType  # 0
    STATUS_CODE_SUCCESS: StructureInfoTrait.StatusCode.ValueType  # 1
    STATUS_CODE_FAILURE: StructureInfoTrait.StatusCode.ValueType  # 2
    STATUS_CODE_UNAUTHORIZED: StructureInfoTrait.StatusCode.ValueType  # 3
    STATUS_CODE_RESOURCE_NOT_FOUND: StructureInfoTrait.StatusCode.ValueType  # 4

    @_typing.final
    class MaxResourceCountsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StructureDeletionEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STRUCTUREID_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def structureId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            structureId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["structureId", b"structureId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["structureId", b"structureId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SyncStructureMetadataRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESOURCEID_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        @_builtins.property
        def resourceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            resourceId: _common_pb2.ResourceId | None = ...,
            name: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "resourceId", b"resourceId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SyncStructureMetadataResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        RESOURCEID_FIELD_NUMBER: _builtins.int
        status: Global___StructureInfoTrait.StatusCode.ValueType
        @_builtins.property
        def resourceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            status: Global___StructureInfoTrait.StatusCode.ValueType = ...,
            resourceId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    RTSSTRUCTUREID_FIELD_NUMBER: _builtins.int
    MAXNESTGUARDCOUNT_FIELD_NUMBER: _builtins.int
    MAXNESTSENSORCOUNT_FIELD_NUMBER: _builtins.int
    MAXNESTCONNECTCOUNT_FIELD_NUMBER: _builtins.int
    PRIMARYFABRICID_FIELD_NUMBER: _builtins.int
    PAIRERID_FIELD_NUMBER: _builtins.int
    MAXNESTLOCKCOUNT_FIELD_NUMBER: _builtins.int
    MAXNESTMOONSTONECOUNT_FIELD_NUMBER: _builtins.int
    MAXNESTPROTECTCOUNT_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    CREATEDAT_FIELD_NUMBER: _builtins.int
    HGID_FIELD_NUMBER: _builtins.int
    MAXRESOURCECOUNTS_FIELD_NUMBER: _builtins.int
    rtsStructureId: _builtins.str
    maxNestGuardCount: _builtins.int
    maxNestSensorCount: _builtins.int
    maxNestConnectCount: _builtins.int
    primaryFabricId: _builtins.int
    maxNestLockCount: _builtins.int
    maxNestMoonstoneCount: _builtins.int
    maxNestProtectCount: _builtins.int
    name: _builtins.str
    @_builtins.property
    def pairerId(self) -> _common_pb2.ResourceId: ...
    @_builtins.property
    def createdAt(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def hgId(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def maxResourceCounts(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]: ...
    def __init__(
        self,
        *,
        rtsStructureId: _builtins.str = ...,
        maxNestGuardCount: _builtins.int = ...,
        maxNestSensorCount: _builtins.int = ...,
        maxNestConnectCount: _builtins.int = ...,
        primaryFabricId: _builtins.int = ...,
        pairerId: _common_pb2.ResourceId | None = ...,
        maxNestLockCount: _builtins.int = ...,
        maxNestMoonstoneCount: _builtins.int = ...,
        maxNestProtectCount: _builtins.int = ...,
        name: _builtins.str = ...,
        createdAt: _timestamp_pb2.Timestamp | None = ...,
        hgId: _wrappers_pb2.StringValue | None = ...,
        maxResourceCounts: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["createdAt", b"createdAt", "hgId", b"hgId", "pairerId", b"pairerId"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["createdAt", b"createdAt", "hgId", b"hgId", "maxNestConnectCount", b"maxNestConnectCount", "maxNestGuardCount", b"maxNestGuardCount", "maxNestLockCount", b"maxNestLockCount", "maxNestMoonstoneCount", b"maxNestMoonstoneCount", "maxNestProtectCount", b"maxNestProtectCount", "maxNestSensorCount", b"maxNestSensorCount", "maxResourceCounts", b"maxResourceCounts", "name", b"name", "pairerId", b"pairerId", "primaryFabricId", b"primaryFabricId", "rtsStructureId", b"rtsStructureId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StructureInfoTrait: _TypeAlias = StructureInfoTrait  # noqa: Y015

@_typing.final
class StructureLocationTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _StatusCode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StructureLocationTrait._StatusCode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_CODE_UNSPECIFIED: StructureLocationTrait._StatusCode.ValueType  # 0
        STATUS_CODE_SUCCESS: StructureLocationTrait._StatusCode.ValueType  # 1
        STATUS_CODE_FAILURE: StructureLocationTrait._StatusCode.ValueType  # 2
        STATUS_CODE_UNAUTHORIZED: StructureLocationTrait._StatusCode.ValueType  # 3
        STATUS_CODE_RESOURCE_NOT_FOUND: StructureLocationTrait._StatusCode.ValueType  # 4

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    STATUS_CODE_UNSPECIFIED: StructureLocationTrait.StatusCode.ValueType  # 0
    STATUS_CODE_SUCCESS: StructureLocationTrait.StatusCode.ValueType  # 1
    STATUS_CODE_FAILURE: StructureLocationTrait.StatusCode.ValueType  # 2
    STATUS_CODE_UNAUTHORIZED: StructureLocationTrait.StatusCode.ValueType  # 3
    STATUS_CODE_RESOURCE_NOT_FOUND: StructureLocationTrait.StatusCode.ValueType  # 4

    @_typing.final
    class GeoCoordinate(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LATITUDE_FIELD_NUMBER: _builtins.int
        LONGITUDE_FIELD_NUMBER: _builtins.int
        latitude: _builtins.float
        longitude: _builtins.float
        def __init__(
            self,
            *,
            latitude: _builtins.float = ...,
            longitude: _builtins.float = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["latitude", b"latitude", "longitude", b"longitude"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class UpdateAddressRequest(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RESOURCEID_FIELD_NUMBER: _builtins.int
        POSTALCODE_FIELD_NUMBER: _builtins.int
        COUNTRYCODE_FIELD_NUMBER: _builtins.int
        ADDRESSLINES_FIELD_NUMBER: _builtins.int
        CITY_FIELD_NUMBER: _builtins.int
        STATE_FIELD_NUMBER: _builtins.int
        GEOCOORDINATE_FIELD_NUMBER: _builtins.int
        TIMEZONENAME_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def resourceId(self) -> _common_pb2.ResourceId: ...
        @_builtins.property
        def postalCode(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def countryCode(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def addressLines(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        @_builtins.property
        def city(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def state(self) -> _wrappers_pb2.StringValue: ...
        @_builtins.property
        def geoCoordinate(self) -> Global___StructureLocationTrait.GeoCoordinate: ...
        @_builtins.property
        def timezoneName(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            resourceId: _common_pb2.ResourceId | None = ...,
            postalCode: _wrappers_pb2.StringValue | None = ...,
            countryCode: _wrappers_pb2.StringValue | None = ...,
            addressLines: _abc.Iterable[_builtins.str] | None = ...,
            city: _wrappers_pb2.StringValue | None = ...,
            state: _wrappers_pb2.StringValue | None = ...,
            geoCoordinate: Global___StructureLocationTrait.GeoCoordinate | None = ...,
            timezoneName: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["city", b"city", "countryCode", b"countryCode", "geoCoordinate", b"geoCoordinate", "postalCode", b"postalCode", "resourceId", b"resourceId", "state", b"state", "timezoneName", b"timezoneName"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["addressLines", b"addressLines", "city", b"city", "countryCode", b"countryCode", "geoCoordinate", b"geoCoordinate", "postalCode", b"postalCode", "resourceId", b"resourceId", "state", b"state", "timezoneName", b"timezoneName"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class UpdateAddressResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        RESOURCEID_FIELD_NUMBER: _builtins.int
        status: Global___StructureLocationTrait.StatusCode.ValueType
        @_builtins.property
        def resourceId(self) -> _common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            status: Global___StructureLocationTrait.StatusCode.ValueType = ...,
            resourceId: _common_pb2.ResourceId | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["resourceId", b"resourceId", "status", b"status"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    POSTALCODE_FIELD_NUMBER: _builtins.int
    COUNTRYCODE_FIELD_NUMBER: _builtins.int
    ADDRESSLINES_FIELD_NUMBER: _builtins.int
    CITY_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    GEOCOORDINATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def postalCode(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def countryCode(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def addressLines(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def city(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def state(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def geoCoordinate(self) -> Global___StructureLocationTrait.GeoCoordinate: ...
    def __init__(
        self,
        *,
        postalCode: _wrappers_pb2.StringValue | None = ...,
        countryCode: _wrappers_pb2.StringValue | None = ...,
        addressLines: _abc.Iterable[_builtins.str] | None = ...,
        city: _wrappers_pb2.StringValue | None = ...,
        state: _wrappers_pb2.StringValue | None = ...,
        geoCoordinate: Global___StructureLocationTrait.GeoCoordinate | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["city", b"city", "countryCode", b"countryCode", "geoCoordinate", b"geoCoordinate", "postalCode", b"postalCode", "state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["addressLines", b"addressLines", "city", b"city", "countryCode", b"countryCode", "geoCoordinate", b"geoCoordinate", "postalCode", b"postalCode", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StructureLocationTrait: _TypeAlias = StructureLocationTrait  # noqa: Y015
