"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SoyMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SoyTemplateMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ParametersEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.int
            @_builtins.property
            def value(self) -> Global___SoyMessage.SoyParameter: ...
            def __init__(
                self,
                *,
                key: _builtins.int = ...,
                value: Global___SoyMessage.SoyParameter | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

        MESSAGENAMESPACE_FIELD_NUMBER: _builtins.int
        PARAMETERS_FIELD_NUMBER: _builtins.int
        messageNamespace: _builtins.str
        @_builtins.property
        def parameters(self) -> _containers.MessageMap[_builtins.int, Global___SoyMessage.SoyParameter]: ...
        def __init__(
            self,
            *,
            messageNamespace: _builtins.str = ...,
            parameters: _abc.Mapping[_builtins.int, Global___SoyMessage.SoyParameter] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["messageNamespace", b"messageNamespace", "parameters", b"parameters"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Any(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TYPEURL_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        typeUrl: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            typeUrl: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["typeUrl", b"typeUrl", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SoyParameter(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SoyMessage.SoyParameterValue: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___SoyMessage.SoyParameterValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SoyParameterValue(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SINGLEVALUE_FIELD_NUMBER: _builtins.int
        BOOLVALUE_FIELD_NUMBER: _builtins.int
        INTVALUE_FIELD_NUMBER: _builtins.int
        PROTOVALUE_FIELD_NUMBER: _builtins.int
        STRINGLISTVALUE_FIELD_NUMBER: _builtins.int
        singleValue: _builtins.str
        boolValue: _builtins.bool
        intValue: _builtins.int
        @_builtins.property
        def protoValue(self) -> Global___SoyMessage.Any: ...
        @_builtins.property
        def stringListValue(self) -> Global___SoyMessage.StringList: ...
        def __init__(
            self,
            *,
            singleValue: _builtins.str = ...,
            boolValue: _builtins.bool = ...,
            intValue: _builtins.int = ...,
            protoValue: Global___SoyMessage.Any | None = ...,
            stringListValue: Global___SoyMessage.StringList | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["protoValue", b"protoValue", "stringListValue", b"stringListValue"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["boolValue", b"boolValue", "intValue", b"intValue", "protoValue", b"protoValue", "singleValue", b"singleValue", "stringListValue", b"stringListValue"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StringList(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        VALUES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            values: _abc.Iterable[_builtins.str] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SoyTemplateImage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        URL_FIELD_NUMBER: _builtins.int
        ACCESSIBILITYTEXT_FIELD_NUMBER: _builtins.int
        WIDTH_FIELD_NUMBER: _builtins.int
        HEIGHT_FIELD_NUMBER: _builtins.int
        url: _builtins.str
        width: _builtins.int
        height: _builtins.int
        @_builtins.property
        def accessibilityText(self) -> Global___SoyMessage.SoyTemplateMessage: ...
        def __init__(
            self,
            *,
            url: _builtins.str = ...,
            accessibilityText: Global___SoyMessage.SoyTemplateMessage | None = ...,
            width: _builtins.int = ...,
            height: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["accessibilityText", b"accessibilityText"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["accessibilityText", b"accessibilityText", "height", b"height", "url", b"url", "width", b"width"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SoyTemplateInfo(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MSGIDSTRING_FIELD_NUMBER: _builtins.int
        msgIdString: _builtins.str
        def __init__(
            self,
            *,
            msgIdString: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["msgIdString", b"msgIdString"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___SoyMessage: _TypeAlias = SoyMessage  # noqa: Y015

@_typing.final
class EnhancedPathlightSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PathlightBrightnessDiscrete:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PathlightBrightnessDiscreteEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EnhancedPathlightSettingsTrait._PathlightBrightnessDiscrete.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PATHLIGHT_BRIGHTNESS_DISCRETE_UNSPECIFIED: EnhancedPathlightSettingsTrait._PathlightBrightnessDiscrete.ValueType  # 0
        PATHLIGHT_BRIGHTNESS_DISCRETE_LOW: EnhancedPathlightSettingsTrait._PathlightBrightnessDiscrete.ValueType  # 1
        PATHLIGHT_BRIGHTNESS_DISCRETE_MEDIUM: EnhancedPathlightSettingsTrait._PathlightBrightnessDiscrete.ValueType  # 2
        PATHLIGHT_BRIGHTNESS_DISCRETE_HIGH: EnhancedPathlightSettingsTrait._PathlightBrightnessDiscrete.ValueType  # 3

    class PathlightBrightnessDiscrete(_PathlightBrightnessDiscrete, metaclass=_PathlightBrightnessDiscreteEnumTypeWrapper): ...
    PATHLIGHT_BRIGHTNESS_DISCRETE_UNSPECIFIED: EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType  # 0
    PATHLIGHT_BRIGHTNESS_DISCRETE_LOW: EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType  # 1
    PATHLIGHT_BRIGHTNESS_DISCRETE_MEDIUM: EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType  # 2
    PATHLIGHT_BRIGHTNESS_DISCRETE_HIGH: EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType  # 3

    class _PathlightCondition:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PathlightConditionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EnhancedPathlightSettingsTrait._PathlightCondition.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PATHLIGHT_CONDITION_UNSPECIFIED: EnhancedPathlightSettingsTrait._PathlightCondition.ValueType  # 0
        PATHLIGHT_CONDITION_LINE_POWER: EnhancedPathlightSettingsTrait._PathlightCondition.ValueType  # 1
        PATHLIGHT_CONDITION_DARKNESS: EnhancedPathlightSettingsTrait._PathlightCondition.ValueType  # 2
        PATHLIGHT_CONDITION_MOTION: EnhancedPathlightSettingsTrait._PathlightCondition.ValueType  # 4

    class PathlightCondition(_PathlightCondition, metaclass=_PathlightConditionEnumTypeWrapper): ...
    PATHLIGHT_CONDITION_UNSPECIFIED: EnhancedPathlightSettingsTrait.PathlightCondition.ValueType  # 0
    PATHLIGHT_CONDITION_LINE_POWER: EnhancedPathlightSettingsTrait.PathlightCondition.ValueType  # 1
    PATHLIGHT_CONDITION_DARKNESS: EnhancedPathlightSettingsTrait.PathlightCondition.ValueType  # 2
    PATHLIGHT_CONDITION_MOTION: EnhancedPathlightSettingsTrait.PathlightCondition.ValueType  # 4

    @_typing.final
    class TriggersEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___EnhancedPathlightSettingsTrait.PathlightTrigger: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___EnhancedPathlightSettingsTrait.PathlightTrigger | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PathlightTrigger(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TIMEOUT_FIELD_NUMBER: _builtins.int
        BRIGHTNESSDISCRETE_FIELD_NUMBER: _builtins.int
        ACTIVATIONCONDITIONS_FIELD_NUMBER: _builtins.int
        brightnessDiscrete: Global___EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType
        @_builtins.property
        def timeout(self) -> _duration_pb2.Duration: ...
        @_builtins.property
        def activationConditions(self) -> _containers.RepeatedScalarFieldContainer[Global___EnhancedPathlightSettingsTrait.PathlightCondition.ValueType]: ...
        def __init__(
            self,
            *,
            timeout: _duration_pb2.Duration | None = ...,
            brightnessDiscrete: Global___EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType = ...,
            activationConditions: _abc.Iterable[Global___EnhancedPathlightSettingsTrait.PathlightCondition.ValueType] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["timeout", b"timeout"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["activationConditions", b"activationConditions", "brightnessDiscrete", b"brightnessDiscrete", "timeout", b"timeout"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TRIGGERS_FIELD_NUMBER: _builtins.int
    BRIGHTNESSDISCRETE_FIELD_NUMBER: _builtins.int
    brightnessDiscrete: Global___EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType
    @_builtins.property
    def triggers(self) -> _containers.MessageMap[_builtins.int, Global___EnhancedPathlightSettingsTrait.PathlightTrigger]: ...
    def __init__(
        self,
        *,
        triggers: _abc.Mapping[_builtins.int, Global___EnhancedPathlightSettingsTrait.PathlightTrigger] | None = ...,
        brightnessDiscrete: Global___EnhancedPathlightSettingsTrait.PathlightBrightnessDiscrete.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["brightnessDiscrete", b"brightnessDiscrete", "triggers", b"triggers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnhancedPathlightSettingsTrait: _TypeAlias = EnhancedPathlightSettingsTrait  # noqa: Y015

@_typing.final
class UserInteractionTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class UserInteractionDetectedEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        UNUSED_FIELD_NUMBER: _builtins.int
        unused: _builtins.int
        def __init__(
            self,
            *,
            unused: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["unused", b"unused"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___UserInteractionTrait: _TypeAlias = UserInteractionTrait  # noqa: Y015

@_typing.final
class EnhancedPathlightStateTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ActivationState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ActivationStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EnhancedPathlightStateTrait._ActivationState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ACTIVATION_STATE_UNSPECIFIED: EnhancedPathlightStateTrait._ActivationState.ValueType  # 0
        ACTIVATION_STATE_OFF: EnhancedPathlightStateTrait._ActivationState.ValueType  # 1
        ACTIVATION_STATE_TIMED_OUT: EnhancedPathlightStateTrait._ActivationState.ValueType  # 2
        ACTIVATION_STATE_ACTIVE: EnhancedPathlightStateTrait._ActivationState.ValueType  # 3

    class ActivationState(_ActivationState, metaclass=_ActivationStateEnumTypeWrapper): ...
    ACTIVATION_STATE_UNSPECIFIED: EnhancedPathlightStateTrait.ActivationState.ValueType  # 0
    ACTIVATION_STATE_OFF: EnhancedPathlightStateTrait.ActivationState.ValueType  # 1
    ACTIVATION_STATE_TIMED_OUT: EnhancedPathlightStateTrait.ActivationState.ValueType  # 2
    ACTIVATION_STATE_ACTIVE: EnhancedPathlightStateTrait.ActivationState.ValueType  # 3

    @_typing.final
    class PathlightStateChangeEvent(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATE_FIELD_NUMBER: _builtins.int
        CONDITIONS_FIELD_NUMBER: _builtins.int
        ACTIVATEDCONDITIONS_FIELD_NUMBER: _builtins.int
        PREVIOUSSTATE_FIELD_NUMBER: _builtins.int
        ACTIVEDURATION_FIELD_NUMBER: _builtins.int
        state: Global___EnhancedPathlightStateTrait.ActivationState.ValueType
        previousState: Global___EnhancedPathlightStateTrait.ActivationState.ValueType
        @_builtins.property
        def conditions(self) -> _containers.RepeatedScalarFieldContainer[Global___EnhancedPathlightSettingsTrait.PathlightCondition.ValueType]: ...
        @_builtins.property
        def activatedConditions(self) -> _containers.RepeatedScalarFieldContainer[Global___EnhancedPathlightSettingsTrait.PathlightCondition.ValueType]: ...
        @_builtins.property
        def activeDuration(self) -> _duration_pb2.Duration: ...
        def __init__(
            self,
            *,
            state: Global___EnhancedPathlightStateTrait.ActivationState.ValueType = ...,
            conditions: _abc.Iterable[Global___EnhancedPathlightSettingsTrait.PathlightCondition.ValueType] | None = ...,
            activatedConditions: _abc.Iterable[Global___EnhancedPathlightSettingsTrait.PathlightCondition.ValueType] | None = ...,
            previousState: Global___EnhancedPathlightStateTrait.ActivationState.ValueType = ...,
            activeDuration: _duration_pb2.Duration | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["activeDuration", b"activeDuration"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["activatedConditions", b"activatedConditions", "activeDuration", b"activeDuration", "conditions", b"conditions", "previousState", b"previousState", "state", b"state"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    def __init__(
        self,
    ) -> None: ...

Global___EnhancedPathlightStateTrait: _TypeAlias = EnhancedPathlightStateTrait  # noqa: Y015

@_typing.final
class PathlightSettingsTrait(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PathlightBrightness:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PathlightBrightnessEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PathlightSettingsTrait._PathlightBrightness.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PATHLIGHT_BRIGHTNESS_UNSPECIFIED: PathlightSettingsTrait._PathlightBrightness.ValueType  # 0
        PATHLIGHT_BRIGHTNESS_OFF: PathlightSettingsTrait._PathlightBrightness.ValueType  # 1
        PATHLIGHT_BRIGHTNESS_LOW: PathlightSettingsTrait._PathlightBrightness.ValueType  # 2
        PATHLIGHT_BRIGHTNESS_MEDIUM: PathlightSettingsTrait._PathlightBrightness.ValueType  # 3
        PATHLIGHT_BRIGHTNESS_HIGH: PathlightSettingsTrait._PathlightBrightness.ValueType  # 4

    class PathlightBrightness(_PathlightBrightness, metaclass=_PathlightBrightnessEnumTypeWrapper): ...
    PATHLIGHT_BRIGHTNESS_UNSPECIFIED: PathlightSettingsTrait.PathlightBrightness.ValueType  # 0
    PATHLIGHT_BRIGHTNESS_OFF: PathlightSettingsTrait.PathlightBrightness.ValueType  # 1
    PATHLIGHT_BRIGHTNESS_LOW: PathlightSettingsTrait.PathlightBrightness.ValueType  # 2
    PATHLIGHT_BRIGHTNESS_MEDIUM: PathlightSettingsTrait.PathlightBrightness.ValueType  # 3
    PATHLIGHT_BRIGHTNESS_HIGH: PathlightSettingsTrait.PathlightBrightness.ValueType  # 4

    PATHLIGHTBRIGHTNESS_FIELD_NUMBER: _builtins.int
    pathlightBrightness: Global___PathlightSettingsTrait.PathlightBrightness.ValueType
    def __init__(
        self,
        *,
        pathlightBrightness: Global___PathlightSettingsTrait.PathlightBrightness.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pathlightBrightness", b"pathlightBrightness"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PathlightSettingsTrait: _TypeAlias = PathlightSettingsTrait  # noqa: Y015
